export type Locale={code:string;nativeName:string;englishName:string;direction:'ltr'|'rtl'};
export const locales:Locale[]=[
{code:'en',nativeName:'English',englishName:'English',direction:'ltr'},{code:'hi',nativeName:'हिन्दी',englishName:'Hindi',direction:'ltr'},{code:'bn',nativeName:'বাংলা',englishName:'Bengali',direction:'ltr'},{code:'mr',nativeName:'मराठी',englishName:'Marathi',direction:'ltr'},{code:'ta',nativeName:'தமிழ்',englishName:'Tamil',direction:'ltr'},{code:'te',nativeName:'తెలుగు',englishName:'Telugu',direction:'ltr'},{code:'gu',nativeName:'ગુજરાતી',englishName:'Gujarati',direction:'ltr'},{code:'kn',nativeName:'ಕನ್ನಡ',englishName:'Kannada',direction:'ltr'},{code:'ml',nativeName:'മലയാളം',englishName:'Malayalam',direction:'ltr'},{code:'pa',nativeName:'ਪੰਜਾਬੀ',englishName:'Punjabi',direction:'ltr'},{code:'ur',nativeName:'اردو',englishName:'Urdu',direction:'rtl'},{code:'as',nativeName:'অসমীয়া',englishName:'Assamese',direction:'ltr'},{code:'or',nativeName:'ଓଡ଼ିଆ',englishName:'Odia',direction:'ltr'},{code:'ne',nativeName:'नेपाली',englishName:'Nepali',direction:'ltr'},{code:'sa',nativeName:'संस्कृतम्',englishName:'Sanskrit',direction:'ltr'},{code:'kok',nativeName:'कोंकणी',englishName:'Konkani',direction:'ltr'},{code:'mai',nativeName:'मैथिली',englishName:'Maithili',direction:'ltr'},{code:'bho',nativeName:'भोजपुरी',englishName:'Bhojpuri',direction:'ltr'},{code:'ks',nativeName:'कॉशुर / کٲشُر',englishName:'Kashmiri',direction:'rtl'},{code:'sd',nativeName:'सिन्धी / سنڌي',englishName:'Sindhi',direction:'rtl'},{code:'doi',nativeName:'डोगरी',englishName:'Dogri',direction:'ltr'},{code:'sat',nativeName:'ᱥᱟᱱᱛᱟᱲᱤ',englishName:'Santali',direction:'ltr'},{code:'mni',nativeName:'ꯃꯤꯇꯩ ꯂꯣꯟ',englishName:'Manipuri',direction:'ltr'},
{code:'ar',nativeName:'العربية',englishName:'Arabic',direction:'rtl'},{code:'fa',nativeName:'فارسی',englishName:'Persian',direction:'rtl'},{code:'tr',nativeName:'Türkçe',englishName:'Turkish',direction:'ltr'},{code:'fr',nativeName:'Français',englishName:'French',direction:'ltr'},{code:'de',nativeName:'Deutsch',englishName:'German',direction:'ltr'},{code:'es',nativeName:'Español',englishName:'Spanish',direction:'ltr'},{code:'pt',nativeName:'Português',englishName:'Portuguese',direction:'ltr'},{code:'it',nativeName:'Italiano',englishName:'Italian',direction:'ltr'},{code:'ru',nativeName:'Русский',englishName:'Russian',direction:'ltr'},{code:'uk',nativeName:'Українська',englishName:'Ukrainian',direction:'ltr'},{code:'pl',nativeName:'Polski',englishName:'Polish',direction:'ltr'},{code:'nl',nativeName:'Nederlands',englishName:'Dutch',direction:'ltr'},{code:'sv',nativeName:'Svenska',englishName:'Swedish',direction:'ltr'},{code:'ja',nativeName:'日本語',englishName:'Japanese',direction:'ltr'},{code:'ko',nativeName:'한국어',englishName:'Korean',direction:'ltr'},{code:'zh',nativeName:'简体中文',englishName:'Chinese (Simplified)',direction:'ltr'},{code:'zh-TW',nativeName:'繁體中文',englishName:'Chinese (Traditional)',direction:'ltr'},{code:'th',nativeName:'ไทย',englishName:'Thai',direction:'ltr'},{code:'vi',nativeName:'Tiếng Việt',englishName:'Vietnamese',direction:'ltr'},{code:'id',nativeName:'Bahasa Indonesia',englishName:'Indonesian',direction:'ltr'},{code:'ms',nativeName:'Bahasa Melayu',englishName:'Malay',direction:'ltr'},{code:'fil',nativeName:'Filipino',englishName:'Filipino',direction:'ltr'},{code:'sw',nativeName:'Kiswahili',englishName:'Swahili',direction:'ltr'},{code:'he',nativeName:'עברית',englishName:'Hebrew',direction:'rtl'}
];
export const defaultLocale='en';
const STORAGE_KEY='drustpoll.locale';
export function getLocale(code:string){return locales.find(l=>l.code===code)||locales[0];}
export async function hasSavedLocale(){try{const{default:AsyncStorage}=await import('@react-native-async-storage/async-storage');return Boolean(await AsyncStorage.getItem(STORAGE_KEY));}catch{return false;}}
export async function loadLocale(){try{const{default:AsyncStorage}=await import('@react-native-async-storage/async-storage');return (await AsyncStorage.getItem(STORAGE_KEY))??defaultLocale;}catch{return defaultLocale;}}
export async function saveLocale(code:string){if(!locales.some(l=>l.code===code))return;const{default:AsyncStorage}=await import('@react-native-async-storage/async-storage');await AsyncStorage.setItem(STORAGE_KEY,code);}

type Vars=Record<string,string|number>;
type Dictionary=Record<string,string>;
const en:Dictionary={welcome:'Welcome',continue:'Continue',back:'Back',done:'Done',create:'Create account',signIn:'Sign in',name:'Name',username:'Username',email:'Email',phone:'Phone',password:'Password',language:'Language',chooseLanguage:'Choose your language',searchLanguages:'Search languages',applyLanguage:'Use this language',yourWorld:'Your world, naturally.',home:'Home',explore:'Explore',createNav:'Create',connect:'Connect',you:'You',market:'Market',notifications:'Notifications',settings:'Settings',profile:'Profile',privacy:'Privacy',security:'Security',safety:'Safety',save:'Save',cancel:'Cancel',retry:'Try again',loading:'Loading…',offline:'You are offline',success:'Done',error:'Something went wrong',forYou:'For You',following:'Following',latest:'Latest',share:'Share',like:'Like',comment:'Comment',savePost:'Save',more:'More',close:'Close',next:'Next',verify:'Verify',resend:'Resend code',verification:'Verification',verificationTitle:'Verify your email',verificationBody:'Enter the 6-digit code we sent you.',codeExpired:'This code has expired.',invalidCode:'That code is not valid.',checkInbox:'Check your inbox',privacyChoice:'Your choices stay yours.'};
const packs:Record<string,Dictionary>={
 hi:{welcome:'स्वागत है',continue:'जारी रखें',back:'वापस',done:'हो गया',create:'खाता बनाएँ',signIn:'साइन इन',name:'नाम',username:'यूज़रनेम',email:'ईमेल',phone:'फ़ोन',password:'पासवर्ड',language:'भाषा',chooseLanguage:'अपनी भाषा चुनें',searchLanguages:'भाषाएँ खोजें',applyLanguage:'इस भाषा का उपयोग करें',yourWorld:'आपकी दुनिया, स्वाभाविक रूप से।',home:'होम',explore:'एक्सप्लोर',createNav:'बनाएँ',connect:'कनेक्ट',you:'आप',market:'मार्केट',notifications:'सूचनाएँ',settings:'सेटिंग्स',profile:'प्रोफ़ाइल',privacy:'गोपनीयता',security:'सुरक्षा',safety:'सेफ़्टी',save:'सहेजें',cancel:'रद्द करें',retry:'फिर कोशिश करें',loading:'लोड हो रहा है…',offline:'आप ऑफ़लाइन हैं',success:'हो गया',error:'कुछ गलत हुआ',forYou:'आपके लिए',following:'फ़ॉलो किए',latest:'नवीनतम',share:'शेयर',like:'पसंद',comment:'कमेंट',savePost:'सहेजें',more:'और',close:'बंद करें',next:'आगे',verify:'सत्यापित करें',resend:'कोड फिर भेजें',verification:'सत्यापन',verificationTitle:'ईमेल सत्यापित करें',verificationBody:'आपको भेजा गया 6 अंकों का कोड डालें।',codeExpired:'यह कोड समाप्त हो गया है।',invalidCode:'यह कोड सही नहीं है।',checkInbox:'अपना इनबॉक्स देखें',privacyChoice:'आपके विकल्प आपके हैं।'},
 bn:{welcome:'স্বাগতম',continue:'চালিয়ে যান',back:'ফিরে যান',done:'সম্পন্ন',create:'অ্যাকাউন্ট তৈরি করুন',signIn:'সাইন ইন',name:'নাম',username:'ইউজারনেম',email:'ইমেল',phone:'ফোন',password:'পাসওয়ার্ড',language:'ভাষা',chooseLanguage:'আপনার ভাষা বেছে নিন',searchLanguages:'ভাষা খুঁজুন',applyLanguage:'এই ভাষা ব্যবহার করুন',yourWorld:'আপনার জগত, স্বাভাবিকভাবে।',home:'হোম',explore:'এক্সপ্লোর',createNav:'তৈরি করুন',connect:'কানেক্ট',you:'আপনি',market:'মার্কেট',notifications:'বিজ্ঞপ্তি',settings:'সেটিংস',profile:'প্রোফাইল',privacy:'গোপনীয়তা',security:'নিরাপত্তা',safety:'সেফটি',save:'সংরক্ষণ',cancel:'বাতিল',retry:'আবার চেষ্টা করুন',loading:'লোড হচ্ছে…',offline:'আপনি অফলাইনে আছেন',success:'সম্পন্ন',error:'কিছু ভুল হয়েছে',forYou:'আপনার জন্য',following:'অনুসরণ',latest:'সাম্প্রতিক',share:'শেয়ার',like:'পছন্দ',comment:'মন্তব্য',savePost:'সংরক্ষণ',more:'আরও',close:'বন্ধ',next:'পরবর্তী',verify:'যাচাই করুন',resend:'কোড আবার পাঠান',verification:'যাচাইকরণ',verificationTitle:'ইমেল যাচাই করুন',verificationBody:'আপনাকে পাঠানো ৬ সংখ্যার কোড লিখুন।',codeExpired:'এই কোডের মেয়াদ শেষ।',invalidCode:'কোডটি সঠিক নয়।',checkInbox:'আপনার ইনবক্স দেখুন',privacyChoice:'আপনার পছন্দ আপনারই।'},
 mr:{welcome:'स्वागत आहे',continue:'पुढे जा',back:'मागे',done:'पूर्ण',create:'खाते तयार करा',signIn:'साइन इन',name:'नाव',username:'वापरकर्तानाव',email:'ईमेल',phone:'फोन',password:'पासवर्ड',language:'भाषा',chooseLanguage:'तुमची भाषा निवडा',searchLanguages:'भाषा शोधा',applyLanguage:'ही भाषा वापरा',yourWorld:'तुमची दुनिया, सहजपणे.',home:'होम',explore:'एक्सप्लोर',createNav:'तयार करा',connect:'कनेक्ट',you:'तुम्ही',market:'मार्केट',notifications:'सूचना',settings:'सेटिंग्ज',profile:'प्रोफाइल',privacy:'गोपनीयता',security:'सुरक्षा',safety:'सेफ्टी',save:'जतन करा',cancel:'रद्द करा',retry:'पुन्हा प्रयत्न करा',loading:'लोड होत आहे…',offline:'तुम्ही ऑफलाइन आहात',success:'पूर्ण',error:'काहीतरी चूक झाली',forYou:'तुमच्यासाठी',following:'फॉलो केलेले',latest:'नवीनतम',share:'शेअर',like:'आवडले',comment:'कमेंट',savePost:'जतन करा',more:'अधिक',close:'बंद',next:'पुढे',verify:'पडताळा',resend:'कोड पुन्हा पाठवा',verification:'पडताळणी',verificationTitle:'ईमेलची पडताळणी करा',verificationBody:'तुम्हाला पाठवलेला ६ अंकी कोड टाका.',codeExpired:'हा कोड कालबाह्य झाला आहे.',invalidCode:'हा कोड योग्य नाही.',checkInbox:'तुमचा इनबॉक्स पहा',privacyChoice:'तुमच्या निवडी तुमच्या आहेत.'},
 ta:{welcome:'வரவேற்கிறோம்',continue:'தொடரவும்',back:'பின்செல்',done:'முடிந்தது',create:'கணக்கை உருவாக்கு',signIn:'உள்நுழை',name:'பெயர்',username:'பயனர்பெயர்',email:'மின்னஞ்சல்',phone:'தொலைபேசி',password:'கடவுச்சொல்',language:'மொழி',chooseLanguage:'உங்கள் மொழியைத் தேர்ந்தெடுக்கவும்',searchLanguages:'மொழிகளைத் தேடுங்கள்',applyLanguage:'இந்த மொழியைப் பயன்படுத்து',yourWorld:'உங்கள் உலகம், இயல்பாக.',home:'முகப்பு',explore:'ஆராயுங்கள்',createNav:'உருவாக்கு',connect:'இணைப்பு',you:'நீங்கள்',market:'சந்தை',notifications:'அறிவிப்புகள்',settings:'அமைப்புகள்',profile:'சுயவிவரம்',privacy:'தனியுரிமை',security:'பாதுகாப்பு',safety:'பாதுகாப்பு',save:'சேமி',cancel:'ரத்து',retry:'மீண்டும் முயற்சி',loading:'ஏற்றுகிறது…',offline:'நீங்கள் ஆஃப்லைனில் உள்ளீர்கள்',success:'முடிந்தது',error:'ஏதோ தவறு நடந்தது',forYou:'உங்களுக்காக',following:'பின்தொடர்வது',latest:'சமீபத்திய',share:'பகிர்',like:'விருப்பம்',comment:'கருத்து',savePost:'சேமி',more:'மேலும்',close:'மூடு',next:'அடுத்து',verify:'சரிபார்',resend:'குறியீட்டை மீண்டும் அனுப்பு',verification:'சரிபார்ப்பு',verificationTitle:'மின்னஞ்சலைச் சரிபார்க்கவும்',verificationBody:'அனுப்பிய 6 இலக்க குறியீட்டை உள்ளிடவும்.',codeExpired:'இந்த குறியீடு காலாவதியானது.',invalidCode:'குறியீடு தவறானது.',checkInbox:'உங்கள் இன்பாக்ஸைப் பாருங்கள்',privacyChoice:'உங்கள் தேர்வுகள் உங்களுடையவை.'},
 te:{welcome:'స్వాగతం',continue:'కొనసాగించండి',back:'వెనుకకు',done:'పూర్తయింది',create:'ఖాతా సృష్టించండి',signIn:'సైన్ ఇన్',name:'పేరు',username:'వినియోగదారు పేరు',email:'ఇమెయిల్',phone:'ఫోన్',password:'పాస్‌వర్డ్',language:'భాష',chooseLanguage:'మీ భాషను ఎంచుకోండి',searchLanguages:'భాషలను వెతకండి',applyLanguage:'ఈ భాషను ఉపయోగించండి',yourWorld:'మీ ప్రపంచం, సహజంగా.',home:'హోమ్',explore:'ఎక్స్‌ప్లోర్',createNav:'సృష్టించండి',connect:'కనెక్ట్',you:'మీరు',market:'మార్కెట్',notifications:'నోటిఫికేషన్లు',settings:'సెట్టింగ్స్',profile:'ప్రొఫైల్',privacy:'గోప్యత',security:'భద్రత',safety:'సేఫ్టీ',save:'సేవ్',cancel:'రద్దు',retry:'మళ్లీ ప్రయత్నించండి',loading:'లోడ్ అవుతోంది…',offline:'మీరు ఆఫ్‌లైన్‌లో ఉన్నారు',success:'పూర్తయింది',error:'ఏదో తప్పు జరిగింది',forYou:'మీ కోసం',following:'ఫాలో అవుతున్నవి',latest:'తాజా',share:'షేర్',like:'ఇష్టం',comment:'కామెంట్',savePost:'సేవ్',more:'మరిన్ని',close:'మూసివేయి',next:'తదుపరి',verify:'ధృవీకరించు',resend:'కోడ్ మళ్లీ పంపండి',verification:'ధృవీకరణ',verificationTitle:'ఇమెయిల్ ధృవీకరించండి',verificationBody:'మీకు పంపిన 6 అంకెల కోడ్‌ను నమోదు చేయండి.',codeExpired:'ఈ కోడ్ గడువు ముగిసింది.',invalidCode:'కోడ్ చెల్లదు.',checkInbox:'మీ ఇన్‌బాక్స్‌ను చూడండి',privacyChoice:'మీ ఎంపికలు మీవే.'}
};
export function t(locale:string,key:string,vars:Vars={}):string{let value=(packs[locale]??{})[key]??en[key]??key;for(const[k,v]of Object.entries(vars))value=value.replace(new RegExp(`\\{${k}\\}`,'g'),String(v));return value;}
export const translationKeys=Object.keys(en);
export function missingTranslationKeys(locale:string){if(locale==='en')return [];const pack=packs[locale]??{};return translationKeys.filter(k=>!pack[k]);}
