import { t as baseT } from './core';
import { fullLocalePacks } from './full-locale-packs';
import { authText } from './auth-ui';

type Vars=Record<string,string|number>;
type Dictionary=Record<string,string>;
const packs:Record<string,Dictionary>={
 gu:{welcome:'સ્વાગત છે',continue:'ચાલુ રાખો',back:'પાછા',create:'એકાઉન્ટ બનાવો',signIn:'સાઇન ઇન',name:'નામ',username:'યુઝરનેમ',email:'ઇમેલ',phone:'ફોન',password:'પાસવર્ડ',language:'ભાષા',chooseLanguage:'તમારી ભાષા પસંદ કરો',searchLanguages:'ભાષાઓ શોધો',applyLanguage:'આ ભાષાનો ઉપયોગ કરો',forgotPassword:'પાસવર્ડ ભૂલી ગયા?',home:'હોમ',explore:'એક્સપ્લોર',profile:'પ્રોફાઇલ',settings:'સેટિંગ્સ'},
 kn:{welcome:'ಸ್ವಾಗತ',continue:'ಮುಂದುವರಿಸಿ',back:'ಹಿಂದೆ',create:'ಖಾತೆ ರಚಿಸಿ',signIn:'ಸೈನ್ ಇನ್',name:'ಹೆಸರು',username:'ಬಳಕೆದಾರ ಹೆಸರು',email:'ಇಮೇಲ್',phone:'ಫೋನ್',password:'ಪಾಸ್‌ವರ್ಡ್',language:'ಭಾಷೆ',chooseLanguage:'ನಿಮ್ಮ ಭಾಷೆಯನ್ನು ಆಯ್ಕೆಮಾಡಿ',searchLanguages:'ಭಾಷೆಗಳನ್ನು ಹುಡುಕಿ',applyLanguage:'ಈ ಭಾಷೆಯನ್ನು ಬಳಸಿ',forgotPassword:'ಪಾಸ್‌ವರ್ಡ್ ಮರೆತಿರಾ?',home:'ಮುಖಪುಟ',explore:'ಎಕ್ಸ್‌ಪ್ಲೋರ್',profile:'ಪ್ರೊಫೈಲ್',settings:'ಸೆಟ್ಟಿಂಗ್‌ಗಳು'},
 ml:{welcome:'സ്വാഗതം',continue:'തുടരുക',back:'പിന്നിലേക്ക്',create:'അക്കൗണ്ട് സൃഷ്ടിക്കുക',signIn:'സൈൻ ഇൻ',name:'പേര്',username:'ഉപയോക്തൃനാമം',email:'ഇമെയിൽ',phone:'ഫോൺ',password:'പാസ്‌വേഡ്',language:'ഭാഷ',chooseLanguage:'നിങ്ങളുടെ ഭാഷ തിരഞ്ഞെടുക്കുക',searchLanguages:'ഭാഷകൾ തിരയുക',applyLanguage:'ഈ ഭാഷ ഉപയോഗിക്കുക',forgotPassword:'പാസ്‌വേഡ് മറന്നോ?',home:'ഹോം',explore:'എക്സ്പ്ലോർ',profile:'പ്രൊഫൈൽ',settings:'ക്രമീകരണങ്ങൾ'},
 pa:{welcome:'ਜੀ ਆਇਆਂ ਨੂੰ',continue:'ਜਾਰੀ ਰੱਖੋ',back:'ਵਾਪਸ',create:'ਖਾਤਾ ਬਣਾਓ',signIn:'ਸਾਈਨ ਇਨ',name:'ਨਾਮ',username:'ਯੂਜ਼ਰਨੇਮ',email:'ਈਮੇਲ',phone:'ਫ਼ੋਨ',password:'ਪਾਸਵਰਡ',language:'ਭਾਸ਼ਾ',chooseLanguage:'ਆਪਣੀ ਭਾਸ਼ਾ ਚੁਣੋ',searchLanguages:'ਭਾਸ਼ਾਵਾਂ ਖੋਜੋ',applyLanguage:'ਇਹ ਭਾਸ਼ਾ ਵਰਤੋ',forgotPassword:'ਪਾਸਵਰਡ ਭੁੱਲ ਗਏ?',home:'ਹੋਮ',explore:'ਐਕਸਪਲੋਰ',profile:'ਪ੍ਰੋਫ਼ਾਈਲ',settings:'ਸੈਟਿੰਗਾਂ'},
 ur:{welcome:'خوش آمدید',continue:'جاری رکھیں',back:'واپس',create:'اکاؤنٹ بنائیں',signIn:'سائن اِن',name:'نام',username:'صارف نام',email:'ای میل',phone:'فون',password:'پاس ورڈ',language:'زبان',chooseLanguage:'اپنی زبان منتخب کریں',searchLanguages:'زبانیں تلاش کریں',applyLanguage:'یہ زبان استعمال کریں',forgotPassword:'پاس ورڈ بھول گئے؟',home:'ہوم',explore:'دریافت',profile:'پروفائل',settings:'ترتیبات'},
 ar:{welcome:'مرحبًا',continue:'متابعة',back:'رجوع',create:'إنشاء حساب',signIn:'تسجيل الدخول',name:'الاسم',username:'اسم المستخدم',email:'البريد الإلكتروني',phone:'الهاتف',password:'كلمة المرور',language:'اللغة',chooseLanguage:'اختر لغتك',searchLanguages:'ابحث عن لغة',applyLanguage:'استخدم هذه اللغة',forgotPassword:'هل نسيت كلمة المرور؟',home:'الرئيسية',explore:'استكشاف',profile:'الملف الشخصي',settings:'الإعدادات'},
 fr:{welcome:'Bienvenue',continue:'Continuer',back:'Retour',create:'Créer un compte',signIn:'Se connecter',name:'Nom',username:"Nom d’utilisateur",email:'E-mail',phone:'Téléphone',password:'Mot de passe',language:'Langue',chooseLanguage:'Choisissez votre langue',searchLanguages:'Rechercher une langue',applyLanguage:'Utiliser cette langue',forgotPassword:'Mot de passe oublié ?',home:'Accueil',explore:'Explorer',profile:'Profil',settings:'Réglages'},
 de:{welcome:'Willkommen',continue:'Weiter',back:'Zurück',create:'Konto erstellen',signIn:'Anmelden',name:'Name',username:'Benutzername',email:'E-Mail',phone:'Telefon',password:'Passwort',language:'Sprache',chooseLanguage:'Sprache auswählen',searchLanguages:'Sprachen suchen',applyLanguage:'Diese Sprache verwenden',forgotPassword:'Passwort vergessen?',home:'Start',explore:'Entdecken',profile:'Profil',settings:'Einstellungen'},
 es:{welcome:'Bienvenido',continue:'Continuar',back:'Atrás',create:'Crear cuenta',signIn:'Iniciar sesión',name:'Nombre',username:'Nombre de usuario',email:'Correo',phone:'Teléfono',password:'Contraseña',language:'Idioma',chooseLanguage:'Elige tu idioma',searchLanguages:'Buscar idiomas',applyLanguage:'Usar esta idioma',forgotPassword:'¿Olvidaste tu contraseña?',home:'Inicio',explore:'Explorar',profile:'Perfil',settings:'Ajustes'},
 ja:{welcome:'ようこそ',continue:'続ける',back:'戻る',create:'アカウントを作成',signIn:'ログイン',name:'名前',username:'ユーザーネーム',email:'メール',phone:'電話番号',password:'パスワード',language:'言語',chooseLanguage:'言語を選択',searchLanguages:'言語を検索',applyLanguage:'この言語を使用',forgotPassword:'パスワードを忘れましたか？',home:'ホーム',explore:'検索',profile:'プロフィール',settings:'設定'},
 ko:{welcome:'환영합니다',continue:'계속',back:'뒤로',create:'계정 만들기',signIn:'로그인',name:'이름',username:'사용자 이름',email:'이메일',phone:'전화번호',password:'비밀번호',language:'언어',chooseLanguage:'언어를 선택하세요',searchLanguages:'언어 검색',applyLanguage:'이 언어 사용',forgotPassword:'비밀번호를 잊으셨나요?',home:'홈',explore:'탐색',profile:'프로필',settings:'설정'},
 zh:{welcome:'欢迎',continue:'继续',back:'返回',create:'创建账户',signIn:'登录',name:'姓名',username:'用户名',email:'邮箱',phone:'手机号',password:'密码',language:'语言',chooseLanguage:'选择你的语言',searchLanguages:'搜索语言',applyLanguage:'使用此语言',forgotPassword:'忘记密码？',home:'首页',explore:'探索',profile:'个人资料',settings:'设置'},
 'zh-TW':{welcome:'歡迎',continue:'繼續',back:'返回',create:'建立帳戶',signIn:'登入',name:'姓名',username:'使用者名稱',email:'電子郵件',phone:'電話',password:'密碼',language:'語言',chooseLanguage:'選擇你的語言',searchLanguages:'搜尋語言',applyLanguage:'使用此語言',forgotPassword:'忘記密碼？',home:'首頁',explore:'探索',profile:'個人資料',settings:'設定'}
};
const AUTH_KEYS=new Set(['resetPassword','forgotPassword','newTo','already','backToSignIn','namePlaceholder','usernamePlaceholder','emailPlaceholder','phonePlaceholder','passwordPlaceholder','accountPlaceholder','weak','good','strong','password12','passwordUpper','passwordLower','passwordNumber','passwordSpecial','codeSentPhone','verifyPhone','verifyRecovery','verifiedContact','expiresIn','resendIn','otpNeverShare','enterName','invalidUsername','enterEmail','invalidEmail','invalidPhone','passwordMin','enterAccount','recoverySent','accountAndPassword','identifierInUse','invalidCredentials','rateLimited','step','of','showPassword','hidePassword','network','emailDeliveryUnavailable','checkInbox','verification','verificationTitle','verificationBody','verify','done','codeExpired','invalidCode','loading']);
export function localizedT(locale:string,key:string,vars?:Vars){
 const value=packs[locale]?.[key]??fullLocalePacks[locale]?.[key];
 const resolved=value??(AUTH_KEYS.has(key)?authText(locale,key as Parameters<typeof authText>[1]):undefined)??baseT(locale,key,vars);
 return resolved.replace(/\{(\w+)\}/g,(_,name)=>String(vars?.[name]??`{${name}}`));
}
