type Dictionary=Record<string,string>;
const p=(continueText:string,back:string,create:string,signIn:string,name:string,username:string,email:string,phone:string,password:string,language:string,choose:string,search:string,forgot:string,verify:string,resend:string,verification:string,verificationTitle:string,verificationBody:string,expired:string,invalid:string):Dictionary=>({continue:continueText,back,done:create,create,signIn,name,username,email,phone,password,language,chooseLanguage:choose,searchLanguages:search,applyLanguage:choose,forgotPassword:forgot,verify,resend,verification,verificationTitle,verificationBody,codeExpired:expired,invalidCode:invalid});
export const fullLocalePacks:Record<string,Dictionary>={
 as:p('আগবাঢ়ক','উভতি যাওক','একাউণ্ট বনাওক','ছাইন ইন','নাম','ব্যৱহাৰকাৰীৰ নাম','ইমেইল','ফোন','পাছৱৰ্ড','ভাষা','আপোনাৰ ভাষা বাছনি কৰক','ভাষা বিচাৰক','পাছৱৰ্ড পাহৰিলে?', 'যাচাই কৰক','কোড পুনৰ পঠাওক','যাচাইকৰণ','আপোনাৰ ইমেইল যাচাই কৰক','পঠিওৱা ৬ সংখ্যাৰ কোডটো দিয়ক।','কোডৰ ম্যাদ শেষ হৈছে।','কোডটো সঠিক নহয়।'),
 or:p('ଜାରି ରଖନ୍ତୁ','ପଛକୁ','ଖାତା ତିଆରି କରନ୍ତୁ','ସାଇନ ଇନ','ନାମ','ବ୍ୟବହାରକାରୀ ନାମ','ଇମେଲ','ଫୋନ','ପାସୱାର୍ଡ','ଭାଷା','ଆପଣଙ୍କ ଭାଷା ବାଛନ୍ତୁ','ଭାଷା ଖୋଜନ୍ତୁ','ପାସୱାର୍ଡ ଭୁଲିଗଲେ?','ଯାଞ୍ଚ କରନ୍ତୁ','କୋଡ୍ ପୁଣି ପଠାନ୍ତୁ','ଯାଞ୍ଚ','ଇମେଲ ଯାଞ୍ଚ କରନ୍ତୁ','ପଠାଯାଇଥିବା ୬ ଅଙ୍କର କୋଡ୍ ଦିଅନ୍ତୁ।','କୋଡ୍ର ମିଆଦ ଶେଷ।','କୋଡ୍ ସଠିକ୍ ନୁହେଁ।'),
 ne:p('जारी राख्नुहोस्','पछाडि','खाता बनाउनुहोस्','साइन इन','नाम','प्रयोगकर्ता नाम','इमेल','फोन','पासवर्ड','भाषा','आफ्नो भाषा छान्नुहोस्','भाषा खोज्नुहोस्','पासवर्ड बिर्सनुभयो?','प्रमाणित गर्नुहोस्','कोड फेरि पठाउनुहोस्','प्रमाणीकरण','इमेल प्रमाणित गर्नुहोस्','तपाईंलाई पठाइएको ६ अङ्कको कोड हाल्नुहोस्।','कोडको म्याद सकियो।','कोड मान्य छैन।'),
 sa:p('अनुवर्तयतु','प्रतिनिवर्तताम्','खातं निर्मीयताम्','प्रविशन्तु','नाम','उपयोक्तृनाम','ईमेल','दूरवाणी','कूटशब्दः','भाषा','स्वस्य भाषां चिनुत','भाषां अन्विष्यताम्','कूटशब्दं विस्मृतवान्?','सत्यापयतु','संकेतं पुनः प्रेषयतु','सत्यापनम्','ईमेल सत्यापयतु','प्रेषितं षडङ्कीयं संकेतं लिखतु।','संकेतस्य कालः समाप्तः।','संकेतः मान्यः नास्ति।'),
 kok:p('चालू दवरचो','फाटीं वच','खातें तयार करचें','साइन इन','नांव','वापरप्याचें नांव','ईमेल','फोन','पासवर्ड','भास','तुमची भास निवडात','भासा सोदात','पासवर्ड विसरलात?','तपासात','कोड परत धाडात','तपासणी','ईमेल तपासात','धाडिल्लो ६ अंकांचो कोड घालात।','कोडाची मुदत गेली।','कोड योग्य ना।'),
 mai:p('जारी राखू','पाछू','खाता बनाबू','साइन इन','नाम','प्रयोगकर्ता नाम','ईमेल','फोन','पासवर्ड','भाषा','अपन भाषा चुनू','भाषा खोजू','पासवर्ड बिसरलहुँ?','सत्यापित करू','कोड फेर भेजू','सत्यापन','ईमेल सत्यापित करू','भेजल ६ अंकक कोड लिखू।','कोडक म्याद समाप्त।','कोड सही नहि अछि।'),
 bho:p('जारी राखीं','पीछे','खाता बनाईं','साइन इन','नाँव','यूजरनेम','ईमेल','फोन','पासवर्ड','भाषा','अपन भाषा चुनीं','भाषा खोजीं','पासवर्ड भूल गइल बानी?','सत्यापित करीं','कोड फेरु भेजीं','सत्यापन','ईमेल सत्यापित करीं','भेजल ६ अंक के कोड डालीं।','कोड के मियाद खतम हो गइल।','कोड सही नइखे।'),
 doi:p('जारी रखो','पिच्छे','खाता बनाओ','साइन इन','नांऽ','बरतून्न नांऽ','ईमेल','फोन','पासवर्ड','भाशा','अपनी भाशा चुनो','भाशां खोजो','पासवर्ड भुली गे?','जांच करो','कोड परत भेजो','जांच','ईमेल जांचो','तुंदे गी भेजे ६ अंकें दा कोड पाओ।','कोड दी मियाद खत्म।','कोड सही नेईं।'),
 sat:p('ᱪᱟᱞᱟ ᱞᱟᱜᱟᱣ','ᱛᱟᱭᱚᱢ','ᱮᱠᱟᱣᱩᱱᱴ ᱵᱟᱹᱱᱟᱣ','ᱥᱟᱭᱤᱱ ᱤᱱ','ᱧᱩᱛᱩᱢ','ᱵᱟᱹᱛᱩᱞ ᱧᱩᱛᱩᱢ','ᱤᱢᱮᱞ','ᱯᱷᱳᱱ','ᱯᱟᱥᱣᱟᱨᱰ','ᱯᱟᱹᱦᱟ','ᱟᱢᱟᱜ ᱯᱟᱹᱦᱟ ᱵᱟᱪᱷᱟᱣ','ᱯᱟᱹᱦᱟ ᱥᱮᱸᱪᱟᱣ','ᱯᱟᱥᱣᱟᱨᱰ ᱵᱷᱩᱞᱟᱹᱣ ᱮᱱᱟ?','ᱥᱟᱹᱵᱩᱫ ᱢᱮ','ᱠᱳᱰ ᱫᱚᱦᱲᱟ ᱥᱮᱫᱟᱣ','ᱥᱟᱹᱵᱩᱫ','ᱤᱢᱮᱞ ᱥᱟᱹᱵᱩᱫ ᱢᱮ','ᱞᱟᱦᱟ ᱠᱚᱰ ᱮᱢ ᱢᱮ','ᱠᱳᱰ ᱫᱚ ᱟᱹᱨᱚᱥ ᱯᱟᱨᱟᱢ','ᱠᱳᱰ ᱵᱚᱞᱚ ᱱᱟᱛᱮᱞᱟ ᱵᱟᱝ।'),
 mni:p('ꯃꯇꯧ ꯆꯠꯊꯣ','ꯃꯇꯥꯡ','ꯈꯥꯇꯥ ꯁꯦꯝꯒꯠꯂꯨ','ꯁꯥꯏꯟ ꯏꯟ','ꯃꯃꯤ','ꯌꯨꯖꯔꯅꯦꯝ','ꯏꯃꯦꯜ','ꯐꯣꯟ','ꯄꯥꯁꯋꯥꯔꯠ','ꯂꯣꯜ','ꯅꯪꯒꯤ ꯂꯣꯜ ꯈꯟꯕꯤꯌꯨ','ꯂꯣꯜ ꯈꯪꯖꯤꯟꯕ','ꯄꯥꯁꯋꯥꯔꯠ ꯈꯪꯗꯦ?','ꯌꯦꯡꯁꯤꯜꯂꯨ','ꯀꯣꯠ ꯑꯃꯨꯛ ꯊꯥꯗꯣꯛꯎ','ꯌꯦꯡꯕ','ꯏꯃꯦꯜ ꯌꯦꯡꯁꯤꯜꯂꯨ','ꯅꯪꯗꯒꯤ ꯂꯥꯛꯄ ꯶ ꯑꯃꯁꯨꯡ ꯄꯥꯟꯒꯜ ꯂꯥꯛꯀ ꯊꯣꯛꯄ','ꯀꯣꯠ ꯑꯁꯤ ꯌꯥꯝ ꯅꯣꯡ','ꯀꯣꯠ ꯑꯁꯤ ꯑꯁꯤꯒꯤ ꯐꯔꯥꯛ ꯅꯠꯇꯦ'),

 ur:p('جاری رکھیں','واپس','اکاؤنٹ بنائیں','سائن اِن','نام','صارف نام','ای میل','فون','پاس ورڈ','زبان','اپنی زبان منتخب کریں','زبانیں تلاش کریں','پاس ورڈ بھول گئے؟','تصدیق کریں','کوڈ دوبارہ بھیجیں','تصدیق','ای میل کی تصدیق کریں','آپ کو بھیجا گیا ۶ ہندسوں کا کوڈ درج کریں۔','کوڈ کی میعاد ختم ہو گئی۔','کوڈ درست نہیں ہے۔'),
 ks:p('جاری تھؤ','واپس','کھٲتہٕ بنٲو','ساین اِن','ناو','یوزرنیم','ای میل','فون','پاسورڈ','زبان','پَنُن زبان ژٕرِو','زبانہٕ تلاو','پاسورڈ ہیُو وسار؟','توثیق کٔرِو','کوڈ دوبارہ پٮ۪وِو','توثیق','ای میل توثیق کٔرِو','تۅہہِ پٮ۪ٹھ پٮ۪ٹھاون ۶ ہندسٕ کوڈ دٔیِو۔','کوڈس ختم۔','کوڈ چھُ صحیح نَہ۔'),
 sd:p('جاري رکو','واپس','کاتو ٺاهيو','سائن اِن','نالو','يوزرنيم','اي ميل','فون','پاسورڊ','ٻولي','پنهنجي ٻولي چونڊيو','ٻوليون ڳوليو','پاسورڊ وسري ويو؟','تصديق ڪريو','ڪوڊ ٻيهر موڪليو','تصديق','اي ميل جي تصديق ڪريو','موڪليل ۶ انگن وارو ڪوڊ داخل ڪريو۔','ڪوڊ ختم ٿي ويو۔','ڪوڊ صحيح ناهي۔'),

 fa:p('ادامه','بازگشت','ایجاد حساب','ورود','نام','نام کاربری','ایمیل','تلفن','رمز عبور','زبان','زبان خود را انتخاب کنید','جستجوی زبان‌ها','رمز عبور را فراموش کردید؟','تأیید','ارسال دوباره کد','تأیید','تأیید ایمیل','کد ۶ رقمی ارسال‌شده را وارد کنید.','این کد منقضی شده است.','کد معتبر نیست.'),
 tr:p('Devam et','Geri','Hesap oluştur','Giriş yap','Ad','Kullanıcı adı','E-posta','Telefon','Şifre','Dil','Dilinizi seçin','Dil ara','Şifrenizi mi unuttunuz?','Doğrula','Kodu yeniden gönder','Doğrulama','E-postanızı doğrulayın','Size gönderdiğimiz 6 haneli kodu girin.','Bu kodun süresi doldu.','Kod geçerli değil.'),
 pt:p('Continuar','Voltar','Criar conta','Entrar','Nome','Nome de utilizador','E-mail','Telefone','Palavra-passe','Idioma','Escolha o seu idioma','Pesquisar idiomas','Esqueceu a palavra-passe?','Verificar','Reenviar código','Verificação','Verifique o seu e-mail','Introduza o código de 6 dígitos que enviámos.','Este código expirou.','O código não é válido.'),
 it:p('Continua','Indietro','Crea account','Accedi','Nome','Nome utente','Email','Telefono','Password','Lingua','Scegli la lingua','Cerca lingue','Hai dimenticato la password?','Verifica','Invia di nuovo il codice','Verifica','Verifica la tua email','Inserisci il codice di 6 cifre che ti abbiamo inviato.','Questo codice è scaduto.','Il codice non è valido.'),
 ru:p('Продолжить','Назад','Создать аккаунт','Войти','Имя','Имя пользователя','Эл. почта','Телефон','Пароль','Язык','Выберите язык','Поиск языков','Забыли пароль?','Подтвердить','Отправить код ещё раз','Подтверждение','Подтвердите эл. почту','Введите 6-значный код, который мы отправили.','Срок действия кода истёк.','Код недействителен.'),
 uk:p('Продовжити','Назад','Створити обліковий запис','Увійти','Ім’я','Ім’я користувача','Електронна пошта','Телефон','Пароль','Мова','Оберіть мову','Пошук мов','Забули пароль?','Підтвердити','Надіслати код ще раз','Підтвердження','Підтвердьте електронну пошту','Введіть 6-значний код, який ми надіслали.','Термін дії коду минув.','Код недійсний.'),
 pl:p('Kontynuuj','Wstecz','Utwórz konto','Zaloguj się','Imię','Nazwa użytkownika','E-mail','Telefon','Hasło','Język','Wybierz język','Szukaj języków','Nie pamiętasz hasła?','Zweryfikuj','Wyślij kod ponownie','Weryfikacja','Zweryfikuj e-mail','Wpisz 6-cyfrowy kod, który wysłaliśmy.','Kod wygasł.','Kod jest nieprawidłowy.'),
 nl:p('Doorgaan','Terug','Account maken','Inloggen','Naam','Gebruikersnaam','E-mail','Telefoon','Wachtwoord','Taal','Kies je taal','Talen zoeken','Wachtwoord vergeten?','Verifiëren','Code opnieuw verzenden','Verificatie','Verifieer je e-mail','Voer de 6-cijferige code in die we stuurden.','Deze code is verlopen.','Deze code is ongeldig.'),
 sv:p('Fortsätt','Tillbaka','Skapa konto','Logga in','Namn','Användarnamn','E-post','Telefon','Lösenord','Språk','Välj språk','Sök språk','Glömt lösenordet?','Verifiera','Skicka koden igen','Verifiering','Verifiera din e-post','Ange den 6-siffriga koden vi skickade.','Koden har gått ut.','Koden är inte giltig.'),
 th:p('ดำเนินการต่อ','ย้อนกลับ','สร้างบัญชี','เข้าสู่ระบบ','ชื่อ','ชื่อผู้ใช้','อีเมล','โทรศัพท์','รหัสผ่าน','ภาษา','เลือกภาษาของคุณ','ค้นหาภาษา','ลืมรหัสผ่าน?','ยืนยัน','ส่งรหัสอีกครั้ง','การยืนยัน','ยืนยันอีเมลของคุณ','ป้อนรหัส 6 หลักที่เราส่งให้คุณ','รหัสนี้หมดอายุแล้ว','รหัสนี้ไม่ถูกต้อง'),
 vi:p('Tiếp tục','Quay lại','Tạo tài khoản','Đăng nhập','Tên','Tên người dùng','Email','Điện thoại','Mật khẩu','Ngôn ngữ','Chọn ngôn ngữ','Tìm ngôn ngữ','Quên mật khẩu?','Xác minh','Gửi lại mã','Xác minh','Xác minh email','Nhập mã 6 chữ số chúng tôi đã gửi.','Mã đã hết hạn.','Mã không hợp lệ.'),
 id:p('Lanjut','Kembali','Buat akun','Masuk','Nama','Nama pengguna','Email','Telepon','Kata sandi','Bahasa','Pilih bahasa Anda','Cari bahasa','Lupa kata sandi?','Verifikasi','Kirim ulang kode','Verifikasi','Verifikasi email Anda','Masukkan kode 6 digit yang kami kirim.','Kode ini telah kedaluwarsa.','Kode tidak valid.'),
 ms:p('Teruskan','Kembali','Cipta akaun','Log masuk','Nama','Nama pengguna','E-mel','Telefon','Kata laluan','Bahasa','Pilih bahasa anda','Cari bahasa','Lupa kata laluan?','Sahkan','Hantar semula kod','Pengesahan','Sahkan e-mel anda','Masukkan kod 6 digit yang kami hantar.','Kod ini telah tamat tempoh.','Kod tidak sah.'),
 fil:p('Magpatuloy','Bumalik','Gumawa ng account','Mag-sign in','Pangalan','Username','Email','Telepono','Password','Wika','Piliin ang iyong wika','Maghanap ng mga wika','Nakalimutan ang password?','I-verify','Ipadala muli ang code','Pag-verify','I-verify ang iyong email','Ilagay ang 6-digit na code na ipinadala namin.','Nag-expire na ang code.','Hindi wasto ang code.'),
 sw:p('Endelea','Rudi','Unda akaunti','Ingia','Jina','Jina la mtumiaji','Barua pepe','Simu','Nenosiri','Lugha','Chagua lugha yako','Tafuta lugha','Umesahau nenosiri?','Thibitisha','Tuma tena msimbo','Uthibitishaji','Thibitisha barua pepe yako','Weka msimbo wa tarakimu 6 tuliokutumia.','Msimbo umeisha muda.','Msimbo si sahihi.'),
 he:p('המשך','חזרה','צור חשבון','התחברות','שם','שם משתמש','אימייל','טלפון','סיסמה','שפה','בחרו את השפה שלכם','חיפוש שפות','שכחתם סיסמה?','אימות','שלחו קוד מחדש','אימות','אמתו את האימייל','הזינו את הקוד בן 6 הספרות ששלחנו.','הקוד פג תוקף.','הקוד אינו תקין.')
};
