import { useMemo, useState, type ReactNode } from 'react';
import { ActivityIndicator, FlatList, Pressable, StyleSheet, Text, TextInput, View } from 'react-native';
import { colors, elevation, radius, spacing, type } from '../ui/theme';
import { Icon } from '../ui/icons';
import { locales, type Locale } from './core';
import { useI18n } from './provider';

export function InitialLanguageGate({children}:{children:ReactNode}){
 const {ready,needsChoice,setLocale,t}=useI18n();
 const [query,setQuery]=useState(''); const [saving,setSaving]=useState(false);
 const filtered=useMemo(()=>{const q=query.trim().toLowerCase();return q?locales.filter(x=>`${x.nativeName} ${x.englishName}`.toLowerCase().includes(q)):locales;},[query]);
 if(!ready)return <View style={s.loading}><ActivityIndicator color={colors.brand}/></View>;
 if(!needsChoice)return <>{children}</>;
 const choose=async(item:Locale)=>{setSaving(true);try{await setLocale(item.code);}finally{setSaving(false);}};
 return <View style={s.screen}><View style={s.hero}><View style={s.mark}><View style={s.ring}/><View style={s.nodeA}/><View style={s.nodeB}/><View style={s.nodeC}/><View style={s.bridgeA}/><View style={s.bridgeB}/><View style={s.orbit}/></View><Text style={s.word}>drustpoll</Text><Text style={s.kicker}>BEGIN WITH YOUR LANGUAGE</Text><Text style={s.title}>Choose the language in which your world should feel natural.</Text><Text style={s.body}>This choice follows you across the entire product. You can change it later in Settings.</Text></View><TextInput value={query} onChangeText={setQuery} placeholder="Search languages" placeholderTextColor={colors.faint} style={s.search}/><FlatList data={filtered} keyExtractor={x=>x.code} contentContainerStyle={s.list} renderItem={({item})=><Pressable accessibilityRole="button" accessibilityLabel={`${item.nativeName}, ${item.englishName}`} onPress={()=>void choose(item)} disabled={saving} style={({pressed})=>[s.row,pressed&&s.pressed]}><View style={s.names}><Text style={s.native}>{item.nativeName}</Text><Text style={s.english}>{item.englishName}{item.direction==='rtl'?' · RTL':''}</Text></View>{saving?<ActivityIndicator size="small"/>:<Icon name="chevronRight" size={18} color={colors.brand}/>}</Pressable>}/></View>;
}
const s=StyleSheet.create({loading:{flex:1,alignItems:'center',justifyContent:'center',backgroundColor:colors.canvas},screen:{flex:1,backgroundColor:colors.canvas,paddingHorizontal:spacing.xl,paddingTop:spacing.huge},hero:{maxWidth:720,width:'100%',alignSelf:'center'},mark:{width:72,height:72,borderRadius:24,backgroundColor:colors.brand,position:'relative',alignItems:'center',justifyContent:'center',...elevation.medium},ring:{position:'absolute',width:50,height:50,borderRadius:25,borderWidth:1.5,borderColor:'rgba(255,255,255,.32)'},nodeA:{position:'absolute',width:8,height:8,borderRadius:4,backgroundColor:colors.white,left:17,top:18},nodeB:{position:'absolute',width:8,height:8,borderRadius:4,backgroundColor:colors.white,right:16,top:14},nodeC:{position:'absolute',width:8,height:8,borderRadius:4,backgroundColor:colors.white,left:31,bottom:15},bridgeA:{position:'absolute',height:1.5,width:21,backgroundColor:colors.white,left:25,top:21,transform:[{rotate:'-12deg'}]},bridgeB:{position:'absolute',height:1.5,width:19,backgroundColor:colors.white,left:27,top:35,transform:[{rotate:'51deg'}]},orbit:{position:'absolute',width:43,height:16,borderRadius:12,borderWidth:1.5,borderColor:colors.social,left:15,top:28,transform:[{rotate:'20deg'}],opacity:.8},word:{fontSize:20,fontWeight:'900',letterSpacing:-.5,color:colors.ink,marginTop:12},kicker:{fontSize:type.labelSM,fontWeight:'900',letterSpacing:1.8,color:colors.brand,marginTop:spacing.xl},title:{fontSize:type.displayLG,lineHeight:38,fontWeight:'900',letterSpacing:-1,color:colors.ink,marginTop:6},body:{fontSize:type.bodyMD,lineHeight:22,color:colors.muted,marginTop:10,maxWidth:620},search:{height:52,borderBottomWidth:1,borderBottomColor:colors.line,color:colors.ink,fontSize:16,marginTop:spacing.xl,maxWidth:720,width:'100%',alignSelf:'center'},list:{paddingVertical:spacing.md,paddingBottom:spacing.huge,maxWidth:720,width:'100%',alignSelf:'center',gap:4},row:{minHeight:64,paddingHorizontal:16,borderRadius:radius.md,flexDirection:'row',alignItems:'center',justifyContent:'space-between',backgroundColor:colors.surface,borderWidth:1,borderColor:colors.line},names:{flex:1},native:{fontSize:16,fontWeight:'800',color:colors.ink},english:{fontSize:12,color:colors.muted,marginTop:2},pressed:{opacity:.7}});