import {ReactNode} from 'react';
import {Link,usePathname} from 'expo-router';
import {Pressable,StyleSheet,Text,View} from 'react-native';
import {SafeAreaView} from 'react-native-safe-area-context';
import {colors,elevation,radius,spacing,type} from './theme';
import {useResponsiveLayout} from './responsive';
import {Icon,type IconName} from './icons';
const items:Array<{href:string;icon:IconName;label:string;hint:string}>= [{href:'/',icon:'home',label:'Home',hint:'Your social context'},{href:'/search',icon:'search',label:'Explore',hint:'Find people, ideas and products'},{href:'/create',icon:'create',label:'Create',hint:'Create and express'},{href:'/messages',icon:'connect',label:'Connect',hint:'Messages and conversations'},{href:'/profile',icon:'profile',label:'You',hint:'Profile and controls'}];
export function AppShell({children}:{children:ReactNode}){const pathname=usePathname();const{isDesktop}=useResponsiveLayout();const activeFor=(href:string)=>pathname===href||(href!=='/'&&pathname.startsWith(`${href}/`));
if(isDesktop)return <SafeAreaView style={s.safe} edges={['top','left','right','bottom']}><View style={s.desktopBody}><View style={s.rail} accessible accessibilityLabel="Primary navigation"><View style={s.brandOrb}><View style={s.orbDotA}/><View style={s.orbDotB}/><View style={s.orbDotC}/></View><Text style={s.brandWord}>drustpoll</Text><View style={s.railItems}>{items.map(item=>{const active=activeFor(item.href);return <Link key={item.href} href={item.href} asChild><Pressable accessibilityRole="link" accessibilityLabel={`${item.label}: ${item.hint}`} accessibilityState={{selected:active}} style={({pressed})=>[s.railItem,active&&s.railActive,pressed&&s.pressed]}><View style={[s.railIcon,active&&s.iconActive]}><Icon name={item.icon} size={21} color={active?colors.brand:colors.muted}/></View><Text style={[s.railLabel,active&&s.labelActive]}>{item.label}</Text></Pressable></Link>})}</View><View style={s.railFoot}><View style={s.footSpark}><Icon name="star" size={13} color={colors.social}/></View><Text style={s.railFootText}>living canvas</Text></View></View><View style={s.desktopContent}>{children}</View></View></SafeAreaView>;
return <SafeAreaView style={s.safe} edges={['top','left','right','bottom']}><View style={s.body}>{children}</View><View style={s.dock} accessibilityRole="tablist" accessibilityLabel="Primary navigation"><View style={s.dockInner}>{items.map((item,i)=>{const active=activeFor(item.href);const center=i===2;return <Link key={item.href} href={item.href} asChild><Pressable accessibilityRole="tab" accessibilityLabel={`${item.label}: ${item.hint}`} accessibilityState={{selected:active}} style={({pressed})=>[s.dockItem,center&&s.createDockItem,active&&center&&s.createActive,pressed&&s.pressed]}><View style={[s.dockIcon,active&&s.iconActive,center&&s.createIcon]}><Icon name={item.icon} size={center?22:20} color={center?'#FFFFFF':active?colors.brand:colors.muted}/></View><Text style={[s.label,active&&s.labelActive,center&&s.createLabel]}>{item.label}</Text></Pressable></Link>})}</View></View></SafeAreaView>;}
const s=StyleSheet.create({safe:{flex:1,backgroundColor:colors.canvas},body:{flex:1,paddingBottom:88},desktopBody:{flex:1,flexDirection:'row'},desktopContent:{flex:1,minWidth:0},rail:{width:138,padding:spacing.md,backgroundColor:colors.surface,borderRightWidth:1,borderRightColor:colors.line,alignItems:'center',gap:spacing.sm},brandOrb:{width:52,height:52,borderRadius:18,backgroundColor:colors.brand,position:'relative',marginTop:4,...elevation.low},orbDotA:{position:'absolute',width:7,height:7,borderRadius:4,backgroundColor:colors.white,left:14,top:17},orbDotB:{position:'absolute',width:7,height:7,borderRadius:4,backgroundColor:colors.white,right:13,top:13},orbDotC:{position:'absolute',width:7,height:7,borderRadius:4,backgroundColor:colors.white,left:23,bottom:13},brandWord:{fontSize:type.labelLG,fontWeight:'900',letterSpacing:-.2,color:colors.ink,marginTop:-2},railItems:{width:'100%',gap:4,marginTop:spacing.md},railItem:{minHeight:70,borderRadius:radius.lg,paddingHorizontal:8,alignItems:'center',justifyContent:'center',gap:4},railActive:{backgroundColor:colors.brandSoft},railIcon:{width:48,height:32,borderRadius:radius.pill,alignItems:'center',justifyContent:'center'},iconActive:{backgroundColor:colors.surface},railLabel:{fontSize:type.labelSM,color:colors.faint,fontWeight:'700'},label:{fontSize:type.labelSM,color:colors.muted,fontWeight:'700'},labelActive:{color:colors.ink,fontWeight:'900'},railFoot:{marginTop:'auto',paddingVertical:10,alignItems:'center',gap:3},footSpark:{width:30,height:30,borderRadius:15,backgroundColor:colors.brandSoft,alignItems:'center',justifyContent:'center'},railFootText:{fontSize:9,fontWeight:'900',letterSpacing:1.2,textTransform:'uppercase',color:colors.faint},pressed:{opacity:.72},dock:{position:'absolute',left:12,right:12,bottom:10,alignItems:'center'},dockInner:{height:76,backgroundColor:colors.surface,borderWidth:1,borderColor:colors.line,borderRadius:28,paddingHorizontal:6,flexDirection:'row',alignItems:'center',...elevation.medium},dockItem:{flex:1,minHeight:64,borderRadius:22,alignItems:'center',justifyContent:'center',gap:2},dockIcon:{width:46,height:34,borderRadius:17,alignItems:'center',justifyContent:'center'},createDockItem:{flexGrow:1.12,transform:[{translateY:-8}]},createIcon:{width:54,height:54,borderRadius:27,backgroundColor:colors.brand,borderWidth:4,borderColor:colors.surface,...elevation.medium},createActive:{transform:[{translateY:-10}]},createLabel:{fontWeight:'900',color:colors.brand,marginTop:-4}});