import {ReactNode} from 'react';
import {Link,usePathname} from 'expo-router';
import {Pressable,StyleSheet,Text,View} from 'react-native';
import {SafeAreaView} from 'react-native-safe-area-context';
import {colors,radius,spacing,type,elevation} from './theme';
import {useResponsiveLayout} from './responsive';
import {Icon,type IconName} from './icons';
import {useI18n} from '../src/i18n/provider';
const items:Array<{href:string;icon:IconName;key:'home'|'explore'|'createNav'|'connect'|'you';hint:string}>= [{href:'/',icon:'home',key:'home',hint:'Your social context'},{href:'/search',icon:'search',key:'explore',hint:'Find people, ideas and products'},{href:'/create',icon:'create',key:'createNav',hint:'Create and express'},{href:'/messages',icon:'connect',key:'connect',hint:'Messages and conversations'},{href:'/profile',icon:'profile',key:'you',hint:'Profile and controls'}];
export function AppShell({children}:{children:ReactNode}){const pathname=usePathname();const{isDesktop}=useResponsiveLayout();const{t}=useI18n();const activeFor=(href:string)=>pathname===href||(href!=='/'&&pathname.startsWith(`${href}/`));
if(isDesktop)return <SafeAreaView style={s.safe} edges={['top','left','right','bottom']}><View style={s.desktopBody}><View style={s.rail} accessible accessibilityLabel="Drustpoll navigation"><View style={s.brandLockup}><View style={s.brandOrb}><View style={s.orbCut}/></View><View><Text style={s.brandWord}>drustpoll</Text><Text style={s.brandSub}>LIVING CANVAS</Text></View></View><View style={s.railItems}>{items.map(item=>{const active=activeFor(item.href);const label=t(item.key);return <Link key={item.href} href={item.href} asChild><Pressable accessibilityRole="link" accessibilityLabel={`${label}: ${item.hint}`} accessibilityState={{selected:active}} style={({pressed})=>[s.railItem,active&&s.railActive,pressed&&s.pressed]}><View style={[s.railIcon,active&&s.railIconActive]}><Icon name={item.icon} size={20} color={active?colors.brand:colors.muted}/></View><View style={s.railLabelWrap}><Text style={[s.railLabel,active&&s.labelActive]}>{label}</Text><View style={[s.railMark,active&&s.railMarkActive]}/></View></Pressable></Link>})}</View><View style={s.railFoot}><View style={s.footRule}/><Text style={s.railFootText}>quiet · clear · human</Text></View></View><View style={s.desktopContent}>{children}</View></View></SafeAreaView>;
return <SafeAreaView style={s.safe} edges={['top','left','right','bottom']}><View style={s.body}>{children}</View><View style={s.dock} accessibilityRole="tablist" accessibilityLabel="Drustpoll primary navigation"><View style={s.dockInner}>{items.map((item,i)=>{const active=activeFor(item.href);const center=i===2;const label=t(item.key);return <Link key={item.href} href={item.href} asChild><Pressable accessibilityRole="tab" accessibilityLabel={`${label}: ${item.hint}`} accessibilityState={{selected:active}} style={({pressed})=>[s.dockItem,center&&s.createDockItem,pressed&&s.pressed]}><View style={[s.dockIcon,active&&s.iconActive,center&&s.createIcon,center&&active&&s.createIconActive]}>{center?<View style={s.createGlyph}><Icon name="create" size={21} color={colors.white}/></View>:<Icon name={item.icon} size={20} color={active?colors.brand:colors.muted}/>}</View><Text style={[s.label,active&&s.labelActive,center&&s.createLabel]}>{label}</Text></Pressable></Link>})}</View></View></SafeAreaView>;}
const s=StyleSheet.create({safe:{flex:1,backgroundColor:colors.canvas},body:{flex:1,paddingBottom:90},desktopBody:{flex:1,flexDirection:'row'},desktopContent:{flex:1,minWidth:0},rail:{width:158,paddingHorizontal:14,paddingTop:16,paddingBottom:12,backgroundColor:colors.canvas,borderRightWidth:1,borderRightColor:colors.line},brandLockup:{flexDirection:'row',alignItems:'center',gap:10,paddingHorizontal:4},brandOrb:{width:40,height:40,borderRadius:13,backgroundColor:colors.brand,alignItems:'center',justifyContent:'center'},orbCut:{width:18,height:18,borderRadius:10,borderWidth:3,borderColor:colors.white},brandWord:{fontSize:14,fontWeight:'800',letterSpacing:-.2,color:colors.ink},brandSub:{fontSize:8,fontWeight:'800',letterSpacing:1.4,color:colors.faint,marginTop:2},railItems:{width:'100%',gap:3,marginTop:28},railItem:{minHeight:58,borderRadius:radius.md,paddingHorizontal:8,flexDirection:'row',alignItems:'center',gap:10},railActive:{backgroundColor:colors.surface,...elevation.low},railIcon:{width:40,height:40,borderRadius:radius.md,alignItems:'center',justifyContent:'center'},railIconActive:{backgroundColor:colors.brandSoft},railLabelWrap:{flex:1,gap:3},railLabel:{fontSize:type.labelMD,color:colors.muted,fontWeight:'700'},labelActive:{color:colors.ink,fontWeight:'800'},railMark:{height:2,width:0,borderRadius:2,backgroundColor:colors.accent},railMarkActive:{width:18},railFoot:{marginTop:'auto',paddingHorizontal:4,gap:8},footRule:{height:1,backgroundColor:colors.line},railFootText:{fontSize:8.5,fontWeight:'800',letterSpacing:1.1,textTransform:'uppercase',color:colors.faint},pressed:{opacity:.72,transform:[{scale:.985}]},dock:{position:'absolute',left:18,right:18,bottom:12,alignItems:'center'},dockInner:{height:72,backgroundColor:'rgba(255,255,255,0.96)',borderWidth:1,borderColor:colors.line,borderRadius:18,paddingHorizontal:5,flexDirection:'row',alignItems:'center',...elevation.medium},dockItem:{flex:1,minHeight:60,borderRadius:15,alignItems:'center',justifyContent:'center',gap:4},dockIcon:{width:42,height:34,alignItems:'center',justifyContent:'center',position:'relative'},iconActive:{},createDockItem:{flexGrow:1.02},createIcon:{width:48,height:48,borderRadius:14,backgroundColor:colors.brand},createIconActive:{backgroundColor:colors.brand},createGlyph:{width:42,height:42,borderRadius:12,borderWidth:1,borderColor:'rgba(255,255,255,0.45)',alignItems:'center',justifyContent:'center'},label:{fontSize:type.labelSM,color:colors.muted,fontWeight:'700'},createLabel:{fontWeight:'800',color:colors.brand}});