import { Image, Modal, Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { useState } from 'react';
import { VideoView, useVideoPlayer } from 'expo-video';
import { colors, radius, spacing, type } from './theme';
import { Icon } from './icons';

type Media={type:'image'|'video';uri:string;alt?:string;width?:number|null;height?:number|null;durationMs?:number|null};
function VideoCard({uri,onOpen}:{uri:string;onOpen:()=>void}){const player=useVideoPlayer(uri,p=>{p.loop=false;});return <View style={styles.mediaFrame}><VideoView player={player} style={styles.video} nativeControls/><Pressable accessibilityRole="button" accessibilityLabel="Open video viewer" onPress={onOpen} style={styles.videoOverlay}><View style={styles.playBadge}><Icon name="play" size={17} color={colors.white}/></View></Pressable></View>;}
export function PostMedia({items}:{items:Media[]}){const[selected,setSelected]=useState<number|null>(null);if(!items.length)return null;return <><View style={styles.wrap}>{items.length===1?<Pressable accessibilityRole="button" accessibilityLabel={items[0].alt||'Open media'} onPress={()=>setSelected(0)} style={styles.single}>{items[0].type==='image'?<Image source={{uri:items[0].uri}} accessibilityLabel={items[0].alt} style={styles.image}/>:<VideoCard uri={items[0].uri} onOpen={()=>setSelected(0)}/>}</Pressable>:<ScrollView horizontal pagingEnabled showsHorizontalScrollIndicator={false} contentContainerStyle={styles.carousel}>{items.map((m,i)=><Pressable key={`${m.uri}-${i}`} accessibilityRole="button" accessibilityLabel={m.alt||`Open media ${i+1} of ${items.length}`} onPress={()=>setSelected(i)} style={styles.slide}>{m.type==='image'?<Image source={{uri:m.uri}} accessibilityLabel={m.alt} style={styles.image}/>:<VideoCard uri={m.uri} onOpen={()=>setSelected(i)}/>}<View style={styles.count}><Text style={styles.countText}>{i+1}/{items.length}</Text></View></Pressable>)}</ScrollView>}</View><Modal visible={selected!==null} animationType="fade" transparent onRequestClose={()=>setSelected(null)} accessibilityViewIsModal><View style={styles.viewer}>{selected!==null&&items[selected]?(items[selected].type==='image'?<Image source={{uri:items[selected].uri}} accessibilityLabel={items[selected].alt} resizeMode="contain" style={styles.full}/>:<View style={styles.fullVideo}><VideoCard uri={items[selected].uri} onOpen={()=>{}}/></View>):null}<Pressable accessibilityRole="button" accessibilityLabel="Close media viewer" onPress={()=>setSelected(null)} style={styles.close}><Icon name="close" size={24} color={colors.white}/></Pressable></View></Modal></>}
const styles=StyleSheet.create({wrap:{width:'100%'},single:{overflow:'hidden',borderRadius:radius.hero,backgroundColor:colors.surfaceStrong,borderWidth:1,borderColor:colors.line},carousel:{gap:8},slide:{width:320,height:360,overflow:'hidden',borderRadius:radius.hero,backgroundColor:colors.surfaceStrong,borderWidth:1,borderColor:colors.line,position:'relative'},mediaFrame:{width:'100%',height:'100%',backgroundColor:colors.black,position:'relative'},video:{width:'100%',height:'100%'},videoOverlay:{position:'absolute',left:0,right:0,top:0,bottom:0,justifyContent:'flex-end',alignItems:'flex-start',padding:14},playBadge:{width:42,height:42,borderRadius:21,backgroundColor:colors.scrim,alignItems:'center',justifyContent:'center'},image:{width:'100%',height:'100%',minHeight:280,resizeMode:'cover'},count:{position:'absolute',right:12,top:12,paddingHorizontal:9,paddingVertical:5,borderRadius:radius.pill,backgroundColor:colors.scrim},countText:{color:colors.white,fontSize:type.labelSM,fontWeight:'800'},viewer:{flex:1,backgroundColor:colors.black,justifyContent:'center',alignItems:'center'},full:{width:'100%',height:'80%'},fullVideo:{width:'100%',height:'80%'},close:{position:'absolute',top:48,right:20,zIndex:2,width:46,height:46,borderRadius:23,backgroundColor:colors.scrim,alignItems:'center',justifyContent:'center'}});