import { PropsWithChildren, ReactNode } from 'react';
import { ActivityIndicator, Pressable, ScrollView, StyleSheet, Text, TextInput, type PressableProps, type TextInputProps, type TextProps, type ViewProps, View } from 'react-native';
import { colors, elevation, radius, spacing, type } from './theme';

export function Surface({ children, tone='default', style, ...props }: PropsWithChildren<ViewProps> & { tone?: 'default'|'soft'|'success'|'commerce'|'info'|'danger' }) { return <View {...props} style={[styles.surface, styles[tone], style]}>{children}</View>; }
export function AppText({ children, variant='body', style, ...props }: TextProps & { variant?: 'display'|'title'|'body'|'muted'|'label'|'caption' }) { return <Text {...props} style={[styles.text, styles[variant], style]}>{children}</Text>; }
export function Action({ children, label, variant='primary', disabled=false, style, ...props }: PressableProps & { label?: string; variant?: 'primary'|'secondary'|'quiet'|'danger' }) { return <Pressable {...props} disabled={disabled} accessibilityRole={props.accessibilityRole ?? 'button'} accessibilityLabel={props.accessibilityLabel ?? label} accessibilityState={{...(props.accessibilityState??{}),disabled}} style={({pressed})=>[styles.action, styles[`action_${variant}`], disabled&&styles.disabled, pressed&&!disabled&&styles.pressed, style]}>{children}</Pressable>; }
export function StateView({ title, body, action, icon, loading=false, tone='default' }: { title:string; body?:string; action?:ReactNode; icon?:ReactNode; loading?:boolean; tone?:'default'|'success'|'commerce'|'info'|'danger' }) { return <Surface tone={tone} style={styles.state}>{loading?<ActivityIndicator/>:icon}{loading?null:<AppText variant="title">{title}</AppText>}{body?<AppText accessibilityRole={tone==='danger'?'alert':undefined} variant="muted" style={styles.stateBody}>{body}</AppText>:null}{action?<View style={styles.stateAction}>{action}</View>:null}</Surface>; }
export function SectionHeader({ eyebrow, title, description, right }: {eyebrow?:string;title:string;description?:string;right?:ReactNode}) { return <View style={styles.sectionHeader}><View style={styles.sectionCopy}>{eyebrow?<AppText variant="caption" style={styles.eyebrow}>{eyebrow}</AppText>:null}<AppText variant="title">{title}</AppText>{description?<AppText variant="muted">{description}</AppText>:null}</View>{right}</View>; }
export function IconButton({ label, children, selected=false, disabled=false, ...props }: PressableProps & {label:string;children:ReactNode;selected?:boolean}) { return <Pressable {...props} disabled={disabled} accessibilityRole="button" accessibilityLabel={label} accessibilityState={{...(props.accessibilityState??{}),selected,disabled}} hitSlop={4} style={({pressed})=>[styles.iconButton,selected&&styles.iconButtonSelected,disabled&&styles.disabled,pressed&&!disabled&&styles.pressed]}>{children}</Pressable>; }
export function Button({ label, onPress, variant='primary', loading=false, disabled=false }: {label:string;onPress?:()=>void;variant?:'primary'|'secondary'|'quiet'|'danger';loading?:boolean;disabled?:boolean}) { return <Action label={label} variant={variant} disabled={disabled||loading} onPress={onPress}>{loading?<ActivityIndicator color={variant==='primary'||variant==='danger'?colors.white:colors.brand}/>:<Text style={[styles.buttonText,variant!=='primary'&&variant!=='danger'&&styles.buttonAlt]}>{label}</Text>}</Action>; }
export function Chip({ label, onPress, selected=false, disabled=false }: {label:string;onPress?:()=>void;selected?:boolean;disabled?:boolean}) { return <Pressable accessibilityRole="button" accessibilityLabel={label} accessibilityState={{selected,disabled}} disabled={disabled} onPress={onPress} style={({pressed})=>[styles.chip,selected&&styles.chipSelected,disabled&&styles.disabled,pressed&&!disabled&&styles.pressed]}><Text style={[styles.chipText,selected&&styles.chipTextSelected]}>{label}</Text></Pressable>; }
export function SearchField(props: TextInputProps & {label?:string}) { const {label='Search',style,...rest}=props; return <TextInput accessibilityLabel={label} placeholderTextColor={colors.faint} autoCorrect={false} autoCapitalize="none" {...rest} style={[styles.searchField,style]}/>; }
export function OfflineBanner({ visible=true, onRetry }: {visible?:boolean;onRetry?:()=>void}) { if(!visible)return null; return <View accessibilityRole="alert" style={styles.offline}><AppText variant="muted" style={styles.offlineText}>Offline mode — showing what is safely available.</AppText>{onRetry?<Button label="Retry" variant="quiet" onPress={onRetry}/>:null}</View>; }
export function Divider() { return <View accessible={false} style={styles.divider}/>; }
export function ScreenScroll({ children, contentStyle }: {children:ReactNode;contentStyle?:any}) { return <ScrollView keyboardShouldPersistTaps="handled" contentContainerStyle={[styles.scroll,contentStyle]}>{children}</ScrollView>; }

const styles=StyleSheet.create({
 surface:{backgroundColor:colors.surface,borderColor:colors.line,borderWidth:1,borderRadius:radius.lg,padding:spacing.lg,...elevation.low},default:{backgroundColor:colors.surface},soft:{backgroundColor:colors.surfaceStrong},success:{backgroundColor:colors.successSoft,borderColor:'#CFE9D9'},commerce:{backgroundColor:colors.commerceSoft,borderColor:'#F0D5BC'},info:{backgroundColor:colors.infoSoft,borderColor:'#D5E6F5'},danger:{backgroundColor:colors.dangerSoft,borderColor:'#F3C9C5'},text:{color:colors.ink},display:{fontSize:type.displayLG,lineHeight:38,fontWeight:'800'},title:{fontSize:type.titleMD,lineHeight:24,fontWeight:'800'},body:{fontSize:type.bodyMD,lineHeight:22},muted:{fontSize:type.bodySM,lineHeight:21,color:colors.muted},label:{fontSize:type.labelLG,lineHeight:20,fontWeight:'700'},caption:{fontSize:type.labelSM,lineHeight:15,color:colors.faint},
 action:{minHeight:44,borderRadius:radius.md,paddingHorizontal:16,alignItems:'center',justifyContent:'center',...elevation.low},action_primary:{backgroundColor:colors.brand},action_secondary:{backgroundColor:colors.surface,borderWidth:1,borderColor:colors.line},action_quiet:{backgroundColor:colors.brandSoft,...elevation.none},action_danger:{backgroundColor:colors.danger},buttonText:{color:colors.white,fontWeight:'800',fontSize:type.labelLG},buttonAlt:{color:colors.brand},chip:{minHeight:40,paddingHorizontal:14,borderRadius:radius.pill,borderWidth:1,borderColor:colors.line,backgroundColor:colors.surface,justifyContent:'center'},chipSelected:{backgroundColor:colors.brandSoft,borderColor:colors.brand},chipText:{fontSize:type.labelMD,fontWeight:'700',color:colors.muted},chipTextSelected:{color:colors.brand},searchField:{minHeight:48,borderWidth:1,borderColor:colors.line,borderRadius:radius.md,backgroundColor:colors.surface,paddingHorizontal:15,color:colors.ink,fontSize:type.bodyMD},iconButton:{width:46,height:46,borderRadius:radius.md,borderWidth:1,borderColor:colors.line,backgroundColor:colors.surface,alignItems:'center',justifyContent:'center'},iconButtonSelected:{backgroundColor:colors.brandSoft,borderColor:colors.brand},sectionHeader:{flexDirection:'row',alignItems:'flex-start',gap:spacing.md},sectionCopy:{flex:1,gap:4},eyebrow:{fontWeight:'800',letterSpacing:1.7,color:colors.brand},state:{marginTop:spacing.sm,gap:2},stateBody:{marginTop:6},stateAction:{marginTop:spacing.md},offline:{minHeight:48,paddingHorizontal:spacing.md,paddingVertical:spacing.xs,backgroundColor:colors.warningSoft,flexDirection:'row',alignItems:'center',gap:spacing.md,borderBottomWidth:1,borderBottomColor:'#EAD8A1'},offlineText:{flex:1,color:colors.inkSoft,fontWeight:'700'},divider:{height:1,backgroundColor:colors.line,width:'100%'},scroll:{padding:spacing.xl,gap:spacing.lg},disabled:{opacity:.45},pressed:{opacity:.72,transform:[{scale:.99}]}
});
