import {useEffect,useState} from 'react';
import {Stack} from 'expo-router';
import * as NativeSplash from 'expo-splash-screen';
import {StatusBar} from 'expo-status-bar';
import {ActivityIndicator,StyleSheet,Text,View} from 'react-native';
import {AuthProvider} from '../src/core/auth/AuthProvider';
import {colors,type} from '../src/ui/theme';
void NativeSplash.preventAutoHideAsync().catch(()=>undefined);
const absoluteFillObject={position:'absolute' as const,top:0,left:0,right:0,bottom:0};
export default function RootLayout(){const[ready,setReady]=useState(false);useEffect(()=>{const t=setTimeout(()=>{setReady(true);void NativeSplash.hideAsync();},460);return()=>clearTimeout(t);},[]);return <AuthProvider><StatusBar style="dark"/><Stack screenOptions={{headerShown:false,animation:'fade',animationDuration:160,gestureEnabled:true,contentStyle:{backgroundColor:colors.canvas}}}/>{!ready?<View pointerEvents="none" style={s.overlay}><View style={s.mark}><View style={s.nodeA}/><View style={s.nodeB}/><View style={s.nodeC}/><View style={s.bridgeA}/><View style={s.bridgeB}/><View style={s.orbit}/></View><Text style={s.brand}>drustpoll</Text><Text style={s.tag}>people · ideas · places</Text><View style={s.loading}><ActivityIndicator color={colors.brand}/><Text style={s.loadingText}>shaping your space</Text></View></View>:null}</AuthProvider>}
const s=StyleSheet.create({overlay:{...absoluteFillObject,backgroundColor:colors.canvas,alignItems:'center',justifyContent:'center',paddingHorizontal:24},mark:{width:96,height:96,borderRadius:32,backgroundColor:colors.brand,position:'relative',transform:[{rotate:'-6deg'}],shadowColor:'#102B24',shadowOpacity:.12,shadowRadius:18,shadowOffset:{width:0,height:8},elevation:6},nodeA:{position:'absolute',width:13,height:13,borderRadius:7,backgroundColor:colors.white,left:22,top:25},nodeB:{position:'absolute',width:13,height:13,borderRadius:7,backgroundColor:colors.white,right:21,top:19},nodeC:{position:'absolute',width:13,height:13,borderRadius:7,backgroundColor:colors.white,left:41,bottom:19},bridgeA:{position:'absolute',height:2,width:31,backgroundColor:colors.white,left:32,top:28,transform:[{rotate:'-13deg'}]},bridgeB:{position:'absolute',height:2,width:27,backgroundColor:colors.white,left:31,top:47,transform:[{rotate:'51deg'}]},orbit:{position:'absolute',width:56,height:21,borderRadius:12,borderWidth:2,borderColor:colors.social,left:20,top:35,transform:[{rotate:'20deg'}],opacity:.75},brand:{marginTop:22,fontSize:30,fontWeight:'900',letterSpacing:-1,color:colors.ink},tag:{marginTop:5,fontSize:type.bodySM,fontWeight:'700',letterSpacing:1,color:colors.muted},loading:{marginTop:18,minHeight:40,flexDirection:'row',alignItems:'center',gap:9},loadingText:{fontSize:type.labelSM,fontWeight:'800',color:colors.faint}});