import AsyncStorage from '@react-native-async-storage/async-storage';
import { useEffect,useState } from 'react';
import { ActivityIndicator,Pressable,ScrollView,StyleSheet,Switch,Text,View } from 'react-native';
import { Link } from 'expo-router';
import { AppShell } from '../src/ui/AppShell';
import { Icon } from '../src/ui/icons';
import { colors,radius,spacing,type } from '../src/ui/theme';
const KEY='drustpoll.experience.preferences';
export default function Accessibility(){const[largeText,setLargeText]=useState(false);const[reducedMotion,setReducedMotion]=useState(false);const[dataSaver,setDataSaver]=useState(false);const[loading,setLoading]=useState(true);useEffect(()=>{void AsyncStorage.getItem(KEY).then(raw=>{if(raw)try{const p=JSON.parse(raw);if(typeof p.largeText==='boolean')setLargeText(p.largeText);if(typeof p.reducedMotion==='boolean')setReducedMotion(p.reducedMotion);if(typeof p.dataSaver==='boolean')setDataSaver(p.dataSaver);}catch{} }).finally(()=>setLoading(false));},[]);const save=(patch:Record<string,boolean>)=>{const next={largeText,reducedMotion,dataSaver,...patch};setLargeText(next.largeText);setReducedMotion(next.reducedMotion);setDataSaver(next.dataSaver);void AsyncStorage.setItem(KEY,JSON.stringify(next));};return <AppShell><ScrollView contentContainerStyle={styles.content}><Link href="/settings" asChild><Pressable accessibilityRole="button" style={styles.back}><Icon name="back" size={18} color={colors.brand}/><Text style={styles.backText}>Settings</Text></Pressable></Link><Text style={styles.kicker}>ACCESSIBILITY</Text><Text style={styles.title}>Make the interface fit you.</Text><Text style={styles.subtitle}>Accessibility preferences are local-first, reversible and never used as a reason to expose extra personal data.</Text>{loading?<View style={styles.center}><ActivityIndicator/><Text style={styles.muted}>Loading accessibility preferences…</Text></View>:<><View style={styles.card}><Toggle title="Larger text" body="Increase Drustpoll's own reading scale where supported. Your operating-system text setting remains respected." value={largeText} onChange={v=>save({largeText:v})}/><Toggle title="Reduced motion" body="Remove nonessential movement and keep transitions calmer." value={reducedMotion} onChange={v=>save({reducedMotion:v})}/><Toggle title="Data saver" body="Reduce media preloading and background transfer." value={dataSaver} onChange={v=>save({dataSaver:v})}/></View><View style={styles.preview}><Text style={[styles.previewTitle,largeText&&styles.large]}>Readable by default.</Text><Text style={[styles.previewBody,largeText&&styles.largeBody]}>State is communicated by text, structure and feedback—not color alone. Touch targets remain forgiving and essential actions do not depend on animation.</Text></View></>}<View style={styles.note}><Text style={styles.noteTitle}>System settings still win.</Text><Text style={styles.noteBody}>Drustpoll complements platform accessibility services; it does not override OS-level assistive technology preferences.</Text></View></ScrollView></AppShell>}
function Toggle({title,body,value,onChange}:{title:string;body:string;value:boolean;onChange:(v:boolean)=>void}){return <View style={styles.row}><View style={styles.copy}><Text style={styles.rowTitle}>{title}</Text><Text style={styles.rowBody}>{body}</Text></View><Switch value={value} onValueChange={onChange} accessibilityRole="switch" accessibilityLabel={title} accessibilityState={{checked:value}}/></View>}
const styles=StyleSheet.create({content:{padding:spacing.xl,gap:spacing.lg,maxWidth:760,width:'100%',alignSelf:'center'},back:{fontWeight:'800',color:colors.brand,minHeight:44,flexDirection:'row',alignItems:'center',gap:8},backText:{fontWeight:'800',color:colors.brand},kicker:{fontSize:type.labelSM,fontWeight:'800',letterSpacing:1.8,color:colors.brand},title:{fontSize:type.displayLG,lineHeight:38,fontWeight:'800',color:colors.ink},subtitle:{fontSize:type.bodySM,lineHeight:21,color:colors.muted},center:{minHeight:180,justifyContent:'center',alignItems:'center',gap:8},muted:{color:colors.muted},card:{backgroundColor:colors.surface,borderWidth:1,borderColor:colors.line,borderRadius:radius.lg,overflow:'hidden'},row:{minHeight:94,padding:spacing.lg,flexDirection:'row',alignItems:'center',gap:12,borderBottomWidth:1,borderBottomColor:colors.line},copy:{flex:1},rowTitle:{fontSize:type.bodyMD,fontWeight:'800',color:colors.ink},rowBody:{fontSize:type.bodySM,lineHeight:20,color:colors.muted,marginTop:4},preview:{padding:spacing.xl,borderRadius:radius.hero,backgroundColor:colors.surface,borderWidth:1,borderColor:colors.line},previewTitle:{fontSize:type.titleXL,fontWeight:'800',color:colors.ink},previewBody:{fontSize:type.bodyMD,lineHeight:23,color:colors.inkSoft,marginTop:8},large:{fontSize:28},largeBody:{fontSize:18,lineHeight:27},note:{padding:spacing.xl,borderRadius:radius.lg,backgroundColor:colors.infoSoft},noteTitle:{fontSize:type.titleMD,fontWeight:'800',color:colors.ink},noteBody:{fontSize:type.bodySM,lineHeight:21,color:colors.inkSoft,marginTop:5}});
