import { useCallback, useState } from 'react';
import { ActivityIndicator, Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { AppShell } from '../src/ui/AppShell';
import { checkout } from '../src/api/client';
import { colors, radius, spacing, type } from '../src/ui/theme';

export default function Checkout(){
 const [state,setState]=useState<'review'|'submitting'|'success'|'error'>('review'); const [error,setError]=useState<string|null>(null);
 const [key]=useState(()=>`checkout-${Date.now()}-${Math.random().toString(36).slice(2)}`);
 const submit=useCallback(async()=>{if(state==='submitting'||state==='success')return;setState('submitting');setError(null);try{await checkout(key);setState('success');}catch(e){setState('error');setError(e instanceof Error?e.message:'Could not create order');}},[key,state]);
 return <AppShell><ScrollView contentContainerStyle={styles.content}><Text style={styles.kicker}>CHECKOUT</Text><Text style={styles.title}>Review before you buy.</Text><Text style={styles.sub}>Nothing is charged merely by opening this page. Order creation happens only after your explicit confirmation.</Text>
  {state==='success'?<View style={styles.success}><Text style={styles.icon}>✓</Text><Text style={styles.heading}>Order created</Text><Text style={styles.body}>Your order is now in its own payment lifecycle. Payment confirmation is not inferred from this screen.</Text></View>:<>
   <View style={styles.card}><Text style={styles.cardTitle}>Order review</Text><View style={styles.row}><Text style={styles.label}>Items</Text><Text style={styles.value}>Your current cart</Text></View><View style={styles.row}><Text style={styles.label}>Payment</Text><Text style={styles.value}>Provider confirmation required</Text></View><View style={styles.row}><Text style={styles.label}>Authorization</Text><Text style={styles.value}>Explicit confirmation</Text></View></View>
   {error?<View accessibilityRole="alert" style={styles.error}><Text style={styles.errorTitle}>Checkout could not continue</Text><Text style={styles.errorBody}>{error}</Text></View>:null}
   <Pressable accessibilityRole="button" accessibilityState={{disabled:state==='submitting'}} disabled={state==='submitting'} onPress={()=>void submit()} style={styles.confirm}>{state==='submitting'?<ActivityIndicator color={colors.white}/>:<Text style={styles.confirmText}>{state==='error'?'Try checkout again':'Confirm order'}</Text>}</Pressable>
   <Text style={styles.note}>Order creation uses an idempotency key so retries do not intentionally create duplicate orders.</Text>
  </>}
 </ScrollView></AppShell>;
}
const styles=StyleSheet.create({content:{padding:spacing.xl,gap:spacing.lg,maxWidth:760,width:'100%',alignSelf:'center'},kicker:{fontSize:type.labelSM,fontWeight:'800',letterSpacing:1.8,color:colors.commerce},title:{fontSize:type.displayLG,lineHeight:38,fontWeight:'800',color:colors.ink},sub:{fontSize:type.bodySM,lineHeight:21,color:colors.muted},card:{backgroundColor:colors.surface,borderWidth:1,borderColor:colors.line,borderRadius:radius.lg,padding:spacing.xl},cardTitle:{fontSize:type.titleMD,fontWeight:'800',color:colors.ink,marginBottom:12},row:{paddingVertical:12,borderTopWidth:1,borderTopColor:colors.line,flexDirection:'row',justifyContent:'space-between',gap:16},label:{color:colors.muted,fontSize:type.bodySM},value:{color:colors.ink,fontSize:type.bodySM,fontWeight:'700',flex:1,textAlign:'right'},confirm:{minHeight:50,borderRadius:radius.md,backgroundColor:colors.commerce,alignItems:'center',justifyContent:'center'},confirmText:{color:colors.white,fontWeight:'800',fontSize:type.bodyMD},note:{fontSize:type.labelSM,lineHeight:18,color:colors.muted,textAlign:'center'},error:{padding:spacing.lg,borderRadius:radius.lg,borderWidth:1,borderColor:colors.danger,backgroundColor:colors.dangerSoft},errorTitle:{color:colors.danger,fontWeight:'800'},errorBody:{color:colors.inkSoft,lineHeight:20,marginTop:5},success:{padding:spacing.xxl,borderRadius:radius.hero,borderWidth:1,borderColor:'#CFE9D9',backgroundColor:colors.successSoft,alignItems:'center'},icon:{fontSize:42,color:colors.success},heading:{fontSize:type.titleXL,fontWeight:'800',color:colors.ink,marginTop:8},body:{fontSize:type.bodySM,lineHeight:21,color:colors.inkSoft,textAlign:'center',marginTop:6,maxWidth:500}});