import { useCallback, useEffect, useState } from 'react';
import { ActivityIndicator, Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { Link, useLocalSearchParams } from 'expo-router';
import { AppShell } from '../src/ui/AppShell';
import { getCollection } from '../src/api/client';
import { colors, elevation, radius, spacing, type } from '../src/ui/theme';
import { Icon } from '../src/ui/icons';
import { PostMedia } from '../src/ui/PostMedia';
export default function Collection(){const {id}=useLocalSearchParams<{id?:string}>();const collectionId=Array.isArray(id)?id[0]:id;const[data,setData]=useState<any>(null);const[loading,setLoading]=useState(true);const[error,setError]=useState<string|null>(null);const load=useCallback(async()=>{if(!collectionId){setError('Collection unavailable');setLoading(false);return;}setLoading(true);setError(null);try{setData(await getCollection(collectionId));}catch(e){setError(e instanceof Error?e.message:'Could not load collection');}finally{setLoading(false);}},[collectionId]);useEffect(()=>{void load();},[load]);return <AppShell><ScrollView contentContainerStyle={styles.content}><Link href="/profile" asChild><Pressable accessibilityRole="button" style={styles.back}><Icon name="back" size={19} color={colors.ink}/><Text style={styles.backText}>Profile</Text></Pressable></Link>{loading?<View style={styles.center}><ActivityIndicator/><Text style={styles.muted}>Loading collection…</Text></View>:error?<View accessibilityRole="alert" style={styles.error}><Text style={styles.errorTitle}>Collection unavailable</Text><Text style={styles.errorBody}>{error}</Text><Pressable accessibilityRole="button" onPress={()=>void load()} style={styles.retry}><Text style={styles.retryText}>Try again</Text></Pressable></View>:data?<><Text style={styles.kicker}>COLLECTION</Text><Text style={styles.title}>{data.collection.name||'Collection'}</Text><Text style={styles.body}>{data.collection.description||'Saved ideas in one place.'}</Text>{data.posts?.length?data.posts.map((p:any)=><View key={p.id} style={styles.card}><Text style={styles.name}>{p.display_name||p.username}</Text>{p.caption?<Text style={styles.caption}>{p.caption}</Text>:null}{p.media?<PostMedia items={p.media.map((m:any)=>({...m,uri:m.uri||m.storageKey}))}/>:null}</View>):<View style={styles.empty}><Icon name="bookmark" size={28} color={colors.faint}/><Text style={styles.emptyTitle}>Nothing saved here yet</Text></View>}</>:null}</ScrollView></AppShell>}
const styles=StyleSheet.create({content:{padding:spacing.xl,gap:12,maxWidth:800,width:'100%',alignSelf:'center'},back:{minHeight:44,paddingHorizontal:12,borderRadius:radius.md,borderWidth:1,borderColor:colors.line,backgroundColor:colors.surface,alignSelf:'flex-start',flexDirection:'row',alignItems:'center',gap:6},backText:{fontWeight:'800',color:colors.ink},center:{minHeight:220,alignItems:'center',justifyContent:'center',gap:8},muted:{fontSize:type.bodySM,color:colors.muted},error:{padding:spacing.lg,borderRadius:radius.lg,backgroundColor:colors.dangerSoft,borderWidth:1,borderColor:colors.danger},errorTitle:{fontWeight:'800',color:colors.danger},errorBody:{color:colors.inkSoft,lineHeight:21,marginTop:4},retry:{marginTop:10,minHeight:44,paddingHorizontal:14,borderRadius:radius.md,backgroundColor:colors.brand,justifyContent:'center',alignSelf:'flex-start'},retryText:{color:colors.white,fontWeight:'800'},kicker:{fontSize:type.labelSM,fontWeight:'800',letterSpacing:1.8,color:colors.brand},title:{fontSize:type.displayLG,fontWeight:'900',color:colors.ink},body:{fontSize:type.bodyMD,lineHeight:22,color:colors.muted},card:{padding:spacing.lg,borderRadius:radius.lg,borderWidth:1,borderColor:colors.line,backgroundColor:colors.surface,...elevation.low},name:{fontWeight:'800',color:colors.ink},caption:{fontSize:type.bodyMD,lineHeight:22,color:colors.inkSoft,marginVertical:8},empty:{padding:spacing.xxl,borderRadius:radius.lg,borderWidth:1,borderColor:colors.line,alignItems:'center',gap:8},emptyTitle:{fontWeight:'800',fontSize:type.titleMD,color:colors.ink}});