import { useCallback, useEffect, useState } from 'react';
import { ActivityIndicator, KeyboardAvoidingView, Platform, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import { useLocalSearchParams } from 'expo-router';
import { AppShell } from '../src/ui/AppShell';
import { addComment } from '../src/api/client';
import { colors, radius, spacing, type } from '../src/ui/theme';

export default function Comments(){
 const {postId}=useLocalSearchParams<{postId?:string}>();const id=Array.isArray(postId)?postId[0]:postId;
 const [body,setBody]=useState('');const [sending,setSending]=useState(false);const [sent,setSent]=useState(0);const [error,setError]=useState<string|null>(null);
 const submit=async()=>{if(!id||!body.trim()||sending)return;setSending(true);setError(null);try{await addComment(id,body.trim());setBody('');setSent(x=>x+1);}catch(e){setError(e instanceof Error?e.message:'Could not add comment');}finally{setSending(false);}};
 return <AppShell><KeyboardAvoidingView style={styles.wrap} behavior={Platform.OS==='ios'?'padding':undefined}><View style={styles.header}><View><Text style={styles.kicker}>CONVERSATION</Text><Text style={styles.title}>Comments</Text></View></View><Text style={styles.subtitle}>Replies are part of the post conversation. New comments appear after server confirmation.</Text><View style={styles.empty}><Text style={styles.emptyTitle}>{sent?'Comment added.':'Open the conversation'}</Text><Text style={styles.emptyBody}>{id?`Post ${id} is ready for the full comment stream.`:'A post id is required to open comments.'}</Text></View><View style={styles.composer}><TextInput value={body} onChangeText={setBody} multiline maxLength={2000} placeholder="Add a thoughtful comment…" placeholderTextColor={colors.faint} accessibilityLabel="Comment text" style={styles.input}/><View style={styles.bottom}><Text style={styles.counter}>{body.length}/2000</Text><Pressable accessibilityRole="button" accessibilityState={{disabled:sending||!body.trim(),busy:sending}} disabled={sending||!body.trim()} onPress={()=>void submit()} style={[styles.send,(sending||!body.trim())&&styles.disabled]}>{sending?<ActivityIndicator color={colors.white}/>:<Text style={styles.sendText}>Send</Text>}</Pressable></View></View>{error?<View accessibilityRole="alert" style={styles.error}><Text style={styles.errorText}>{error}</Text></View>:null}<ScrollView contentContainerStyle={styles.notes}><View style={styles.note}><Text style={styles.noteTitle}>Thread-ready</Text><Text style={styles.noteBody}>The backend supports parent comments and replies. This surface is intentionally separate from the feed so reading and replying can remain focused.</Text></View></ScrollView></KeyboardAvoidingView></AppShell>;
}
const styles=StyleSheet.create({wrap:{flex:1,padding:spacing.xl,gap:spacing.md,maxWidth:760,width:'100%',alignSelf:'center'},header:{flexDirection:'row',justifyContent:'space-between',alignItems:'center'},kicker:{fontSize:type.labelSM,fontWeight:'800',letterSpacing:1.8,color:colors.social},title:{fontSize:type.displayLG,fontWeight:'800',lineHeight:38,color:colors.ink},subtitle:{fontSize:type.bodySM,lineHeight:21,color:colors.muted},empty:{padding:spacing.xl,borderRadius:radius.lg,borderWidth:1,borderColor:colors.line,backgroundColor:colors.surface},emptyTitle:{fontSize:type.titleMD,fontWeight:'800',color:colors.ink},emptyBody:{fontSize:type.bodySM,lineHeight:21,color:colors.muted,marginTop:4},composer:{borderWidth:1,borderColor:colors.line,borderRadius:radius.lg,backgroundColor:colors.surface,padding:spacing.md},input:{minHeight:110,color:colors.ink,fontSize:type.bodyMD,lineHeight:22,textAlignVertical:'top'},bottom:{flexDirection:'row',alignItems:'center',justifyContent:'space-between'},counter:{fontSize:type.labelSM,color:colors.faint},send:{minHeight:44,paddingHorizontal:18,borderRadius:radius.md,backgroundColor:colors.brand,alignItems:'center',justifyContent:'center'},sendText:{color:colors.white,fontWeight:'800'},disabled:{opacity:.45},error:{padding:spacing.md,borderRadius:radius.md,backgroundColor:colors.dangerSoft,borderWidth:1,borderColor:colors.danger},errorText:{color:colors.danger,fontWeight:'700'},notes:{paddingBottom:spacing.xl},note:{padding:spacing.xl,borderRadius:radius.lg,backgroundColor:colors.socialSoft},noteTitle:{fontSize:type.titleMD,fontWeight:'800',color:colors.ink},noteBody:{fontSize:type.bodySM,lineHeight:21,color:colors.inkSoft,marginTop:5}});