import { useCallback, useEffect, useState } from 'react';
import { ActivityIndicator, Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { Link, useLocalSearchParams } from 'expo-router';
import { AppShell } from '../src/ui/AppShell';
import { getMessages, markConversationRead } from '../src/api/client';
import { colors, radius, spacing, type } from '../src/ui/theme';

export default function Conversation(){
 const {id}=useLocalSearchParams<{id?:string}>();const conversationId=Array.isArray(id)?id[0]:id;
 const [messages,setMessages]=useState<Awaited<ReturnType<typeof getMessages>>['messages']>([]);const [nextBefore,setNextBefore]=useState<string|null>(null);const [loading,setLoading]=useState(true);const [loadingMore,setLoadingMore]=useState(false);const [error,setError]=useState<string|null>(null);
 const load=useCallback(async()=>{if(!conversationId){setError('Conversation is unavailable');setLoading(false);return;}setLoading(true);setError(null);try{const r=await getMessages(conversationId);setMessages(r.messages??[]);setNextBefore(r.nextBefore??null);await markConversationRead(conversationId);}catch(e){setError(e instanceof Error?e.message:'Could not load conversation');}finally{setLoading(false);}},[conversationId]);
 const loadOlder=useCallback(async()=>{if(!conversationId||!nextBefore||loadingMore)return;setLoadingMore(true);setError(null);try{const r=await getMessages(conversationId,50,nextBefore);setMessages(prev=>{const seen=new Set(prev.map(x=>x.id));return [...(r.messages??[]).filter(x=>!seen.has(x.id)),...prev];});setNextBefore(r.nextBefore??null);}catch(e){setError(e instanceof Error?e.message:'Could not load older messages');}finally{setLoadingMore(false);}},[conversationId,loadingMore,nextBefore]);
 useEffect(()=>{void load();},[load]);
 return <AppShell><ScrollView contentContainerStyle={styles.content}><View style={styles.header}><View><Text style={styles.kicker}>CONNECT</Text><Text style={styles.title}>Private conversation</Text></View><Link href="/messages" asChild><Pressable accessibilityRole="button" style={styles.back}><Text style={styles.backText}>Back</Text></Pressable></Link></View><Text style={styles.subtitle}>Encrypted message envelopes are displayed without exposing plaintext to the server.</Text>{loading?<View style={styles.center}><ActivityIndicator/><Text style={styles.muted}>Loading secure messages…</Text></View>:error&&!messages.length?<View accessibilityRole="alert" style={styles.alert}><Text style={styles.alertTitle}>Conversation unavailable</Text><Text style={styles.alertBody}>{error}</Text><Pressable accessibilityRole="button" onPress={()=>void load()} style={styles.secondary}><Text style={styles.secondaryText}>Try again</Text></Pressable></View>:<><View style={styles.list}>{nextBefore?<Pressable accessibilityRole="button" accessibilityLabel="Load older encrypted messages" accessibilityState={{busy:loadingMore,disabled:loadingMore}} disabled={loadingMore} onPress={()=>void loadOlder()} style={styles.more}>{loadingMore?<ActivityIndicator/>:<Text style={styles.moreText}>Load older messages</Text>}</Pressable>:null}{messages.length?messages.map(m=><View key={m.id} style={styles.message}><Text style={styles.meta}>{m.sender_id} · {new Date(m.created_at).toLocaleString()}</Text><Text style={styles.cipher} numberOfLines={4}>{m.ciphertext}</Text><Text style={styles.state}>{m.read_at?'Seen':m.delivered_at?'Delivered':'Sent'} · key v{m.key_version}</Text></View>):<View style={styles.empty}><Text style={styles.emptyTitle}>No messages yet.</Text><Text style={styles.emptyBody}>This conversation has no stored encrypted messages.</Text></View>}</View>{error?<View accessibilityRole="alert" style={styles.inlineError}><Text style={styles.alertBody}>{error}</Text><Pressable accessibilityRole="button" onPress={()=>void load()} style={styles.retry}><Text style={styles.retryText}>Retry</Text></Pressable></View>:null}</>}<View style={styles.note}><Text style={styles.noteKicker}>CRYPTO BOUNDARY</Text><Text style={styles.noteTitle}>No fake end-to-end encryption.</Text><Text style={styles.noteBody}>The transport stores ciphertext and key metadata. A complete audited client-side E2EE protocol still requires an audited maintained cryptographic implementation before plaintext messaging is enabled.</Text></View></ScrollView></AppShell>;
}
const styles=StyleSheet.create({content:{padding:spacing.xl,gap:spacing.lg,maxWidth:760,width:'100%',alignSelf:'center'},header:{flexDirection:'row',justifyContent:'space-between',alignItems:'center',gap:12},kicker:{fontSize:type.labelSM,fontWeight:'800',letterSpacing:1.8,color:colors.brand},title:{fontSize:type.displayLG,lineHeight:38,fontWeight:'800',color:colors.ink},subtitle:{fontSize:type.bodySM,lineHeight:21,color:colors.muted},back:{minHeight:44,paddingHorizontal:14,borderWidth:1,borderColor:colors.line,borderRadius:radius.md,justifyContent:'center'},backText:{fontWeight:'800',color:colors.ink},center:{minHeight:220,alignItems:'center',justifyContent:'center',gap:8},muted:{color:colors.muted},alert:{padding:spacing.lg,borderRadius:radius.lg,borderWidth:1,borderColor:colors.danger,backgroundColor:colors.dangerSoft},alertTitle:{fontWeight:'800',color:colors.danger},alertBody:{color:colors.inkSoft,lineHeight:21,marginTop:4},secondary:{marginTop:12,minHeight:44,paddingHorizontal:14,borderRadius:radius.md,borderWidth:1,borderColor:colors.line,alignSelf:'flex-start',justifyContent:'center'},secondaryText:{color:colors.ink,fontWeight:'800'},inlineError:{padding:spacing.md,borderRadius:radius.md,backgroundColor:colors.dangerSoft,gap:8},retry:{alignSelf:'flex-start',minHeight:40,paddingHorizontal:12,borderRadius:radius.md,borderWidth:1,borderColor:colors.line,justifyContent:'center'},retryText:{fontWeight:'800',color:colors.ink},list:{gap:10},more:{minHeight:44,borderRadius:radius.md,borderWidth:1,borderColor:colors.line,backgroundColor:colors.surface,alignItems:'center',justifyContent:'center'},moreText:{color:colors.brand,fontWeight:'800'},message:{padding:spacing.lg,borderRadius:radius.lg,backgroundColor:colors.surface,borderWidth:1,borderColor:colors.line},meta:{fontSize:type.labelSM,color:colors.muted},cipher:{fontSize:type.bodySM,lineHeight:20,color:colors.ink,marginTop:8,fontFamily:'monospace'},state:{fontSize:type.labelSM,color:colors.faint,marginTop:8},empty:{padding:spacing.xxl,alignItems:'center',borderRadius:radius.lg,borderWidth:1,borderColor:colors.line,backgroundColor:colors.surface},emptyTitle:{fontSize:type.titleMD,fontWeight:'800',color:colors.ink},emptyBody:{fontSize:type.bodySM,color:colors.muted,textAlign:'center',marginTop:5},note:{padding:spacing.xl,borderRadius:radius.lg,backgroundColor:colors.successSoft,borderWidth:1,borderColor:'#CFE9D9'},noteKicker:{fontSize:type.labelSM,fontWeight:'800',letterSpacing:1.5,color:colors.success},noteTitle:{fontSize:type.titleMD,fontWeight:'800',color:colors.ink},noteBody:{fontSize:type.bodySM,lineHeight:21,color:colors.inkSoft,marginTop:6}});