import { useEffect, useMemo, useState } from 'react';
import { ActivityIndicator, FlatList, Pressable, StyleSheet, Text, TextInput, View } from 'react-native';
import { router } from 'expo-router';
import { locales, loadLocale, saveLocale, type Locale } from '../src/i18n/core';
import { colors, radius, spacing, type } from '../src/ui/theme';
import { Icon } from '../src/ui/icons';

export default function LanguageScreen(){
 const [selected,setSelected]=useState('en'); const [query,setQuery]=useState(''); const [saving,setSaving]=useState(false);
 useEffect(()=>{void loadLocale().then(setSelected);},[]);
 const filtered=useMemo(()=>{const q=query.trim().toLowerCase();return q?locales.filter(x=>`${x.nativeName} ${x.englishName}`.toLowerCase().includes(q)):locales;},[query]);
 async function choose(item:Locale){setSaving(true);setSelected(item.code);await saveLocale(item.code);setSaving(false);router.replace('/');}
 return <View style={s.screen}><View style={s.header}><Pressable accessibilityRole="button" accessibilityLabel="Back" onPress={()=>router.back()} style={s.icon}><Icon name="back" size={20} color={colors.ink}/></Pressable><View style={s.copy}><Text style={s.kicker}>LANGUAGE</Text><Text style={s.title}>Choose how Drustpoll speaks to you.</Text><Text style={s.body}>Your language choice applies across the product.</Text></View></View><TextInput value={query} onChangeText={setQuery} placeholder="Search languages" placeholderTextColor={colors.faint} style={s.search} accessibilityLabel="Search languages"/><FlatList data={filtered} keyExtractor={x=>x.code} contentContainerStyle={s.list} renderItem={({item})=><Pressable accessibilityRole="radio" accessibilityState={{selected:selected===item.code}} onPress={()=>void choose(item)} style={({pressed})=>[s.row,selected===item.code&&s.selected,pressed&&s.pressed]}><View style={s.names}><Text style={s.native}>{item.nativeName}</Text><Text style={s.english}>{item.englishName}{item.direction==='rtl'?' · RTL':''}</Text></View>{selected===item.code?(saving?<ActivityIndicator/>:<Icon name="check" size={20} color={colors.brand}/>):null}</Pressable>}/></View>;
}
const s=StyleSheet.create({screen:{flex:1,backgroundColor:colors.canvas,padding:spacing.xl},header:{flexDirection:'row',alignItems:'flex-start',gap:12},icon:{width:44,height:44,borderRadius:radius.md,borderWidth:1,borderColor:colors.line,backgroundColor:colors.surface,alignItems:'center',justifyContent:'center'},copy:{flex:1},kicker:{fontSize:type.labelSM,fontWeight:'900',letterSpacing:1.8,color:colors.brand},title:{fontSize:type.titleXL,lineHeight:31,fontWeight:'900',color:colors.ink,marginTop:3},body:{fontSize:type.bodySM,lineHeight:20,color:colors.muted,marginTop:4},search:{height:50,borderBottomWidth:1,borderBottomColor:colors.line,color:colors.ink,fontSize:16,marginTop:20},list:{paddingVertical:10,gap:4},row:{minHeight:64,paddingHorizontal:14,borderRadius:radius.md,flexDirection:'row',alignItems:'center',justifyContent:'space-between'},selected:{backgroundColor:colors.brandSoft},names:{flex:1},native:{fontSize:16,fontWeight:'800',color:colors.ink},english:{fontSize:12,color:colors.muted,marginTop:2},pressed:{opacity:.72}});