import { useCallback, useEffect, useState } from 'react';
import { ActivityIndicator, Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { Link, useLocalSearchParams } from 'expo-router';
import { AppShell } from '../src/ui/AppShell';
import { addCartItem, getProduct, recordCommerceEvent } from '../src/api/client';
import { colors, elevation, radius, spacing, type } from '../src/ui/theme';

type Product=Awaited<ReturnType<typeof getProduct>>['product'];
export default function Product(){
 const {id}=useLocalSearchParams<{id?:string}>();const productId=Array.isArray(id)?id[0]:id;const[p,setP]=useState<Product|null>(null);const[loading,setLoading]=useState(true);const[error,setError]=useState<string|null>(null);const[state,setState]=useState<'idle'|'adding'|'added'>('idle');
 const load=useCallback(async()=>{if(!productId){setError('Product is unavailable');setLoading(false);return;}setLoading(true);setError(null);try{const r=await getProduct(productId);if(!r.product)throw new Error('Product not found');setP(r.product);void recordCommerceEvent({productId,eventType:'open',clientEventId:`open-${Date.now()}-${Math.random()}`}).catch(()=>{});}catch(e){setError(e instanceof Error?e.message:'Could not load product');}finally{setLoading(false);}},[productId]);
 useEffect(()=>{void load();},[load]);
 const add=async()=>{if(!p||state!=='idle'||p.inventory<1)return;setState('adding');setError(null);try{await addCartItem(p.id,1);void recordCommerceEvent({productId:p.id,eventType:'add_cart',clientEventId:`cart-${Date.now()}-${Math.random()}`}).catch(()=>{});setState('added');}catch(e){setError(e instanceof Error?e.message:'Could not add to cart');setState('idle');}};
 return <AppShell><ScrollView contentContainerStyle={styles.content}>{loading?<View style={styles.center}><ActivityIndicator/><Text style={styles.muted}>Loading product…</Text></View>:error?<View style={styles.alert} accessibilityRole="alert"><Text style={styles.alertTitle}>Product unavailable</Text><Text style={styles.alertBody}>{error}</Text><Pressable accessibilityRole="button" onPress={()=>void load()} style={styles.secondary}><Text style={styles.secondaryText}>Try again</Text></Pressable></View>:p?<><Text style={styles.kicker}>PRODUCT</Text><Text style={styles.title}>{p.title}</Text><Text style={styles.shop}>{p.shop_name}</Text><View style={styles.priceCard}><Text style={styles.price}>{(p.price_minor/100).toFixed(2)} {p.currency}</Text><Text style={styles.inventory}>{p.inventory>0?`${p.inventory} available`:'Currently unavailable'}</Text></View><View style={styles.description}><Text style={styles.heading}>About this product</Text><Text style={styles.body}>{p.description||'No additional description.'}</Text></View><View style={styles.actions}><Pressable accessibilityRole="button" accessibilityLabel={state==='added'?'Added to cart':'Add to cart'} disabled={p.inventory<1||state!=='idle'} accessibilityState={{disabled:p.inventory<1||state!=='idle',busy:state==='adding'}} onPress={()=>void add()} style={[styles.add,(p.inventory<1||state!=='idle')&&styles.disabled]}>{state==='adding'?<ActivityIndicator color={colors.white}/>:<Text style={styles.addText}>{state==='added'?'Added to cart':'Add to cart'}</Text>}</Pressable><Link href="/cart" asChild><Pressable accessibilityRole="button" style={styles.cart}><Text style={styles.cartText}>Open cart</Text></Pressable></Link></View><View style={styles.trust}><Text style={styles.trustKicker}>COMMERCE BOUNDARY</Text><Text style={styles.trustTitle}>No accidental purchase.</Text><Text style={styles.trustBody}>Opening or liking content does not purchase this product. Order and payment remain explicit separate steps.</Text></View></>:null}</ScrollView></AppShell>;
}
const styles=StyleSheet.create({content:{padding:spacing.xl,gap:spacing.lg,maxWidth:760,width:'100%',alignSelf:'center'},center:{minHeight:240,justifyContent:'center',alignItems:'center',gap:8},muted:{color:colors.muted},kicker:{fontSize:type.labelSM,fontWeight:'800',letterSpacing:1.8,color:colors.commerce},title:{fontSize:type.displayXL,lineHeight:44,fontWeight:'800',color:colors.ink},shop:{fontSize:type.bodyMD,color:colors.muted},priceCard:{padding:spacing.xl,borderRadius:radius.hero,backgroundColor:colors.commerceSoft,borderWidth:1,borderColor:'#EBD2BB'},price:{fontSize:type.titleXL,fontWeight:'800',color:colors.ink},inventory:{fontSize:type.bodySM,color:colors.inkSoft,marginTop:6},description:{padding:spacing.lg,borderRadius:radius.lg,borderWidth:1,borderColor:colors.line,backgroundColor:colors.surface},heading:{fontSize:type.titleMD,fontWeight:'800',color:colors.ink},body:{fontSize:type.bodyMD,lineHeight:23,color:colors.inkSoft,marginTop:8},actions:{gap:10},add:{minHeight:50,borderRadius:radius.md,backgroundColor:colors.commerce,alignItems:'center',justifyContent:'center',...elevation.low},disabled:{opacity:.45},addText:{color:colors.white,fontWeight:'800',fontSize:type.bodyMD},cart:{minHeight:48,borderRadius:radius.md,borderWidth:1,borderColor:colors.line,alignItems:'center',justifyContent:'center'},cartText:{color:colors.ink,fontWeight:'800'},alert:{padding:spacing.lg,borderRadius:radius.lg,borderWidth:1,borderColor:colors.danger,backgroundColor:colors.dangerSoft},alertTitle:{fontWeight:'800',color:colors.danger},alertBody:{color:colors.inkSoft,lineHeight:21,marginTop:5},secondary:{marginTop:12,minHeight:44,paddingHorizontal:14,borderRadius:radius.md,borderWidth:1,borderColor:colors.line,alignSelf:'flex-start',justifyContent:'center'},secondaryText:{color:colors.ink,fontWeight:'800'},trust:{padding:spacing.xl,borderRadius:radius.lg,backgroundColor:colors.successSoft,borderWidth:1,borderColor:'#CFE9D9'},trustKicker:{fontSize:type.labelSM,fontWeight:'800',letterSpacing:1.5,color:colors.success},trustTitle:{fontSize:type.titleMD,fontWeight:'800',color:colors.ink,marginTop:4},trustBody:{fontSize:type.bodySM,lineHeight:21,color:colors.inkSoft,marginTop:6}});
