import { useState } from 'react';
import { ActivityIndicator, Image, Pressable, StyleSheet, Text, View } from 'react-native';
import * as ImagePicker from 'expo-image-picker';
import { router } from 'expo-router';
import { api } from '../src/api/client';
import { colors, radius, spacing, type } from '../src/ui/theme';
import { Icon } from '../src/ui/icons';

export default function ProfileSetup(){
 const [uri,setUri]=useState<string|null>(null); const [busy,setBusy]=useState(false); const [error,setError]=useState('');
 const choose=async()=>{setError('');const permission=await ImagePicker.requestMediaLibraryPermissionsAsync();if(!permission.granted){setError('Allow photo access to choose a profile picture.');return;}const result=await ImagePicker.launchImageLibraryAsync({mediaTypes:['images'],allowsEditing:true,aspect:[1,1],quality:.85});if(!result.canceled&&result.assets[0]?.uri)setUri(result.assets[0].uri);};
 const finish=async()=>{setError('');setBusy(true);try{if(uri){const upload=await api<any>('/v1/account/avatar',{method:'POST',body:JSON.stringify({uri})});if(!upload)throw new Error('Could not save profile picture.');}router.replace('/');}catch(e){setError(e instanceof Error?e.message:'Could not finish profile setup.');}finally{setBusy(false);}};
 return <View style={s.screen}><View style={s.wrap}><Pressable accessibilityRole="button" accessibilityLabel="Back" onPress={()=>router.replace('/')} style={s.back}><Icon name="back" size={20} color={colors.ink}/></Pressable><View style={s.hero}><View style={s.avatarWrap}>{uri?<Image source={{uri}} style={s.avatar}/>:<View style={s.avatarEmpty}><Icon name="profile" size={36} color={colors.faint}/></View>}<Pressable accessibilityRole="button" onPress={()=>void choose()} style={s.camera}><Icon name="edit" size={17} color={colors.white}/></Pressable></View><Text style={s.kicker}>PROFILE</Text><Text style={s.title}>Add a profile picture</Text><Text style={s.body}>Optional. You can skip this now and add one later from your profile.</Text>{error?<View style={s.error}><Icon name="circleAlert" size={17} color={colors.danger}/><Text style={s.errorText}>{error}</Text></View>:null}<Pressable disabled={busy} accessibilityRole="button" onPress={()=>void finish()} style={[s.primary,busy&&s.disabled]}>{busy?<ActivityIndicator color={colors.white}/>:<Text style={s.primaryText}>{uri?'Continue':'Skip for now'}</Text>}</Pressable>{uri?<Pressable disabled={busy} accessibilityRole="button" onPress={()=>{setUri(null)}} style={s.skip}><Text style={s.skipText}>Remove picture</Text></Pressable>:null}</View></View></View>
}
const s=StyleSheet.create({screen:{flex:1,backgroundColor:colors.canvas},wrap:{width:'100%',maxWidth:560,alignSelf:'center',flex:1,padding:spacing.xl,justifyContent:'center'},back:{width:44,height:44,borderRadius:radius.md,borderWidth:1,borderColor:colors.line,backgroundColor:colors.surface,alignItems:'center',justifyContent:'center',marginBottom:spacing.huge},hero:{alignItems:'center'},avatarWrap:{position:'relative',marginBottom:spacing.xl},avatar:{width:128,height:128,borderRadius:64},avatarEmpty:{width:128,height:128,borderRadius:64,borderWidth:1,borderColor:colors.line,backgroundColor:colors.surface,alignItems:'center',justifyContent:'center'},camera:{position:'absolute',right:2,bottom:2,width:38,height:38,borderRadius:19,backgroundColor:colors.brand,alignItems:'center',justifyContent:'center',borderWidth:3,borderColor:colors.canvas},kicker:{fontSize:type.labelSM,fontWeight:'900',letterSpacing:1.8,color:colors.brand},title:{fontSize:type.displayLG,lineHeight:40,fontWeight:'900',letterSpacing:-1,color:colors.ink,marginTop:6,textAlign:'center'},body:{fontSize:type.bodyMD,lineHeight:22,color:colors.muted,maxWidth:430,textAlign:'center',marginTop:10},error:{width:'100%',minHeight:42,padding:12,borderRadius:radius.md,backgroundColor:colors.dangerSoft,flexDirection:'row',gap:8,alignItems:'center',marginTop:18},errorText:{flex:1,color:colors.danger,fontSize:12.5,lineHeight:17},primary:{width:'100%',height:54,borderRadius:radius.pill,backgroundColor:colors.brand,alignItems:'center',justifyContent:'center',marginTop:22},primaryText:{color:colors.white,fontSize:15,fontWeight:'900'},disabled:{opacity:.55},skip:{minHeight:44,paddingVertical:12,alignItems:'center',justifyContent:'center'},skipText:{fontSize:13,fontWeight:'800',color:colors.brand}});
