import { ScrollView, StyleSheet, Text, View, Pressable } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { Link } from 'expo-router';

export default function Profile() {
  return <SafeAreaView style={styles.safe}><ScrollView contentInsetAdjustmentBehavior="automatic" contentContainerStyle={styles.content}><View style={styles.avatar}><Text style={styles.avatarText}>R</Text></View><Text style={styles.name}>Your profile</Text><Text style={styles.handle}>@drustpoll_user</Text><Text style={styles.bio}>Posts, reels, people and a storefront—one identity.</Text><View style={styles.stats}><Stat n="0" l="Posts"/><Stat n="0" l="Followers"/><Stat n="0" l="Following"/></View><Link href="/shop" asChild><Pressable style={styles.shop}><Text style={styles.shopTitle}>Open Shop</Text><Text style={styles.shopBody}>Products, collections, orders and seller tools</Text><Text style={styles.arrow}>→</Text></Pressable></Link><View style={styles.tabs}><Text style={styles.active}>Posts</Text><Text>Reels</Text><Text>Shop</Text></View></ScrollView></SafeAreaView>;
}
function Stat({n,l}:{n:string;l:string}){return <View><Text style={styles.statN}>{n}</Text><Text style={styles.statL}>{l}</Text></View>}
const styles=StyleSheet.create({safe:{flex:1,backgroundColor:'#F6F7F9'},content:{padding:20,gap:10},avatar:{width:86,height:86,borderRadius:43,backgroundColor:'#111827',alignItems:'center',justifyContent:'center'},avatarText:{fontSize:32,fontWeight:'800',color:'#fff'},name:{fontSize:27,fontWeight:'800',color:'#101828',marginTop:5},handle:{color:'#667085'},bio:{fontSize:15,lineHeight:21,color:'#475467',maxWidth:420},stats:{flexDirection:'row',gap:34,paddingVertical:18},statN:{fontSize:19,fontWeight:'800',color:'#101828'},statL:{fontSize:12,color:'#667085'},shop:{backgroundColor:'#E8F0FF',borderRadius:24,padding:20,position:'relative',minHeight:120},shopTitle:{fontSize:20,fontWeight:'800',color:'#101828'},shopBody:{fontSize:13,color:'#475467',marginTop:6,maxWidth:310},arrow:{position:'absolute',right:20,bottom:18,fontSize:24},tabs:{flexDirection:'row',justifyContent:'space-around',paddingVertical:18,marginTop:8},active:{fontWeight:'800'}});
