import { useCallback, useEffect, useState } from 'react';
import { ActivityIndicator, Pressable, ScrollView, StyleSheet, Text, View, Image } from 'react-native';
import { Link, useLocalSearchParams } from 'expo-router';
import { AppShell } from '../src/ui/AppShell';
import { colors, radius, spacing, type } from '../src/ui/theme';
import { getFollowers, getFollowing, getMutualContext } from '../src/api/client';
import { Icon } from '../src/ui/icons';

type Mode='followers'|'following'|'mutuals';
export default function ProfileList(){const params=useLocalSearchParams<{id?:string;mode?:string}>();const userId=Array.isArray(params.id)?params.id[0]:params.id;const mode=(Array.isArray(params.mode)?params.mode[0]:params.mode) as Mode||'followers';const[items,setItems]=useState<any[]>([]);const[loading,setLoading]=useState(true);const[error,setError]=useState<string|null>(null);const load=useCallback(async()=>{if(!userId){setError('Profile is unavailable');setLoading(false);return;}setLoading(true);setError(null);try{if(mode==='followers')setItems((await getFollowers(userId)).people);else if(mode==='following')setItems((await getFollowing(userId)).people);else setItems((await getMutualContext(userId)).people);}catch(e){setError(e instanceof Error?e.message:'Could not load people');}finally{setLoading(false);}},[mode,userId]);useEffect(()=>{void load();},[load]);return <AppShell><ScrollView contentContainerStyle={styles.content}><View style={styles.header}><View><Text style={styles.kicker}>PEOPLE</Text><Text style={styles.title}>{mode==='followers'?'Followers':mode==='following'?'Following':'Mutual connections'}</Text></View><Link href={{pathname:'/profile',params:{id:userId}}} asChild><Pressable accessibilityRole="button" style={styles.back}><Icon name="back" size={19} color={colors.ink}/></Pressable></Link></View>{loading?<View style={styles.center}><ActivityIndicator/><Text style={styles.muted}>Loading people…</Text></View>:error?<View accessibilityRole="alert" style={styles.error}><Text style={styles.errorTitle}>Could not load this list</Text><Text style={styles.errorBody}>{error}</Text><Pressable accessibilityRole="button" onPress={()=>void load()} style={styles.retry}><Text style={styles.retryText}>Try again</Text></Pressable></View>:items.length?items.map(person=><Link key={person.id} href={{pathname:'/profile',params:{id:person.id}}} asChild><Pressable accessibilityRole="button" style={styles.person}><View style={styles.avatar}>{person.avatar_url?<Image source={{uri:person.avatar_url}} style={styles.avatarImage}/>:<Text style={styles.avatarText}>{String(person.display_name||person.username||'D').slice(0,1).toUpperCase()}</Text>}</View><View style={styles.copy}><Text style={styles.name}>{person.display_name||person.username}</Text><Text style={styles.handle}>@{person.username}</Text></View><Icon name="chevronRight" size={19} color={colors.faint}/></Pressable></Link>):<View style={styles.empty}><Icon name="profile" size={28} color={colors.faint}/><Text style={styles.emptyTitle}>Nothing to show yet</Text><Text style={styles.muted}>This list will fill as connections are made.</Text></View>}</ScrollView></AppShell>}
const styles=StyleSheet.create({content:{padding:spacing.xl,gap:12,maxWidth:720,width:'100%',alignSelf:'center'},header:{flexDirection:'row',justifyContent:'space-between',alignItems:'center'},kicker:{fontSize:type.labelSM,fontWeight:'800',letterSpacing:1.7,color:colors.brand},title:{fontSize:type.displayLG,fontWeight:'900',color:colors.ink},back:{width:44,height:44,borderRadius:radius.md,borderWidth:1,borderColor:colors.line,alignItems:'center',justifyContent:'center',backgroundColor:colors.surface},center:{minHeight:220,alignItems:'center',justifyContent:'center',gap:8},muted:{fontSize:type.bodySM,color:colors.muted,lineHeight:21},error:{padding:spacing.lg,borderRadius:radius.lg,backgroundColor:colors.dangerSoft,borderWidth:1,borderColor:colors.danger},errorTitle:{fontWeight:'800',color:colors.danger},errorBody:{marginTop:4,color:colors.inkSoft},retry:{marginTop:12,minHeight:44,paddingHorizontal:14,borderRadius:radius.md,backgroundColor:colors.brand,justifyContent:'center',alignSelf:'flex-start'},retryText:{color:colors.white,fontWeight:'800'},person:{minHeight:72,padding:spacing.md,borderWidth:1,borderColor:colors.line,borderRadius:radius.lg,backgroundColor:colors.surface,flexDirection:'row',alignItems:'center',gap:11},avatar:{width:48,height:48,borderRadius:24,backgroundColor:colors.brand,alignItems:'center',justifyContent:'center',overflow:'hidden'},avatarImage:{width:48,height:48},avatarText:{color:colors.white,fontWeight:'800',fontSize:18},copy:{flex:1},name:{fontWeight:'800',color:colors.ink},handle:{fontSize:type.labelSM,color:colors.muted,marginTop:2},empty:{padding:spacing.xxl,alignItems:'center',borderWidth:1,borderColor:colors.line,borderRadius:radius.lg,backgroundColor:colors.surface,gap:7},emptyTitle:{fontSize:type.titleMD,fontWeight:'800',color:colors.ink}});