import { useCallback, useEffect, useRef, useState } from 'react';
import { FlatList, Pressable, Share, StyleSheet, Text, View, useWindowDimensions } from 'react-native';
import { useVideoPlayer, VideoView } from 'expo-video';
import { AppShell } from '../src/ui/AppShell';
import { colors, elevation, radius, spacing, type } from '../src/ui/theme';
import { getReels, startReelWatchSession, endReelWatchSession } from '../src/api/client';
import { enqueueReelEvents, flushReelEvents, type QueuedReelEvent } from '../src/reels/event-queue';

type Reel=Awaited<ReturnType<typeof getReels>>['items'][number];
const id=()=>`${Date.now()}-${Math.random().toString(36).slice(2)}-${Math.random().toString(36).slice(2)}`;

function ReelVideo({item,active,onEvent}:{item:Reel;active:boolean;onEvent:(event:QueuedReelEvent)=>void}){
 const player=useVideoPlayer(item.videoUrl,p=>{p.muted=true;});const started=useRef(false);const lastSecond=useRef(-1);const completed=useRef(false);
 useEffect(()=>{if(active){player.play();if(!started.current){started.current=true;completed.current=false;onEvent({postId:item.id,eventType:'impression',clientEventId:id()});onEvent({postId:item.id,eventType:'start',clientEventId:id()});}}else{if(started.current&&!completed.current&&player.duration>0&&player.currentTime/player.duration<.9)onEvent({postId:item.id,eventType:'skip',position:Math.floor(player.currentTime),watchedMs:Math.floor(player.currentTime*1000),videoDurationMs:Math.floor(player.duration*1000),clientEventId:id()});player.pause();}},[active,item.id,onEvent,player]);
 useEffect(()=>{if(!active)return;const timer=setInterval(()=>{const current=player.currentTime;const duration=player.duration;if(duration>0&&current>=duration-.5&&!completed.current){completed.current=true;onEvent({postId:item.id,eventType:'complete',position:Math.floor(duration),watchedMs:Math.floor(duration*1000),videoDurationMs:Math.floor(duration*1000),clientEventId:id()});}const second=Math.floor(current);if(second!==lastSecond.current&&second%2===0){lastSecond.current=second;onEvent({postId:item.id,eventType:'progress',position:second,watchedMs:Math.floor(current*1000),videoDurationMs:Math.floor(Math.max(0,duration)*1000),clientEventId:id()});}},1000);return()=>clearInterval(timer);},[active,item.id,onEvent,player]);
 return <VideoView style={styles.video} player={player} contentFit="cover" allowsFullscreen allowsPictureInPicture nativeControls={false}/>;
}

export default function Reels(){
 const{height}=useWindowDimensions();const[items,setItems]=useState<Reel[]>([]);const[active,setActive]=useState(0);const[session,setSession]=useState<string|null>(null);const[error,setError]=useState<string|null>(null);const[loading,setLoading]=useState(true);const[liked,setLiked]=useState<Set<string>>(new Set());const[saved,setSaved]=useState<Set<string>>(new Set());
 const queue=useRef<QueuedReelEvent[]>([]);
 const flush=useCallback(async()=>{if(!session)return;if(queue.current.length){const pending=queue.current.splice(0);await enqueueReelEvents(pending);}await flushReelEvents(session);},[session]);
 const load=useCallback(async()=>{setLoading(true);setError(null);setActive(0);try{const[r,s]=await Promise.all([getReels(),startReelWatchSession(id())]);setItems(r.items??[]);setSession(s.sessionId);}catch(e){setItems([]);setSession(null);setError(e instanceof Error?e.message:'Could not load Reels');}finally{setLoading(false);}},[]);
 useEffect(()=>{void load();},[load]);
 useEffect(()=>{if(!session)return;const timer=setInterval(()=>void flush(),5000);return()=>clearInterval(timer);},[session,flush]);
 useEffect(()=>()=>{if(session)void(async()=>{await flush();await endReelWatchSession(session);})();},[session,flush]);
 const push=(event:QueuedReelEvent)=>{queue.current.push(event);};
 const activeItem=items[active];
 const reactTo=async(type:'like'|'save')=>{if(!activeItem)return;const was=type==='like'?liked.has(activeItem.id):saved.has(activeItem.id);if(was)return;push({postId:activeItem.id,eventType:type,clientEventId:id()});if(type==='like')setLiked(prev=>new Set(prev).add(activeItem.id));else setSaved(prev=>new Set(prev).add(activeItem.id));await flush();};
 const share=async()=>{if(!activeItem)return;try{await Share.share({message:activeItem.videoUrl});push({postId:activeItem.id,eventType:'share',clientEventId:id()});await flush();}catch{ /* user cancellation or unavailable share surface: do not record a share */ }};
 if(loading)return <AppShell><View style={styles.center}><Text style={styles.state}>Finding something interesting…</Text><Text style={styles.substate}>Balancing relevance, variety and creator diversity.</Text></View></AppShell>;
 if(error)return <AppShell><View style={styles.center}><Text style={styles.state}>Reels could not load.</Text><Text style={styles.substate}>{error}</Text><Pressable accessibilityRole="button" accessibilityLabel="Retry loading Reels" onPress={()=>void load()} style={styles.retry}><Text style={styles.retryText}>Try again</Text></Pressable></View></AppShell>;
 if(!items.length)return <AppShell><View style={styles.center}><Text style={styles.state}>Nothing ready yet.</Text><Text style={styles.substate}>There are no eligible videos to show right now.</Text><Pressable accessibilityRole="button" onPress={()=>void load()} style={styles.retry}><Text style={styles.retryText}>Refresh</Text></Pressable></View></AppShell>;
 return <AppShell><FlatList data={items} pagingEnabled keyExtractor={x=>x.id} showsVerticalScrollIndicator={false} onMomentumScrollEnd={e=>setActive(Math.round(e.nativeEvent.contentOffset.y/Math.max(height,1)))} renderItem={({item,index})=><View style={[styles.page,{height:Math.max(height,560)}]}>{Math.abs(index-active)<=1?<ReelVideo item={item} active={index===active} onEvent={push}/>:null}<View style={styles.scrim}/><View style={styles.overlay}><View style={styles.topRow}><Text style={styles.badge}>{item.reason.replaceAll('_',' ')}</Text><Pressable accessibilityRole="button" accessibilityLabel="More video actions" accessibilityState={{disabled:true}} disabled hitSlop={12}><Text style={styles.more}>•••</Text></Pressable></View><Text style={styles.title}>{item.display_name||item.username}</Text><Text style={styles.meta}>{item.likes} likes · {item.comments} comments</Text><View style={styles.actions}>
  <Pressable accessibilityRole="button" accessibilityLabel={liked.has(item.id)?'Unlike video':'Like video'} accessibilityState={{selected:liked.has(item.id)}} onPress={()=>void reactTo('like')} style={[styles.action,liked.has(item.id)&&styles.actionSelected]}><Text style={styles.actionIcon}>{liked.has(item.id)?'♥':'♡'}</Text><Text style={styles.actionLabel}>{liked.has(item.id)?'Liked':'Like'}</Text></Pressable>
  <Pressable accessibilityRole="button" accessibilityLabel={saved.has(item.id)?'Unsave video':'Save video'} accessibilityState={{selected:saved.has(item.id)}} onPress={()=>void reactTo('save')} style={[styles.action,saved.has(item.id)&&styles.actionSelected]}><Text style={styles.actionIcon}>{saved.has(item.id)?'◆':'◇'}</Text><Text style={styles.actionLabel}>{saved.has(item.id)?'Saved':'Save'}</Text></Pressable>
  <Pressable accessibilityRole="button" accessibilityLabel="Share video" onPress={()=>void share()} style={styles.action}><Text style={styles.actionIcon}>↗</Text><Text style={styles.actionLabel}>Share</Text></Pressable>
 </View></View></View>}/></AppShell>;
}
const styles=StyleSheet.create({page:{backgroundColor:'#0B0C0B',position:'relative'},video:{...StyleSheet.absoluteFillObject},scrim:{...StyleSheet.absoluteFillObject,backgroundColor:'rgba(0,0,0,.16)'},overlay:{position:'absolute',left:spacing.xl,right:spacing.xl,bottom:spacing.xl,gap:9},topRow:{flexDirection:'row',justifyContent:'space-between',alignItems:'center'},badge:{alignSelf:'flex-start',paddingHorizontal:11,paddingVertical:7,borderRadius:radius.pill,backgroundColor:'rgba(255,255,255,.18)',color:colors.white,fontSize:type.labelSM,fontWeight:'800',textTransform:'uppercase'},more:{fontSize:20,color:colors.white,letterSpacing:1},title:{fontSize:type.titleXL,fontWeight:'800',color:colors.white},meta:{fontSize:type.bodySM,color:'#E4E7E5'},actions:{flexDirection:'row',gap:10,marginTop:2},action:{minHeight:44,paddingHorizontal:13,borderRadius:radius.pill,backgroundColor:'rgba(0,0,0,.42)',flexDirection:'row',alignItems:'center',gap:6},actionSelected:{backgroundColor:'rgba(255,255,255,.28)'},actionIcon:{fontSize:18,color:colors.white},actionLabel:{fontSize:type.labelSM,color:colors.white,fontWeight:'700'},center:{flex:1,justifyContent:'center',alignItems:'center',padding:spacing.xl,backgroundColor:colors.canvas},state:{color:colors.ink,fontSize:type.titleMD,fontWeight:'800',textAlign:'center'},substate:{color:colors.muted,fontSize:type.bodySM,marginTop:6,textAlign:'center',maxWidth:380},retry:{marginTop:14,backgroundColor:colors.brand,paddingHorizontal:16,paddingVertical:11,borderRadius:radius.md,minHeight:44,justifyContent:'center',...elevation.low},retryText:{color:colors.white,fontWeight:'800'}});
