import {useCallback,useEffect,useState} from 'react';
import {ActivityIndicator,Alert,Pressable,ScrollView,StyleSheet,Text,View} from 'react-native';
import {Link} from 'expo-router';
import {getSecurityAlerts,getSecurityEvents,secureAccount,api} from '../src/api/client';
import {AppShell} from '../src/ui/AppShell';
import {Icon} from '../src/ui/icons';
import {colors,elevation,radius,spacing,type} from '../src/ui/theme';

type Session={id:string;label?:string;current?:boolean;revoked?:boolean;lastSeenAt?:string|null;expiresAt?:string|null};
export default function Security(){
 const[sessions,setSessions]=useState<Session[]>([]);const[alerts,setAlerts]=useState<any[]>([]);const[events,setEvents]=useState<any[]>([]);const[loading,setLoading]=useState(true);const[busy,setBusy]=useState<string|null>(null);const[error,setError]=useState<string|null>(null);
 const load=useCallback(async()=>{setLoading(true);setError(null);try{const[s,a,e]=await Promise.all([api<{sessions:Session[]}>('/v1/auth/sessions'),getSecurityAlerts(),getSecurityEvents()]);setSessions(s.sessions??[]);setAlerts(a.alerts??[]);setEvents(e.events??[]);}catch(e){setError(e instanceof Error?e.message:'Security center unavailable');}finally{setLoading(false);}},[]);useEffect(()=>{void load();},[load]);
 const revokeOne=async(id:string)=>{setBusy(id);try{await api(`/v1/auth/sessions/${encodeURIComponent(id)}/revoke`,{method:'POST'});await load();}catch(e){setError(e instanceof Error?e.message:'Could not revoke session');}finally{setBusy(null);}};
 const revokeAll=async()=>{setBusy('all');try{await api('/v1/auth/sessions/revoke-all',{method:'POST'});await load();}catch(e){setError(e instanceof Error?e.message:'Could not revoke sessions');}finally{setBusy(null);}};
 const ack=async(id:string)=>{setBusy(`a-${id}`);try{await api(`/v1/security/alerts/${encodeURIComponent(id)}/ack`,{method:'POST'});await load();}catch(e){setError(e instanceof Error?e.message:'Could not acknowledge alert');}finally{setBusy(null);}};
 const secure=()=>Alert.alert('Secure account','Revoke active sessions and acknowledge current security alerts?', [{text:'Cancel',style:'cancel'},{text:'Secure account',style:'destructive',onPress:async()=>{setBusy('secure');try{await secureAccount();Alert.alert('Account secured','Sessions were revoked. Sign in again from a trusted device.');}catch(e){setError(e instanceof Error?e.message:'Could not secure account');}finally{setBusy(null);}}}]);
 if(loading)return <AppShell><View style={s.center}><ActivityIndicator/><Text style={s.muted}>Opening Security Center…</Text></View></AppShell>;
 return <AppShell><ScrollView contentContainerStyle={s.content}><Link href="/settings" asChild><Pressable style={s.back}><Icon name="back" size={18} color={colors.brand}/><Text style={s.backText}>Settings</Text></Pressable></Link><Text style={s.kicker}>SECURITY CENTER</Text><Text style={s.title}>Know what your account is doing.</Text><Text style={s.subtitle}>Sessions, alerts, security events and recovery are intentionally visible and reversible where technically possible.</Text>{error?<View style={s.alert}><Icon name="circleAlert" size={18} color={colors.danger}/><Text style={s.error}>{error}</Text><Pressable onPress={()=>void load()}><Icon name="refresh" size={18} color={colors.danger}/></Pressable></View>:null}
 <View style={s.card}><Text style={s.heading}>Account protection</Text><Text style={s.meta}>For suspected compromise, revoke sessions and start again from a trusted sign-in path.</Text><Pressable disabled={!!busy} onPress={secure} style={s.secure}><Icon name="shield" size={18} color={colors.brand}/><Text style={s.secureText}>{busy==='secure'?'Securing…':'Secure account'}</Text></Pressable></View>
 <View style={s.card}><Text style={s.heading}>Security alerts</Text>{alerts.map(x=><View key={x.id} style={s.row}><Icon name="circleAlert" size={18} color={x.severity==='critical'?colors.danger:colors.warning}/><View style={s.flex}><Text style={s.name}>{x.event_type}</Text><Text style={s.meta}>{x.message}</Text><Text style={s.meta}>{new Date(x.created_at).toLocaleString()}</Text></View>{x.acknowledged_at?<Text style={s.seen}>Seen</Text>:<Pressable disabled={!!busy} onPress={()=>void ack(x.id)} style={s.revoke}>{busy===`a-${x.id}`?<ActivityIndicator/>:<Text style={s.revokeText}>Acknowledge</Text>}</Pressable>}</View>)}{!alerts.length?<Text style={s.muted}>No active security alerts.</Text>:null}</View>
 <View style={s.card}><Text style={s.heading}>Sessions</Text><Text style={s.meta}>Every session has an explicit revoke path. The current device is marked rather than hidden.</Text><Pressable disabled={!!busy} onPress={()=>Alert.alert('Revoke all sessions?','You will need to sign in again.',[{text:'Cancel',style:'cancel'},{text:'Revoke all',style:'destructive',onPress:()=>void revokeAll()}])} style={s.danger}>{busy==='all'?<ActivityIndicator color={colors.white}/>:<Text style={s.dangerText}>Revoke all sessions</Text>}</Pressable><View style={s.list}>{sessions.map(x=><View key={x.id} style={s.session}><Icon name={x.current?'phone':'package'} size={18} color={colors.brand}/><View style={s.flex}><Text style={s.name}>{x.label||'Session'}{x.current?' · This device':''}</Text><Text style={s.meta}>{x.lastSeenAt?`Last seen ${new Date(x.lastSeenAt).toLocaleString()}`:'Last seen unavailable'}</Text><Text style={s.meta}>{x.revoked?'Revoked':'Active'}{x.expiresAt?` · expires ${new Date(x.expiresAt).toLocaleString()}`:''}</Text></View>{!x.revoked&&!x.current?<Pressable disabled={!!busy} onPress={()=>void revokeOne(x.id)} style={s.revoke}>{busy===x.id?<ActivityIndicator/>:<Text style={s.revokeText}>Revoke</Text>}</Pressable>:null}</View>)}</View></View>
 <View style={s.card}><Text style={s.heading}>Security event history</Text>{events.slice(0,50).map(x=><View key={x.id} style={s.event}><Icon name="clock" size={16} color={colors.muted}/><View style={s.flex}><Text style={s.name}>{x.event_type}</Text><Text style={s.meta}>{x.resource_type}{x.resource_id?` · ${String(x.resource_id).slice(0,12)}`:''} · {new Date(x.created_at).toLocaleString()}</Text></View></View>)}{!events.length?<Text style={s.muted}>No security events recorded yet.</Text>:null}</View>
 <View style={s.card}><Text style={s.heading}>Future-facing authentication</Text><Text style={s.meta}>Passkeys and stronger authenticators belong to this surface. The UI does not pretend a passkey is enrolled until a real WebAuthn ceremony is wired and verified.</Text><View style={s.future}><Icon name="lock" size={18} color={colors.brand}/><View style={s.flex}><Text style={s.name}>Passkeys</Text><Text style={s.meta}>Provider ceremony boundary reserved; no false enrollment state.</Text></View><Icon name="chevronRight" size={17} color={colors.muted}/></View><View style={s.future}><Icon name="shield" size={18} color={colors.brand}/><View style={s.flex}><Text style={s.name}>Password & recovery</Text><Text style={s.meta}>Use the existing secure reset flow; add re-authentication before destructive controls.</Text></View></View></View>
 <View style={s.note}><Icon name="shield" size={18} color={colors.success}/><View style={s.flex}><Text style={s.name}>Privacy and security are not engagement levers.</Text><Text style={s.meta}>No dark-pattern countdowns, fake urgency, or hidden defaults.</Text></View></View>
 </ScrollView></AppShell>}
const s=StyleSheet.create({content:{padding:spacing.xl,gap:spacing.lg,maxWidth:900,width:'100%',alignSelf:'center'},back:{minHeight:42,flexDirection:'row',alignItems:'center',gap:7},backText:{color:colors.brand,fontWeight:'900'},kicker:{fontSize:type.labelSM,fontWeight:'900',letterSpacing:1.8,color:colors.brand},title:{fontSize:type.displayLG,lineHeight:40,fontWeight:'900',color:colors.ink},subtitle:{fontSize:type.bodyMD,lineHeight:22,color:colors.muted},alert:{padding:spacing.md,borderRadius:radius.md,backgroundColor:colors.dangerSoft,flexDirection:'row',alignItems:'center',gap:8},error:{color:colors.danger,flex:1},center:{minHeight:250,alignItems:'center',justifyContent:'center',gap:8},muted:{color:colors.muted},card:{backgroundColor:colors.surface,borderWidth:1,borderColor:colors.line,borderRadius:radius.xl,padding:spacing.lg,...elevation.low},heading:{fontSize:type.titleLG,fontWeight:'900',color:colors.ink},meta:{fontSize:type.bodySM,color:colors.muted,lineHeight:20,marginTop:4},secure:{minHeight:48,marginTop:14,borderWidth:1,borderColor:colors.brand,borderRadius:radius.md,flexDirection:'row',alignItems:'center',justifyContent:'center',gap:7},secureText:{color:colors.brand,fontWeight:'900'},row:{minHeight:78,paddingVertical:11,borderTopWidth:1,borderTopColor:colors.line,flexDirection:'row',alignItems:'center',gap:9},flex:{flex:1},name:{fontSize:type.bodyMD,fontWeight:'800',color:colors.ink},seen:{fontSize:type.labelSM,fontWeight:'900',color:colors.success},revoke:{minHeight:40,paddingHorizontal:11,borderRadius:radius.md,borderWidth:1,borderColor:colors.line,justifyContent:'center'},revokeText:{fontWeight:'900',color:colors.danger},danger:{marginTop:12,minHeight:46,paddingHorizontal:13,borderRadius:radius.md,backgroundColor:colors.danger,alignItems:'center',justifyContent:'center',alignSelf:'flex-start'},dangerText:{color:colors.white,fontWeight:'900'},list:{marginTop:10,borderWidth:1,borderColor:colors.line,borderRadius:radius.lg,overflow:'hidden'},session:{minHeight:82,padding:spacing.md,flexDirection:'row',alignItems:'center',gap:9,borderBottomWidth:1,borderBottomColor:colors.line},event:{minHeight:58,paddingVertical:10,borderTopWidth:1,borderTopColor:colors.line,flexDirection:'row',gap:8,alignItems:'center'},future:{minHeight:64,paddingVertical:10,borderTopWidth:1,borderTopColor:colors.line,flexDirection:'row',alignItems:'center',gap:9},note:{padding:spacing.lg,borderRadius:radius.xl,backgroundColor:colors.successSoft,flexDirection:'row',alignItems:'center',gap:9}});
