import { useCallback,useEffect,useState } from 'react';
import { ActivityIndicator,Pressable,ScrollView,StyleSheet,Text,TextInput,View } from 'react-native';
import { Link } from 'expo-router';
import { AppShell } from '../src/ui/AppShell';
import { createSellerProduct,getSellerProducts,type SellerProduct } from '../src/api/client';
import { colors,radius,spacing,type } from '../src/ui/theme';

export default function Seller(){
 const[products,setProducts]=useState<SellerProduct[]>([]);const[loading,setLoading]=useState(true);const[error,setError]=useState<string|null>(null);const[title,setTitle]=useState('');const[description,setDescription]=useState('');const[price,setPrice]=useState('');const[inventory,setInventory]=useState('');const[category,setCategory]=useState('');const[busy,setBusy]=useState(false);const[success,setSuccess]=useState(false);
 const load=useCallback(async()=>{setLoading(true);setError(null);try{setProducts((await getSellerProducts()).products??[]);}catch(e){setError(e instanceof Error?e.message:'Could not load catalogue');}finally{setLoading(false);}},[]);useEffect(()=>{void load();},[load]);
 const create=async()=>{if(busy)return;const priceMinor=Math.round(Number(price)*100),stock=Number(inventory);if(!title.trim())return setError('Add a product title.');if(!Number.isSafeInteger(priceMinor)||priceMinor<0)return setError('Enter a valid price.');if(!Number.isSafeInteger(stock)||stock<0)return setError('Enter a valid inventory count.');setBusy(true);setError(null);setSuccess(false);try{await createSellerProduct({title:title.trim(),description:description.trim(),priceMinor,inventory:stock,category:category.trim()||undefined});setTitle('');setDescription('');setPrice('');setInventory('');setCategory('');setSuccess(true);await load();}catch(e){setError(e instanceof Error?e.message:'Could not create product');}finally{setBusy(false);}};
 return <AppShell><ScrollView contentContainerStyle={styles.content}><Text style={styles.kicker}>MARKET / SELLER</Text><Text style={styles.title}>Your storefront.</Text><Text style={styles.subtitle}>Create products with explicit price, stock and category. Nothing implies a sale until the server accepts the product.</Text>{error?<View accessibilityRole="alert" style={styles.alert}><Text style={styles.alertTitle}>Catalogue needs attention</Text><Text style={styles.alertBody}>{error}</Text></View>:null}{success?<View style={styles.success}><Text style={styles.successTitle}>Product created.</Text><Text style={styles.successBody}>Your catalogue is updated from the server.</Text></View>:null}
 <View style={styles.form}><Text style={styles.heading}>New product</Text><Field label="Title" value={title} onChangeText={setTitle} placeholder="What are you selling?"/><Field label="Description" value={description} onChangeText={setDescription} placeholder="Useful product details" multiline/><View style={styles.row}><View style={styles.half}><Field label="Price" value={price} onChangeText={setPrice} placeholder="0.00" keyboardType="decimal-pad"/></View><View style={styles.half}><Field label="Inventory" value={inventory} onChangeText={setInventory} placeholder="0" keyboardType="number-pad"/></View></View><Field label="Category" value={category} onChangeText={setCategory} placeholder="e.g. clothing"/><Pressable accessibilityRole="button" accessibilityState={{disabled:busy}} disabled={busy} onPress={()=>void create()} style={[styles.primary,busy&&styles.disabled]}>{busy?<ActivityIndicator color={colors.white}/>:<Text style={styles.primaryText}>Publish product</Text>}</Pressable></View>
 <View style={styles.header}><Text style={styles.heading}>Catalogue</Text><Link href="/shop" asChild><Pressable accessibilityRole="button" style={styles.link}><Text style={styles.linkText}>View shop</Text></Pressable></Link></View>{loading?<View style={styles.center}><ActivityIndicator/><Text style={styles.muted}>Loading catalogue…</Text></View>:<View style={styles.list}>{products.length?products.map(p=><View key={p.id} style={styles.product}><View style={styles.copy}><Text style={styles.productTitle}>{p.title}</Text><Text style={styles.meta}>{p.category||'Uncategorised'} · {p.inventory} in stock · {p.status}</Text></View><Text style={styles.priceText}>{(p.price_minor/100).toFixed(2)} {p.currency}</Text></View>):<View style={styles.empty}><Text style={styles.emptyTitle}>No products yet.</Text><Text style={styles.emptyBody}>Start with one clear product and let the catalogue grow from there.</Text></View>}</View>}
 <View style={styles.note}><Text style={styles.noteKicker}>COMMERCE PRINCIPLE</Text><Text style={styles.noteTitle}>Confidence before conversion.</Text><Text style={styles.noteBody}>Seller identity, price, availability and payment state remain explicit. The interface never manufactures urgency or fake demand.</Text></View></ScrollView></AppShell>;
}
function Field({label,value,onChangeText,placeholder,multiline=false,keyboardType='default'}:{label:string;value:string;onChangeText:(v:string)=>void;placeholder:string;multiline?:boolean;keyboardType?:'default'|'decimal-pad'|'number-pad'}){return <View style={styles.field}><Text style={styles.label}>{label}</Text><TextInput accessibilityLabel={label} value={value} onChangeText={onChangeText} placeholder={placeholder} placeholderTextColor={colors.faint} multiline={multiline} keyboardType={keyboardType} maxLength={multiline?10000:200} style={[styles.input,multiline&&styles.textarea]}/></View>}
const styles=StyleSheet.create({content:{padding:spacing.xl,gap:spacing.lg,maxWidth:760,width:'100%',alignSelf:'center'},kicker:{fontSize:type.labelSM,fontWeight:'800',letterSpacing:1.7,color:colors.commerce},title:{fontSize:type.displayLG,lineHeight:38,fontWeight:'800',color:colors.ink},subtitle:{fontSize:type.bodySM,lineHeight:21,color:colors.muted},alert:{padding:spacing.lg,borderWidth:1,borderColor:colors.danger,borderRadius:radius.lg,backgroundColor:colors.dangerSoft},alertTitle:{fontWeight:'800',color:colors.danger},alertBody:{color:colors.inkSoft,marginTop:4},success:{padding:spacing.lg,borderRadius:radius.lg,backgroundColor:colors.successSoft,borderWidth:1,borderColor:'#CFE9D9'},successTitle:{fontWeight:'800',color:colors.ink},successBody:{fontSize:type.bodySM,color:colors.inkSoft,marginTop:4},form:{padding:spacing.xl,borderWidth:1,borderColor:colors.line,borderRadius:radius.hero,backgroundColor:colors.surface},heading:{fontSize:type.titleMD,fontWeight:'800',color:colors.ink},field:{gap:6,marginTop:14},label:{fontSize:type.labelMD,fontWeight:'800',color:colors.ink},input:{minHeight:48,borderWidth:1,borderColor:colors.line,borderRadius:radius.md,paddingHorizontal:14,color:colors.ink,fontSize:type.bodyMD,backgroundColor:colors.canvas},textarea:{minHeight:110,paddingTop:12,textAlignVertical:'top'},row:{flexDirection:'row',gap:12},half:{flex:1},primary:{marginTop:18,minHeight:50,borderRadius:radius.md,backgroundColor:colors.commerce,alignItems:'center',justifyContent:'center'},primaryText:{color:colors.white,fontWeight:'800',fontSize:type.bodyMD},disabled:{opacity:.5},header:{flexDirection:'row',alignItems:'center',justifyContent:'space-between'},link:{minHeight:44,justifyContent:'center',paddingHorizontal:12},linkText:{color:colors.commerce,fontWeight:'800'},center:{minHeight:140,alignItems:'center',justifyContent:'center',gap:8},muted:{color:colors.muted},list:{borderWidth:1,borderColor:colors.line,borderRadius:radius.lg,overflow:'hidden',backgroundColor:colors.surface},product:{minHeight:78,padding:spacing.lg,flexDirection:'row',alignItems:'center',gap:12,borderBottomWidth:1,borderBottomColor:colors.line},copy:{flex:1},productTitle:{fontSize:type.bodyMD,fontWeight:'800',color:colors.ink},meta:{fontSize:type.labelSM,color:colors.muted,marginTop:4},priceText:{fontSize:type.bodyMD,fontWeight:'800',color:colors.commerce},empty:{padding:spacing.xl,alignItems:'center'},emptyTitle:{fontSize:type.titleMD,fontWeight:'800',color:colors.ink},emptyBody:{fontSize:type.bodySM,lineHeight:21,color:colors.muted,textAlign:'center',marginTop:5},note:{padding:spacing.xl,borderRadius:radius.lg,backgroundColor:colors.commerceSoft},noteKicker:{fontSize:type.labelSM,fontWeight:'800',letterSpacing:1.5,color:colors.commerce},noteTitle:{fontSize:type.titleMD,fontWeight:'800',color:colors.ink,marginTop:4},noteBody:{fontSize:type.bodySM,lineHeight:21,color:colors.inkSoft,marginTop:5}});
