import { useCallback,useEffect,useState } from 'react';
import { ActivityIndicator,Alert,Pressable,ScrollView,StyleSheet,Text,TextInput,View } from 'react-native';
import { Link } from 'expo-router';
import { api,getAccountExperiencePreferences,getMyProfile } from '../src/api/client';
import { AppShell } from '../src/ui/AppShell';
import { Icon } from '../src/ui/icons';
import { colors,elevation,radius,spacing,type } from '../src/ui/theme';

type Prefs={language:string;region:string;currency:string};
const defaults:Prefs={language:'en',region:'IN',currency:'INR'};
export default function SettingsControl(){
 const[prefs,setPrefs]=useState<Prefs>(defaults);const[profile,setProfile]=useState<any>(null);const[email,setEmail]=useState('');const[phone,setPhone]=useState('');const[loading,setLoading]=useState(true);const[busy,setBusy]=useState<string|null>(null);const[notice,setNotice]=useState('');
 const load=useCallback(async()=>{setLoading(true);try{const[p,r,c]=await Promise.all([getAccountExperiencePreferences(),getMyProfile(),api<any>('/v1/account/contacts')]);setPrefs({...defaults,...p});setProfile(r.profile);setEmail(c.email??'');setPhone(c.phone??'');}catch(e){setNotice(e instanceof Error?e.message:'Could not load account controls');}finally{setLoading(false);}},[]);useEffect(()=>{void load();},[load]);
 const saveContacts=async()=>{if(busy)return;setBusy('contacts');setNotice('');try{const r=await api<any>('/v1/account/contacts',{method:'PUT',body:JSON.stringify({email:email.trim()||null,phone:phone.trim()||null})});setEmail(r.email??email);setPhone(r.phone??phone);setNotice('Contact details saved. Verification state remains server-controlled.');}catch(e){setNotice(e instanceof Error?e.message:'Could not save contact details');}finally{setBusy(null);}};
 const destructive=(kind:'logout-all'|'delete')=>{const title=kind==='delete'?'Delete account and data':'Sign out other sessions';const body=kind==='delete'?'This creates an explicit deletion request. Required legal/commerce records may have a separate retention obligation.':'All other active sessions will be revoked.';Alert.alert(title,body,[{text:'Cancel',style:'cancel'},{text:'Continue',style:'destructive',onPress:async()=>{setBusy(kind);try{if(kind==='logout-all')await api('/v1/auth/sessions/revoke-all',{method:'POST'});else await api('/v1/privacy/data-requests',{method:'POST',body:JSON.stringify({kind:'delete'})});setNotice(kind==='delete'?'Deletion request created.':'Other sessions revoked.');}catch(e){setNotice(e instanceof Error?e.message:'Action failed');}finally{setBusy(null);}}}]);};
 if(loading)return <AppShell><View style={s.center}><ActivityIndicator/><Text style={s.muted}>Loading account controls…</Text></View></AppShell>;
 return <AppShell><ScrollView contentContainerStyle={s.content}><Link href="/settings" asChild><Pressable style={s.back}><Icon name="back" size={18} color={colors.brand}/><Text style={s.backText}>Settings</Text></Pressable></Link><Text style={s.kicker}>ACCOUNT CONTROLS</Text><Text style={s.title}>The details behind your account.</Text><Text style={s.subtitle}>Identity, contact channels and interface language live here; safety and privacy stay separated so consequential choices remain easy to understand.</Text>{notice?<View style={s.notice}><Icon name="info" size={18} color={colors.brand}/><Text style={s.noticeText}>{notice}</Text></View>:null}
 <Section title="Account"><Row icon="profile" title="Profile" body={`@${profile?.username??'—'} · ${profile?.display_name??'—'}`}/><Row icon="lock" title="Security" body="Sessions, alerts, passkeys and password recovery." href="/security"/></Section>
 <Section title="Email & phone"><Field label="Email" value={email} onChangeText={setEmail} placeholder="name@example.com"/><Field label="Phone" value={phone} onChangeText={setPhone} placeholder="+91…"/><Pressable style={s.primary} disabled={!!busy} onPress={()=>void saveContacts()}>{busy==='contacts'?<ActivityIndicator color={colors.white}/>:<><Icon name="check" size={17} color={colors.white}/><Text style={s.primaryText}>Save contact details</Text></>}</Pressable><Text style={s.helper}>Changing a contact channel never silently marks it verified.</Text></Section>
 <Section title="Appearance & accessibility"><View style={s.row}><Icon name="settings" size={18} color={colors.brand}/><View style={s.flex}><Text style={s.rowTitle}>Light appearance</Text><Text style={s.meta}>Drustpoll currently uses its light theme. In-app dark mode and operating-system theme overrides are not available yet.</Text></View></View><Link href="/accessibility" asChild><Pressable accessibilityRole="button" style={s.row}><Icon name="eye" size={18} color={colors.brand}/><View style={s.flex}><Text style={s.rowTitle}>Device accessibility</Text><Text style={s.meta}>Review text scaling, screen reader and reduced-motion settings reported by your device.</Text></View><Icon name="chevronRight" size={17} color={colors.muted}/></Pressable></Link></Section>
 <Section title="Language, region & currency"><View style={s.row}><Icon name="edit" size={18} color={colors.brand}/><View style={s.flex}><Text style={s.rowTitle}>Interface language</Text><Text style={s.meta}>{prefs.language.toUpperCase()}</Text></View></View><Link href="/language" asChild><Pressable accessibilityRole="button" style={s.outlineWide}><Icon name="edit" size={17} color={colors.brand}/><Text style={s.outlineText}>Change interface language</Text></Pressable></Link><View style={s.localeNote}><Text style={s.meta}>Account defaults · {prefs.region.toUpperCase()} · {prefs.currency.toUpperCase()}</Text><Text style={s.meta}>Region and currency preferences do not currently convert product prices or localize delivery. Market prices remain in each seller’s currency.</Text></View></Section>
 <Section title="Notifications"><Link href="/notifications" asChild><Pressable style={s.row}><Icon name="bell" size={18} color={colors.brand}/><View style={s.flex}><Text style={s.rowTitle}>Notification controls</Text><Text style={s.meta}>Categories, digest and quiet periods stay together.</Text></View><Icon name="chevronRight" size={17} color={colors.muted}/></Pressable></Link></Section>
 <Section title="Privacy, permissions & accessibility"><Link href="/privacy" asChild><Pressable style={s.row}><Icon name="shield" size={18} color={colors.brand}/><View style={s.flex}><Text style={s.rowTitle}>Privacy Center</Text><Text style={s.meta}>Visibility, hidden terms, recommendation reset, inventory, audit and data requests.</Text></View><Icon name="chevronRight" size={17} color={colors.muted}/></Pressable></Link><Link href="/accessibility" asChild><Pressable style={s.row}><Icon name="eye" size={18} color={colors.brand}/><View style={s.flex}><Text style={s.rowTitle}>Accessibility</Text><Text style={s.meta}>Review settings reported by the operating system or browser.</Text></View><Icon name="chevronRight" size={17} color={colors.muted}/></Pressable></Link></Section>
 <Section title="Account lifecycle"><Pressable style={s.row} disabled={!!busy} onPress={()=>destructive('logout-all')}><Icon name="shield" size={18} color={colors.brand}/><View style={s.flex}><Text style={s.rowTitle}>Sign out all other sessions</Text><Text style={s.meta}>Useful after device loss or a suspicious sign-in.</Text></View></Pressable><Pressable style={[s.row,s.dangerRow]} disabled={!!busy} onPress={()=>destructive('delete')}><Icon name="trash" size={18} color={colors.danger}/><View style={s.flex}><Text style={[s.rowTitle,{color:colors.danger}]}>Delete account & data</Text><Text style={s.meta}>Creates a visible deletion request; nothing is silently erased from a single tap.</Text></View></Pressable></Section>
 </ScrollView></AppShell>;
}
function Section({title,children}:{title:string;children:React.ReactNode}){return <View style={s.section}><Text style={s.sectionTitle}>{title}</Text><View style={s.card}>{children}</View></View>}
function Row({icon,title,body,href}:{icon:any;title:string;body:string;href?:any}){const v=<View style={s.row}><Icon name={icon} size={18} color={colors.brand}/><View style={s.flex}><Text style={s.rowTitle}>{title}</Text><Text style={s.meta}>{body}</Text></View>{href?<Icon name="chevronRight" size={17} color={colors.muted}/>:null}</View>;return href?<Link href={href} asChild><Pressable>{v}</Pressable></Link>:v}
function Field({label,value,onChangeText,placeholder}:{label:string;value:string;onChangeText:(v:string)=>void;placeholder:string}){return <View style={s.field}><Text style={s.label}>{label}</Text><TextInput accessibilityLabel={label} value={value} onChangeText={onChangeText} autoCapitalize="none" placeholder={placeholder} placeholderTextColor={colors.faint} style={s.input}/></View>}
const s=StyleSheet.create({content:{padding:spacing.xl,gap:spacing.lg,maxWidth:900,width:'100%',alignSelf:'center'},back:{minHeight:42,flexDirection:'row',alignItems:'center',gap:7},backText:{color:colors.brand,fontWeight:'900'},kicker:{fontSize:type.labelSM,fontWeight:'900',letterSpacing:1.8,color:colors.brand},title:{fontSize:type.displayLG,lineHeight:40,fontWeight:'900',color:colors.ink},subtitle:{fontSize:type.bodyMD,lineHeight:22,color:colors.muted},notice:{padding:spacing.md,borderRadius:radius.lg,backgroundColor:colors.brandSoft,flexDirection:'row',gap:8,alignItems:'center'},noticeText:{flex:1,color:colors.inkSoft,fontSize:type.bodySM,lineHeight:20},center:{minHeight:300,justifyContent:'center',alignItems:'center',gap:8},muted:{color:colors.muted},section:{gap:8},sectionTitle:{fontSize:type.titleLG,fontWeight:'900',color:colors.ink},card:{backgroundColor:colors.surface,borderWidth:1,borderColor:colors.line,borderRadius:radius.xl,...elevation.low,paddingHorizontal:spacing.lg},row:{minHeight:72,borderBottomWidth:1,borderBottomColor:colors.line,flexDirection:'row',alignItems:'center',gap:10,paddingVertical:11},dangerRow:{borderBottomWidth:0},flex:{flex:1},rowTitle:{fontSize:type.bodyMD,fontWeight:'800',color:colors.ink},meta:{fontSize:type.bodySM,lineHeight:19,color:colors.muted,marginTop:3},localeNote:{gap:5,paddingTop:10,paddingBottom:14,borderTopWidth:1,borderTopColor:colors.line},field:{paddingVertical:10,borderBottomWidth:1,borderBottomColor:colors.line},label:{fontSize:type.labelSM,fontWeight:'900',color:colors.inkSoft},input:{minHeight:46,borderWidth:1,borderColor:colors.line,borderRadius:radius.md,paddingHorizontal:12,color:colors.ink,fontSize:type.bodyMD,marginTop:6},primary:{minHeight:48,borderRadius:radius.md,backgroundColor:colors.brand,marginVertical:14,alignItems:'center',justifyContent:'center',flexDirection:'row',gap:7},primaryText:{color:colors.white,fontWeight:'900'},helper:{fontSize:type.bodySM,lineHeight:20,color:colors.muted,paddingBottom:12},choiceWrap:{flexDirection:'row',gap:8,paddingVertical:14,flexWrap:'wrap'},choice:{minHeight:42,paddingHorizontal:13,borderWidth:1,borderColor:colors.line,borderRadius:radius.pill,justifyContent:'center'},choiceActive:{backgroundColor:colors.brandSoft,borderColor:colors.brand},choiceText:{color:colors.muted,fontWeight:'800'},choiceTextActive:{color:colors.brand},outlineWide:{minHeight:48,borderWidth:1,borderColor:colors.brand,borderRadius:radius.md,alignItems:'center',justifyContent:'center',flexDirection:'row',gap:7,marginVertical:14},outlineText:{color:colors.brand,fontWeight:'900'}});
