import { useCallback, useEffect, useState } from 'react';
import { RefreshControl, ScrollView, StyleSheet, Text, View, Pressable } from 'react-native';
import { Link } from 'expo-router';
import { AppShell } from '../src/ui/AppShell';
import { colors, radius, spacing, type } from '../src/ui/theme';
import { getShopRecommendations } from '../src/api/client';
import { readCache, writeCache } from '../src/offline/cache';
import { Action, Surface, StateView } from '../src/ui/primitives';

type Items=Awaited<ReturnType<typeof getShopRecommendations>>['items'];
const CACHE_KEY='market.recommendations';
export default function Shop(){
 const[items,setItems]=useState<Items>([]);const[loading,setLoading]=useState(true);const[error,setError]=useState<string|null>(null);const[offline,setOffline]=useState(false);
 const load=useCallback(async()=>{setLoading(true);setError(null);setOffline(false);try{const cached=await readCache<Items>(CACHE_KEY);if(cached?.length)setItems(cached);const fresh=await getShopRecommendations();const next=fresh.items??[];setItems(next);await writeCache(CACHE_KEY,next);}catch(e){const cached=await readCache<Items>(CACHE_KEY);if(cached?.length){setItems(cached);setOffline(true);}else setError(e instanceof Error?e.message:'Could not load Market');}finally{setLoading(false);}},[]);
 useEffect(()=>{void load();},[load]);
 return <AppShell><ScrollView refreshControl={<RefreshControl refreshing={loading} onRefresh={()=>void load()} accessibilityLabel="Refresh Market"/>} contentContainerStyle={styles.content}><View style={styles.header}><View style={styles.headerCopy}><Text style={styles.kicker}>MARKET</Text><Text style={styles.title}>Products that fit your world.</Text><Text style={styles.sub}>Useful discovery from shops and products you have reason to care about.</Text></View><View style={styles.headerActions}><Link href="/orders" asChild><Pressable accessibilityRole="button" accessibilityLabel="Open orders" style={({pressed})=>[styles.orders,pressed&&styles.pressed]}><Text style={styles.ordersText}>Orders</Text></Pressable></Link><Link href="/cart" asChild><Pressable accessibilityRole="button" accessibilityLabel="Open cart" style={({pressed})=>[styles.cart,pressed&&styles.pressed]}><Text style={styles.cartText}>Cart</Text></Pressable></Link></View></View>{offline?<Surface tone="info"><Text style={styles.noticeTitle}>Showing your saved Market</Text><Text style={styles.noticeBody}>You're offline. Recommendations will refresh when a connection is available.</Text></Surface>:null}<Surface tone="commerce"><Text style={styles.explainTitle}>Why these products?</Text><Text style={styles.explainBody}>Recommendations can use recent activity, saved interests, relationships, availability and shop diversity. You stay in control.</Text></Surface>{loading&&!items.length?<StateView title="Finding relevant products…" body="Balancing relevance, variety and availability."/>:error?<StateView title="Market unavailable" body={error} action={<Action label="Try again" variant="secondary" onPress={()=>void load()}><Text style={styles.actionText}>Try again</Text></Action>}/>:!items.length?<StateView title="No products yet" body="Explore again later or open a shop from someone's profile."/>:items.map((p,i)=><Link key={p.id} href={{pathname:'/product',params:{id:p.id}}} asChild><Pressable accessibilityRole="button" accessibilityLabel={`Open ${p.title}`}><Surface style={styles.card}><View style={styles.numWrap}><Text style={styles.num}>{String(i+1).padStart(2,'0')}</Text></View><View style={styles.copy}><Text style={styles.ct}>{p.title}</Text><Text style={styles.cb}>{p.description||'Available from an active shop.'}</Text><Text style={styles.reason}>{p.reason.replaceAll('_',' ')}</Text></View><Text style={styles.price}>{(p.price_minor/100).toFixed(2)} {p.currency}</Text></Surface></Pressable></Link>)}</ScrollView></AppShell>;
}
const styles=StyleSheet.create({content:{padding:spacing.xl,gap:spacing.lg,maxWidth:1100,width:'100%',alignSelf:'center'},header:{flexDirection:'row',alignItems:'flex-start',justifyContent:'space-between',gap:spacing.md},headerCopy:{flex:1},headerActions:{flexDirection:'row',gap:8},kicker:{fontSize:type.labelSM,fontWeight:'800',letterSpacing:1.8,color:colors.commerce},title:{fontSize:type.displayLG,lineHeight:38,fontWeight:'800',color:colors.ink,maxWidth:500},sub:{fontSize:type.bodySM,lineHeight:20,color:colors.muted,marginTop:6},orders:{borderWidth:1,borderColor:colors.line,paddingHorizontal:14,paddingVertical:11,borderRadius:radius.md,minHeight:44,justifyContent:'center',backgroundColor:colors.surface},ordersText:{color:colors.ink,fontWeight:'800'},cart:{backgroundColor:colors.commerce,paddingHorizontal:16,paddingVertical:11,borderRadius:radius.md,minHeight:44,justifyContent:'center'},pressed:{opacity:.72},cartText:{color:colors.white,fontWeight:'800'},noticeTitle:{fontWeight:'800',color:colors.info},noticeBody:{fontSize:type.bodySM,lineHeight:20,color:colors.inkSoft,marginTop:4},explainTitle:{fontSize:type.titleMD,fontWeight:'800',color:colors.ink},explainBody:{fontSize:type.bodySM,lineHeight:21,color:colors.inkSoft,marginTop:6},actionText:{color:colors.ink,fontWeight:'800'},card:{minHeight:122,flexDirection:'row',alignItems:'center',gap:15},numWrap:{width:34,alignItems:'center'},num:{fontSize:type.labelSM,fontWeight:'800',color:colors.faint},copy:{flex:1},ct:{fontSize:type.titleMD,fontWeight:'800',color:colors.ink},cb:{fontSize:type.bodySM,lineHeight:19,color:colors.muted,marginTop:5},reason:{fontSize:type.labelSM,color:colors.commerce,marginTop:7,textTransform:'capitalize'},price:{fontSize:type.labelLG,fontWeight:'800',color:colors.ink}});
