import { useEffect, useMemo, useRef, useState } from 'react';
import { ActivityIndicator, Animated, Easing, KeyboardAvoidingView, Platform, Pressable, StyleSheet, Text, TextInput, View } from 'react-native';
import { router, useLocalSearchParams } from 'expo-router';
import { api } from '../src/api/client';
import { colors, radius, spacing, motion, touch } from '../src/ui/theme';
import { Icon } from '../src/ui/icons';
import { BrandMark } from '../src/ui/BrandMark';
import { useI18n } from '../src/i18n/provider';

type Purpose='verify_email'|'verify_phone'|'password_reset'|'login_step_up';
export default function VerifyOtp(){
 const{t}=useI18n();const params=useLocalSearchParams<{destination?:string;purpose?:Purpose}>();const destination=String(params.destination??'');const purpose=(String(params.purpose??'verify_email') as Purpose);const isPhone=purpose==='verify_phone';
 const[code,setCode]=useState('');const[busy,setBusy]=useState(false);const[resending,setResending]=useState(false);const[error,setError]=useState('');const[notice,setNotice]=useState('');const[left,setLeft]=useState(300);const[requested,setRequested]=useState(true);const input=useRef<TextInput>(null);const pulse=useRef(new Animated.Value(0)).current;
 useEffect(()=>{input.current?.focus();const timer=setInterval(()=>setLeft(v=>Math.max(v-1,0)),1000);return()=>clearInterval(timer);},[]);
 useEffect(()=>{if(requested&&destination)setNotice(isPhone?t('codeSentPhone'):t('checkInbox'));},[requested,destination,isPhone,t]);
 const masked=useMemo(()=>{if(!destination)return '';if(destination.includes('@')){const[a,b]=destination.split('@');return `${a.slice(0,2)}•••@${b}`;}return `${destination.slice(0,3)}••••${destination.slice(-2)}`;},[destination]);
 const validCode=/^\d{6}$/.test(code);
 useEffect(()=>{if(validCode){pulse.setValue(0);Animated.timing(pulse,{toValue:1,duration:motion.quick,easing:Easing.out(Easing.cubic),useNativeDriver:true}).start();}},[validCode,pulse]);
 function friendlyOtpError(e:unknown){const m=e instanceof Error?e.message:'';if(/NETWORK_TIMEOUT|network request failed|fetch failed|failed to fetch|unable to resolve host|timed out|eai_again|enotfound|etimedout/i.test(m))return 'Unable to reach the Drustpoll server right now. Please check your connection and try again.';if(/too many/i.test(m))return 'Too many code requests. Please wait a little and try again.';return m||t('error');}
 async function verify(){setError('');setNotice('');if(!destination)return setError(t('error'));if(left===0)return setError(t('codeExpired'));if(!validCode)return setError(t('invalidCode'));setBusy(true);try{const result=await api<{verified:boolean;purpose:Purpose}>('/v1/auth/otp/verify',{method:'POST',body:JSON.stringify({destination,purpose,code})});if(result.verified){setNotice(t('done'));setTimeout(()=>router.replace(purpose==='password_reset'?'/auth':'/profile-setup'),220);}}catch(e){setError(friendlyOtpError(e));}finally{setBusy(false);}}
 async function resend(){if(resending||left>270)return;setResending(true);setError('');setNotice('');try{await api('/v1/auth/otp/request',{method:'POST',body:JSON.stringify({destination,purpose})});setLeft(300);setCode('');setRequested(true);setNotice(isPhone?t('codeSentPhone'):t('checkInbox'));}catch(e){setError(friendlyOtpError(e));}finally{setResending(false);}}
 return <KeyboardAvoidingView style={s.screen} behavior={Platform.OS==='ios'?'padding':undefined}><View style={s.wrap}><View style={s.header}><Pressable onPress={()=>router.back()} accessibilityRole="button" accessibilityLabel={t('back')} style={({pressed})=>[s.icon,pressed&&s.pressed]}><Icon name="back" size={20} color={colors.ink}/></Pressable><View style={s.brand}><BrandMark size={34}/><View><Text style={s.brandWord}>DRUSTPOLL</Text><Text style={s.kicker}>{t('verification').toUpperCase()}</Text></View></View></View><View style={s.hero}><Text style={s.title}>{isPhone?t('verifyPhone'):purpose==='password_reset'?t('verifyRecovery'):t('verificationTitle')}</Text><Text style={s.body}>{t('verificationBody')}</Text><Text style={s.destination}>{masked||t('verifiedContact')}</Text></View><View style={s.codeSection}><View style={s.codeTop}><Text style={s.codeLabel}>ONE-TIME CODE</Text><Text style={s.expiry}>{left===0?t('codeExpired'):`${Math.floor(left/60).toString().padStart(2,'0')}:${(left%60).toString().padStart(2,'0')}`}</Text></View><Animated.View style={[s.codeField,{transform:[{scale:pulse.interpolate({inputRange:[0,1],outputRange:[1,.992]})}]}]}><TextInput ref={input} value={code} onChangeText={v=>setCode(v.replace(/\D/g,'').slice(0,6))} keyboardType="number-pad" maxLength={6} inputMode="numeric" autoComplete="one-time-code" textContentType="oneTimeCode" style={s.code} placeholder="000000" placeholderTextColor={colors.faint} accessibilityLabel={t('verification')}/></Animated.View><View style={s.digits}>{Array.from({length:6},(_,i)=><View key={i} style={[s.digitBar,i<code.length&&s.digitBarFilled]}/>)}</View></View>{error?<View style={s.error} accessibilityRole="alert"><Icon name="circleAlert" size={17} color={colors.danger}/><Text style={s.errorText}>{error}</Text></View>:null}{notice?<View style={s.notice} accessibilityLiveRegion="polite"><Icon name="circleCheck" size={17} color={colors.success}/><Text style={s.noticeText}>{notice}</Text></View>:null}<Pressable accessibilityRole="button" disabled={busy||left===0} onPress={()=>void verify()} style={({pressed})=>[s.primary,(busy||left===0)&&s.disabled,pressed&&s.pressed]}>{busy?<ActivityIndicator color={colors.white}/>:<><Text style={s.primaryText}>{t('verify')} · {t('continue').toLowerCase()}</Text><Icon name="chevronRight" size={17} color={colors.white}/></>}</Pressable><Pressable accessibilityRole="button" disabled={resending||left>270} onPress={()=>void resend()} style={s.secondary}><Text style={[s.secondaryText,(resending||left>270)&&s.muted]}>{resending?t('loading'):left>270?`${t('resendIn')} ${left-270}s`:t('resend')}</Text></Pressable><Text style={s.security}>{t('otpNeverShare')}</Text></View></KeyboardAvoidingView>;
}
const s=StyleSheet.create({screen:{flex:1,backgroundColor:colors.canvas},wrap:{width:'100%',maxWidth:560,flex:1,alignSelf:'center',padding:spacing.xl,justifyContent:'center'},header:{minHeight:48,flexDirection:'row',alignItems:'center',gap:12,marginBottom:30},icon:{width:touch.comfortable,height:touch.comfortable,borderRadius:radius.md,borderWidth:1,borderColor:colors.line,backgroundColor:colors.surface,alignItems:'center',justifyContent:'center'},brand:{flexDirection:'row',alignItems:'center',gap:9},brandWord:{fontSize:12,fontWeight:'900',letterSpacing:1.7,color:colors.ink},kicker:{fontSize:9,fontWeight:'800',letterSpacing:1.8,color:colors.brand,marginTop:3},hero:{gap:7},title:{fontSize:38,lineHeight:43,fontWeight:'800',letterSpacing:-1.2,color:colors.ink},body:{fontSize:15,lineHeight:22,color:colors.muted,marginTop:3,maxWidth:470},destination:{fontSize:16,fontWeight:'800',color:colors.ink,marginTop:3},codeSection:{marginTop:30,paddingTop:20,borderTopWidth:1,borderTopColor:colors.line},codeTop:{flexDirection:'row',justifyContent:'space-between',alignItems:'center'},codeLabel:{fontSize:10,fontWeight:'900',letterSpacing:1.8,color:colors.faint},expiry:{fontSize:11,fontWeight:'800',color:colors.muted},codeField:{height:82,borderWidth:1,borderColor:colors.line,borderRadius:radius.lg,backgroundColor:colors.surface,marginTop:10,justifyContent:'center'},code:{height:78,fontSize:38,letterSpacing:8,fontWeight:'800',color:colors.ink,textAlign:'center'},digits:{flexDirection:'row',gap:5,marginTop:9},digitBar:{height:3,flex:1,borderRadius:3,backgroundColor:colors.line},digitBarFilled:{backgroundColor:colors.brand},error:{minHeight:46,padding:12,borderRadius:radius.md,backgroundColor:colors.dangerSoft,flexDirection:'row',gap:8,alignItems:'center',marginTop:16},errorText:{flex:1,color:colors.danger,fontSize:12.5,lineHeight:18},notice:{minHeight:46,padding:12,borderRadius:radius.md,backgroundColor:colors.successSoft,flexDirection:'row',gap:8,alignItems:'center',marginTop:16},noticeText:{flex:1,color:colors.inkSoft,fontSize:12.5,lineHeight:18},primary:{height:52,borderRadius:radius.md,backgroundColor:colors.brand,alignItems:'center',justifyContent:'center',marginTop:18,flexDirection:'row',gap:8},primaryText:{color:colors.white,fontSize:14,fontWeight:'900'},secondary:{minHeight:46,alignItems:'center',justifyContent:'center',paddingHorizontal:10},secondaryText:{fontSize:13,fontWeight:'800',color:colors.brand},muted:{color:colors.faint},disabled:{opacity:.55},pressed:{opacity:.78,transform:[{scale:.988}]},security:{fontSize:11,lineHeight:17,color:colors.faint,textAlign:'center',maxWidth:430,alignSelf:'center',marginTop:18}});