import { useEffect, useMemo, useRef, useState } from 'react';
import { ActivityIndicator, KeyboardAvoidingView, Platform, Pressable, StyleSheet, Text, TextInput, View } from 'react-native';
import { router, useLocalSearchParams } from 'expo-router';
import { api } from '../src/api/client';
import { colors, radius, spacing } from '../src/ui/theme';
import { Icon } from '../src/ui/icons';
import { useI18n } from '../src/i18n/provider';

type Purpose='verify_email'|'verify_phone'|'password_reset'|'login_step_up';
export default function VerifyOtp(){
 const{t}=useI18n();const params=useLocalSearchParams<{destination?:string;purpose?:Purpose}>();const destination=String(params.destination??'');const purpose=(String(params.purpose??'verify_email') as Purpose);const isPhone=purpose==='verify_phone';
 const[code,setCode]=useState('');const[busy,setBusy]=useState(false);const[resending,setResending]=useState(false);const[error,setError]=useState('');const[notice,setNotice]=useState('');const[left,setLeft]=useState(300);const[requested,setRequested]=useState(false);const input=useRef<TextInput>(null);
 useEffect(()=>{input.current?.focus();const timer=setInterval(()=>setLeft(v=>Math.max(v-1,0)),1000);return()=>clearInterval(timer);},[]);
 useEffect(()=>{if(!destination||requested)return;let active=true;(async()=>{try{await api('/v1/auth/otp/request',{method:'POST',body:JSON.stringify({destination,purpose})});if(active){setRequested(true);setNotice(isPhone?t('codeSentPhone'):t('checkInbox'));}}catch(e){if(active)setError(e instanceof Error?e.message:t('error'));}})();return()=>{active=false;};},[destination,purpose,requested,isPhone,t]);
 const masked=useMemo(()=>{if(!destination)return '';if(destination.includes('@')){const[a,b]=destination.split('@');return `${a.slice(0,2)}•••@${b}`;}return `${destination.slice(0,3)}••••${destination.slice(-2)}`;},[destination]);
 async function verify(){setError('');setNotice('');if(!destination)return setError(t('error'));if(left===0)return setError(t('codeExpired'));if(!/^\d{6}$/.test(code))return setError(t('invalidCode'));setBusy(true);try{const result=await api<{verified:boolean;purpose:Purpose}>('/v1/auth/otp/verify',{method:'POST',body:JSON.stringify({destination,purpose,code})});if(result.verified){setNotice(t('done'));setTimeout(()=>router.replace(purpose==='password_reset'?'/auth':'/profile-setup'),220);}}catch(e){setError(/invalid or expired otp/i.test(e instanceof Error?e.message:'')?t('invalidCode'):e instanceof Error?e.message:t('invalidCode'));}finally{setBusy(false);}}
 async function resend(){if(resending||left>270)return;setResending(true);setError('');try{await api('/v1/auth/otp/request',{method:'POST',body:JSON.stringify({destination,purpose})});setLeft(300);setCode('');setRequested(true);setNotice(isPhone?t('codeSentPhone'):t('checkInbox'));}catch(e){setError(e instanceof Error?e.message:t('error'));}finally{setResending(false);}}
 return <KeyboardAvoidingView style={s.screen} behavior={Platform.OS==='ios'?'padding':undefined}><View style={s.wrap}><View style={s.header}><Pressable onPress={()=>router.back()} accessibilityRole="button" accessibilityLabel={t('back')} style={s.icon}><Icon name="back" size={20} color={colors.ink}/></Pressable><Text style={s.kicker}>{t('verification').toUpperCase()}</Text></View><View style={s.hero}><View style={s.mark}><Icon name={isPhone?'phone':'shield'} size={25} color={colors.white}/></View><Text style={s.title}>{isPhone?t('verifyPhone'):purpose==='password_reset'?t('verifyRecovery'):t('verificationTitle')}</Text><Text style={s.body}>{t('verificationBody')} <Text style={s.strong}>{masked||t('verifiedContact')}</Text></Text></View><View style={s.codeRow}><TextInput ref={input} value={code} onChangeText={v=>setCode(v.replace(/\D/g,'').slice(0,6))} keyboardType="number-pad" maxLength={6} inputMode="numeric" autoComplete="one-time-code" textContentType="oneTimeCode" style={s.code} placeholder="000000" placeholderTextColor={colors.faint} accessibilityLabel={t('verification')}/></View>{left===0?<Text style={s.timer}>{t('codeExpired')}</Text>:<Text style={s.timer}>{t('expiresIn')} {String(Math.floor(left/60)).padStart(2,'0')}:{String(left%60).padStart(2,'0')}</Text>}{error?<View style={s.error} accessibilityRole="alert"><Icon name="circleAlert" size={18} color={colors.danger}/><Text style={s.errorText}>{error}</Text></View>:null}{notice?<View style={s.notice} accessibilityLiveRegion="polite"><Icon name="circleCheck" size={18} color={colors.success}/><Text style={s.noticeText}>{notice}</Text></View>:null}<Pressable disabled={busy||left===0} onPress={()=>void verify()} style={[s.primary,(busy||left===0)&&s.disabled]}>{busy?<ActivityIndicator color={colors.white}/>:<Text style={s.primaryText}>{t('verify')} · {t('continue').toLowerCase()}</Text>}</Pressable><Pressable disabled={resending||left>270} onPress={()=>void resend()} style={s.secondary}><Text style={[s.secondaryText,(resending||left>270)&&s.muted]}>{resending?t('loading'):left>270?`${t('resendIn')} ${left-270}s`:t('resend')}</Text></Pressable><Text style={s.security}>{t('otpNeverShare')}</Text></View></KeyboardAvoidingView>;
}
const s=StyleSheet.create({screen:{flex:1,backgroundColor:colors.canvas},wrap:{width:'100%',maxWidth:560,alignSelf:'center',flex:1,padding:spacing.xl,justifyContent:'center',gap:16},header:{flexDirection:'row',alignItems:'center',gap:12},icon:{width:44,height:44,borderRadius:radius.md,borderWidth:1,borderColor:colors.line,backgroundColor:colors.surface,alignItems:'center',justifyContent:'center'},kicker:{fontSize:11,fontWeight:'900',letterSpacing:2,color:colors.brand},hero:{gap:9,marginTop:8},mark:{width:58,height:58,borderRadius:21,backgroundColor:colors.brand,alignItems:'center',justifyContent:'center'},title:{fontSize:38,lineHeight:44,fontWeight:'900',letterSpacing:-1.1,color:colors.ink},body:{fontSize:16,lineHeight:24,color:colors.muted,maxWidth:480},strong:{color:colors.ink,fontWeight:'800'},codeRow:{marginTop:12,borderBottomWidth:2,borderBottomColor:colors.brand},code:{height:76,fontSize:38,letterSpacing:11,fontWeight:'900',color:colors.ink,textAlign:'center'},timer:{fontSize:12,fontWeight:'800',color:colors.muted,textAlign:'center'},error:{padding:13,borderRadius:radius.md,backgroundColor:colors.dangerSoft,flexDirection:'row',gap:9},errorText:{flex:1,color:colors.danger,fontSize:13,lineHeight:19},notice:{padding:13,borderRadius:radius.md,backgroundColor:colors.successSoft,flexDirection:'row',gap:9},noticeText:{flex:1,color:colors.inkSoft,fontSize:13,lineHeight:19},primary:{height:56,borderRadius:16,backgroundColor:colors.brand,alignItems:'center',justifyContent:'center',marginTop:4},primaryText:{color:colors.white,fontSize:16,fontWeight:'900'},secondary:{minHeight:48,alignItems:'center',justifyContent:'center'},secondaryText:{color:colors.brand,fontWeight:'800'},muted:{color:colors.faint},disabled:{opacity:.5},security:{fontSize:11,lineHeight:17,color:colors.faint,textAlign:'center',maxWidth:440,alignSelf:'center'}});