import { useEffect, useMemo, useRef, useState } from 'react';
import { ActivityIndicator, KeyboardAvoidingView, Platform, Pressable, StyleSheet, Text, TextInput, View } from 'react-native';
import { router, useLocalSearchParams } from 'expo-router';
import { api } from '../src/api/client';
import { colors, radius, spacing, type } from '../src/ui/theme';
import { Icon } from '../src/ui/icons';

type Purpose='verify_email'|'verify_phone'|'password_reset'|'login_step_up';
export default function VerifyOtp(){
 const params=useLocalSearchParams<{destination?:string;purpose?:Purpose;challengeId?:string}>();
 const destination=String(params.destination??''); const purpose=(String(params.purpose??'verify_email') as Purpose);
 const [code,setCode]=useState('');const[busy,setBusy]=useState(false);const[resending,setResending]=useState(false);const[error,setError]=useState('');const[notice,setNotice]=useState('');const[left,setLeft]=useState(300);const input=useRef<TextInput>(null);
 useEffect(()=>{input.current?.focus();const t=setInterval(()=>setLeft(v=>Math.max(0,v-1)),1000);return()=>clearInterval(t);},[]);
 const masked=useMemo(()=>{if(!destination)return '';if(destination.includes('@')){const[a,b]=destination.split('@');return `${a.slice(0,2)}•••@${b}`;}return `${destination.slice(0,3)}••••${destination.slice(-2)}`;},[destination]);
 async function verify(){setError('');setNotice('');if(!/^\d{6}$/.test(code))return setError('Enter the 6-digit code.');setBusy(true);try{await api('/v1/auth/otp/verify',{method:'POST',body:JSON.stringify({destination,purpose,code})});setNotice('Verified.');setTimeout(()=>router.replace(purpose==='password_reset'?'/auth':'/'),220);}catch(e){setError(e instanceof Error?e.message:'That code could not be verified.');}finally{setBusy(false);}}
 async function resend(){if(resending||left>270)return;setResending(true);setError('');try{await api('/v1/auth/otp/request',{method:'POST',body:JSON.stringify({destination,purpose})});setLeft(300);setCode('');setNotice('A new code has been sent.');}catch(e){setError(e instanceof Error?e.message:'Could not send a new code.');}finally{setResending(false);}}
 return <KeyboardAvoidingView style={s.screen} behavior={Platform.OS==='ios'?'padding':undefined}><View style={s.wrap}><View style={s.header}><Pressable onPress={()=>router.back()} accessibilityRole="button" accessibilityLabel="Back" style={s.icon}><Icon name="back" size={20} color={colors.ink}/></Pressable><Text style={s.kicker}>SECURITY CHECK</Text></View><View style={s.hero}><View style={s.mark}><Icon name={destination.includes('@')?'mail':'phone'} size={25} color={colors.white}/></View><Text style={s.title}>Enter the code.</Text><Text style={s.body}>We sent a one-time code to <Text style={s.strong}>{masked||'your verified contact'}</Text>. It expires in 5 minutes.</Text></View><View style={s.codeRow}><TextInput ref={input} value={code} onChangeText={v=>setCode(v.replace(/\D/g,'').slice(0,6))} keyboardType="number-pad" maxLength={6} inputMode="numeric" style={s.code} placeholder="000000" placeholderTextColor={colors.faint} accessibilityLabel="6 digit verification code"/></View>{left===0?<Text style={s.timer}>Code expired.</Text>:<Text style={s.timer}>Expires in {String(Math.floor(left/60)).padStart(2,'0')}:{String(left%60).padStart(2,'0')}</Text>}{error?<View style={s.error} accessibilityRole="alert"><Icon name="circleAlert" size={18} color={colors.danger}/><Text style={s.errorText}>{error}</Text></View>:null}{notice?<View style={s.notice} accessibilityLiveRegion="polite"><Icon name="circleCheck" size={18} color={colors.success}/><Text style={s.noticeText}>{notice}</Text></View>:null}<Pressable disabled={busy||left===0} onPress={()=>void verify()} style={[s.primary,(busy||left===0)&&s.disabled]}>{busy?<ActivityIndicator color={colors.white}/>:<Text style={s.primaryText}>Verify and continue</Text>}</Pressable><Pressable disabled={resending||left>270} onPress={()=>void resend()} style={s.secondary}><Text style={[s.secondaryText,(resending||left>270)&&s.muted]}>{resending?'Sending…':left>270?`Resend in ${left-270}s`:'Resend code'}</Text></Pressable><Text style={s.security}>Never share this code. Drustpoll support will never ask for it.</Text></View></KeyboardAvoidingView>;
}
const s=StyleSheet.create({screen:{flex:1,backgroundColor:colors.canvas},wrap:{width:'100%',maxWidth:560,alignSelf:'center',flex:1,padding:spacing.xl,justifyContent:'center',gap:16},header:{flexDirection:'row',alignItems:'center',gap:12},icon:{width:44,height:44,borderRadius:radius.md,borderWidth:1,borderColor:colors.line,backgroundColor:colors.surface,alignItems:'center',justifyContent:'center'},kicker:{fontSize:11,fontWeight:'900',letterSpacing:2,color:colors.brand},hero:{gap:9,marginTop:8},mark:{width:58,height:58,borderRadius:21,backgroundColor:colors.brand,alignItems:'center',justifyContent:'center'},title:{fontSize:38,lineHeight:44,fontWeight:'900',letterSpacing:-1.1,color:colors.ink},body:{fontSize:16,lineHeight:24,color:colors.muted,maxWidth:480},strong:{color:colors.ink,fontWeight:'800'},codeRow:{marginTop:12,borderBottomWidth:2,borderBottomColor:colors.brand},code:{height:76,fontSize:38,letterSpacing:11,fontWeight:'900',color:colors.ink,textAlign:'center'},timer:{fontSize:12,fontWeight:'800',color:colors.muted,textAlign:'center'},error:{padding:13,borderRadius:radius.md,backgroundColor:colors.dangerSoft,flexDirection:'row',gap:9},errorText:{flex:1,color:colors.danger,fontSize:13,lineHeight:19},notice:{padding:13,borderRadius:radius.md,backgroundColor:colors.successSoft,flexDirection:'row',gap:9},noticeText:{flex:1,color:colors.inkSoft,fontSize:13,lineHeight:19},primary:{height:56,borderRadius:16,backgroundColor:colors.brand,alignItems:'center',justifyContent:'center',marginTop:4},primaryText:{color:colors.white,fontSize:16,fontWeight:'900'},secondary:{minHeight:48,alignItems:'center',justifyContent:'center'},secondaryText:{color:colors.brand,fontWeight:'800'},muted:{color:colors.faint},disabled:{opacity:.5},security:{fontSize:11,lineHeight:17,color:colors.faint,textAlign:'center',maxWidth:440,alignSelf:'center'}});