import { api } from './client';
export async function getPrivacy(){return api<any>('/v1/privacy');}
export async function updatePrivacy(input:any){return api<any>('/v1/privacy',{method:'PUT',body:JSON.stringify(input)});}
export async function getHiddenTerms(){return api<any>('/v1/privacy/hidden-terms');}
export async function setHiddenTerm(term:string,kind:'word'|'topic',hidden:boolean){return api<any>('/v1/privacy/hidden-terms',{method:hidden?'POST':'DELETE',body:JSON.stringify({term,kind})});}
export async function resetRecommendations(){return api<any>('/v1/privacy/recommendations/reset',{method:'POST'});}
export async function getDataInventory(){return api<any>('/v1/privacy/inventory');}
export async function getDataRequests(){return api<any>('/v1/privacy/data-requests');}
export async function requestData(kind:'export'|'delete'){return api<any>('/v1/privacy/data-requests',{method:'POST',body:JSON.stringify({kind})});}
export async function getPrivacyPermissions(){return api<any>('/v1/privacy/permissions');}
export async function getPermissions(){return getPrivacyPermissions();}
export async function getPrivacyAudit(){return api<any>('/v1/privacy/audit');}
export async function getBlockedUsers(){return api<any>('/v1/privacy/blocked');}
export async function getMutedUsers(){return api<any>('/v1/privacy/muted');}
export async function setBlocked(userId:string,blocked:boolean){return api<any>('/v1/safety/block',{method:blocked?'POST':'DELETE',body:JSON.stringify({targetUserId:userId})});}
export async function setMuted(userId:string,muted:boolean){return api<any>('/v1/safety/mute',{method:muted?'POST':'DELETE',body:JSON.stringify({targetUserId:userId})});}
export async function getAccountExperiencePreferences(){return api<any>('/v1/account/experience');}
export async function updateAccountExperiencePreferences(input:any){return api<any>('/v1/account/experience',{method:'PUT',body:JSON.stringify(input)});}
export async function getAccountContacts(){return api<any>('/v1/account/contacts');}
export async function updateAccountContacts(input:any){return api<any>('/v1/account/contacts',{method:'PUT',body:JSON.stringify(input)});}
export async function getSecurityAlerts(){return api<any>('/v1/security/alerts');}
export async function acknowledgeSecurityAlert(id:string){return api<any>(`/v1/security/alerts/${encodeURIComponent(id)}/ack`,{method:'POST'});}
export async function getSecurityEvents(){return api<any>('/v1/security/events');}
export async function secureAccount(){return api<any>('/v1/security/secure-account',{method:'POST'});}
export async function getProfessionalProfile(){return api<any>('/v1/account/professional');}
export async function updateProfessionalProfile(input:any){return api<any>('/v1/account/professional',{method:'PUT',body:JSON.stringify(input)});}
export async function getBusinessVerification(){return api<any>('/v1/business/verification');}
export async function requestBusinessVerification(input:any){return api<any>('/v1/business/verification',{method:'POST',body:JSON.stringify(input)});}
export async function getAdCampaigns(){return api<any>('/v1/ads/campaigns');}
export async function getAdDeliveryControls(){return api<any>('/v1/ads/delivery-controls');}
export async function updateAdDeliveryControls(input:any){return api<any>('/v1/ads/delivery-controls',{method:'PUT',body:JSON.stringify(input)});}
export async function createAdCampaign(input:any){return api<any>('/v1/ads/campaigns',{method:'POST',body:JSON.stringify(input)});}
export async function createAdCreative(campaignId:string,input:any){return api<any>(`/v1/ads/campaigns/${encodeURIComponent(campaignId)}/creatives`,{method:'POST',body:JSON.stringify(input)});}
export async function getAdForViewer(context='feed'){return api<any>(`/v1/ads/serve?context=${encodeURIComponent(context)}`);}
export async function reportAdViewerFeedback(creativeId:string,signal:string){return api<any>(`/v1/ads/serve/${encodeURIComponent(creativeId)}/feedback`,{method:'POST',body:JSON.stringify({signal})});}
export async function getSafetyState(targetUserId?:string){return api<any>(`/v1/safety/state${targetUserId?`?targetUserId=${encodeURIComponent(targetUserId)}`:''}`);}
export async function reportTarget(target:any,reason:string,details=''){return api<any>('/v1/safety/report',{method:'POST',body:JSON.stringify({target,reason,details})});}
export async function setRestricted(targetUserId:string,restricted:boolean){return api<any>('/v1/safety/restrict',{method:restricted?'POST':'DELETE',body:JSON.stringify({targetUserId})});}
export async function getSafetyCases(){return api<any>('/v1/safety/cases');}
export async function addReportEvidence(caseId:string,evidence:any){return api<any>(`/v1/safety/cases/${encodeURIComponent(caseId)}/evidence`,{method:'POST',body:JSON.stringify(evidence)});}
export async function submitSafetyAppeal(caseId:string,reason:string){return api<any>(`/v1/safety/cases/${encodeURIComponent(caseId)}/appeal`,{method:'POST',body:JSON.stringify({reason})});}
export async function getModerationNotices(){return api<any>('/v1/safety/notices');}
