const API_URL=(process.env.EXPO_PUBLIC_API_URL??'').replace(/\/$/,'');
export class ApiError extends Error{constructor(public status:number,message:string){super(message);}}
export async function api<T>(path:string,init:RequestInit={}):Promise<T>{if(!API_URL)throw new ApiError(0,'EXPO_PUBLIC_API_URL is not configured');const res=await fetch(`${API_URL}${path}`,{...init,credentials:'include',headers:{'Content-Type':'application/json',...(init.headers??{})}});const text=await res.text();let data:any={};try{data=text?JSON.parse(text):{};}catch{data={error:'Invalid server response'};}if(!res.ok)throw new ApiError(res.status,String(data.error??`Request failed (${res.status})`));return data as T;}
export type FeedPost={id:string;author_id:string;caption:string;visibility:string;created_at:string;like_count:number;comment_count:number;save_count:number;share_count:number;media:Array<{type:'image'|'video';uri:string;alt?:string}>};
export async function getFeed(mode:'for_you'|'following'='for_you',before?:string){return api<{items:FeedPost[];nextCursor?:string|null}>(`/v1/feed?mode=${mode}${before?`&before=${encodeURIComponent(before)}`:''}`);}
export async function getReels(){return api<{items:Array<{id:string;author_id:string;created_at:string;username:string;display_name:string;videoUrl:string;prior_watched_ms:number;prior_duration_ms:number;creator_exposures:number;likes:number;comments:number;position:number;reason:string;score:number}>}>(`/v1/reels/recommended`);}
export async function startReelWatchSession(clientSessionId:string){return api<{sessionId:string}>(`/v1/reels/watch-sessions`,{method:'POST',body:JSON.stringify({clientSessionId})});}
export async function recordReelWatchEvents(sessionId:string,events:Array<{postId:string;eventType:'impression'|'start'|'progress'|'complete'|'skip'|'replay'|'like'|'save'|'share'|'comment'|'not_interested';position?:number;watchedMs?:number;videoDurationMs?:number;clientEventId:string}>){return api<{accepted:number;acceptedClientEventIds:string[]}>(`/v1/reels/watch-events`,{method:'POST',body:JSON.stringify({sessionId,events})});}
export async function endReelWatchSession(sessionId:string){return api(`/v1/reels/watch-sessions/${encodeURIComponent(sessionId)}`,{method:'DELETE'});}
export async function getShopRecommendations(){return api<{items:Array<{id:string;shop_id:string;title:string;description:string;price_minor:number;currency:string;inventory:number;score:number;reason:string}>}>(`/v1/shop/recommended`);}
export async function recordCommerceEvent(input:{productId:string;eventType:'impression'|'open'|'view'|'add_cart'|'remove_cart'|'purchase'|'save'|'not_interested';dwellMs?:number;clientEventId?:string}){return api<{accepted:boolean}>(`/v1/shop/events`,{method:'POST',body:JSON.stringify(input)});}
export async function getCart(){return api<{id:string|null;items:Array<{productId:string;quantity:number;unitPriceMinor:number;title:string;currency:string;inventory:number}>}>(`/v1/cart`);}
export async function addCartItem(productId:string,quantity:number){return api(`/v1/cart/items`,{method:'POST',body:JSON.stringify({productId,quantity})});}
export async function updateCartItem(productId:string,quantity:number){return api<{id:string|null;items:Array<{productId:string;quantity:number;unitPriceMinor:number;title:string;currency:string;inventory:number}>}>(`/v1/cart/items`,{method:'PATCH',body:JSON.stringify({productId,quantity})});}
export async function checkout(idempotencyKey:string){return api<{orders:Array<{orderId:string;totalMinor:number;currency:string;status:string}>}>(`/v1/orders`,{method:'POST',body:JSON.stringify({idempotencyKey})});}
export async function createPost(input:{caption:string;visibility:'public'|'followers'|'private';mediaAssetIds?:string[]}){return api<{id:string;createdAt:string}>('/v1/posts',{method:'POST',body:JSON.stringify(input)});}
export async function getMyProfile(){return api<{profile:{user_id:string;username:string;display_name:string;bio:string;avatar_url:string|null;website_url:string|null;profile_visibility:string;follower_count:number;following_count:number;post_count:number}|null}>('/v1/social/me/profile');}
export async function recordExposure(items:Array<{postId:string;creatorId:string;surface:'feed'|'reels'|'shop';position:number}>){return api('/v1/recommendation/exposure',{method:'POST',body:JSON.stringify({items})});}
export type PrivacySettings={profile_visibility:'public'|'followers'|'private';activity_visibility:'everyone'|'followers'|'only_me';discoverability:'discoverable'|'hidden';message_requests:'everyone'|'followers'|'nobody';personalized_recommendations:boolean;personalized_ads:boolean};
export async function getPrivacy(){return api<{privacy:PrivacySettings}>('/v1/privacy');}
export async function updatePrivacy(input:Partial<{profileVisibility:'public'|'followers'|'private';activityVisibility:'everyone'|'followers'|'only_me';discoverability:'discoverable'|'hidden';messageRequests:'everyone'|'followers'|'nobody';personalizedRecommendations:boolean;personalizedAds:boolean}>){return api<{privacy:PrivacySettings}>('/v1/privacy',{method:'PUT',body:JSON.stringify(input)});}
export type Notification={id:string;actor_id:string|null;type:string;object_id:string|null;read_at:string|null;created_at:string;actor_username?:string;actor_display_name?:string;metadata?:Record<string,unknown>};
export async function getNotifications(limit=30,before?:string){return api<{notifications:Notification[];nextBefore:string|null}>(`/v1/notifications?limit=${Math.min(Math.max(limit,1),100)}${before?`&before=${encodeURIComponent(before)}`:''}`);}
export async function markAllNotificationsRead(){return api<{updated:number}>('/v1/notifications/read-all',{method:'POST'});}
export async function markNotificationRead(id:string){return api<{ok:boolean}>(`/v1/notifications/${encodeURIComponent(id)}/read`,{method:'POST'});}
