const API_URL=(process.env.EXPO_PUBLIC_API_URL??'').replace(/\/$/,'');
export class ApiError extends Error{constructor(public status:number,message:string){super(message);}}
export async function api<T>(path:string,init:RequestInit={}):Promise<T>{if(!API_URL)throw new ApiError(0,'EXPO_PUBLIC_API_URL is not configured');const res=await fetch(`${API_URL}${path}`,{...init,credentials:'include',headers:{'Content-Type':'application/json',...(init.headers??{})}});const text=await res.text();let data:any={};try{data=text?JSON.parse(text):{};}catch{data={error:'Invalid server response'};}if(!res.ok)throw new ApiError(res.status,String(data.error??`Request failed (${res.status})`));return data as T;}
export type FeedPost={id:string;author_id:string;caption:string;visibility:string;created_at:string;content_type?:string;content_warning?:string;location_label?:string|null;allow_comments?:boolean;metadata?:any;like_count:number;comment_count:number;save_count:number;share_count:number;liked_by_me?:boolean;saved_by_me?:boolean;username?:string;display_name?:string;avatar_url?:string|null;media:Array<{type:'image'|'video';uri:string;storageKey?:string;alt?:string;width?:number|null;height?:number|null;durationMs?:number|null}>};
export async function getFeed(mode:'for_you'|'following'|'latest'='for_you',before?:string){return api<{items:FeedPost[];nextCursor?:string|null}>(`/v1/feed?mode=${mode}${before?`&before=${encodeURIComponent(before)}`:''}`);}
export async function recordExposure(items:any[]){return api('/v1/recommendation/exposure',{method:'POST',body:JSON.stringify({items})});}
export async function toggleReaction(postId:string){return api<{active:boolean;reaction:string|null}>(`/v1/posts/${encodeURIComponent(postId)}/reaction`,{method:'POST'});}
export async function toggleSave(postId:string){return api<{saved:boolean}>(`/v1/posts/${encodeURIComponent(postId)}/save`,{method:'POST'});}
export async function addComment(postId:string,body:string,parentId?:string){return api<{id:string;createdAt:string}>(`/v1/posts/${encodeURIComponent(postId)}/comments`,{method:'POST',body:JSON.stringify({body,parentId})});}
export async function getComments(postId:string,limit=50,before?:string){return api<{comments:Array<any>;nextBefore:string|null}>(`/v1/posts/${encodeURIComponent(postId)}/comments?limit=${Math.min(Math.max(limit,1),100)}${before?`&before=${encodeURIComponent(before)}`:''}`);}
export async function getCommentReplies(commentId:string,limit=50,before?:string){return api<{comments:Array<any>;nextBefore:string|null}>(`/v1/comments/${encodeURIComponent(commentId)}/replies?limit=${Math.min(Math.max(limit,1),100)}${before?`&before=${encodeURIComponent(before)}`:''}`);}
export async function getPoll(postId:string){return api<any>(`/v1/posts/${encodeURIComponent(postId)}/poll`);}
export async function votePoll(postId:string,optionId:string){return api<{ok:boolean}>(`/v1/posts/${encodeURIComponent(postId)}/poll`,{method:'POST',body:JSON.stringify({optionId})});}
export async function repostPost(postId:string,quote=''){return api<{reposted:boolean}>(`/v1/posts/${encodeURIComponent(postId)}/repost`,{method:'POST',body:JSON.stringify({quote})});}
export type FeedbackObjectType='post'|'reel'|'product'|'creator'|'topic';export type FeedbackSignal='more_like_this'|'less_like_this'|'not_interested'|'hide'|'mute'|'report';
export async function recommendationFeedback(input:{objectType:FeedbackObjectType;objectId:string;signal:FeedbackSignal;context?:string}){return api<{ok:boolean}>('/v1/recommendation/feedback',{method:'POST',body:JSON.stringify(input)});}
export async function removeRecommendationFeedback(input:{objectType:FeedbackObjectType;objectId:string;signal:FeedbackSignal;context?:string}){return api<{ok:boolean}>('/v1/recommendation/feedback',{method:'DELETE',body:JSON.stringify(input)});}
export async function setHiddenTopic(topic:string,hidden=true){return api<{topic:string;hidden:boolean}>('/v1/feed/hidden-topics',{method:hidden?'POST':'DELETE',body:JSON.stringify({topic})});}
export async function listHiddenTopics(){return api<{topics:Array<{topic:string;created_at:string}>}>('/v1/feed/hidden-topics');}
export async function getFeedPreferences(){return api<{mode:'for_you'|'following'|'latest';topic:string|null;updated_at:string|null}>('/v1/feed/preferences');}
export async function setFeedPreferences(input:{mode?:'for_you'|'following'|'latest';topic?:string|null}){return api<{mode:'for_you'|'following'|'latest';topic:string|null;updated_at:string}>('/v1/feed/preferences',{method:'PUT',body:JSON.stringify(input)});}
export async function resetFeed(){return api<{ok:boolean;resetAt:string}>('/v1/feed/reset',{method:'POST'});}
export async function getFeedTopics(){return api<{topics:Array<{topic:string;count:number}>}>('/v1/feed/topics');}
export async function getReels(){return api<{items:Array<any>}>('/v1/reels/recommended');}
export async function startReelWatchSession(clientSessionId:string){return api<{sessionId:string}>('/v1/reels/watch-sessions',{method:'POST',body:JSON.stringify({clientSessionId})});}
export async function recordReelWatchEvents(sessionId:string,events:Array<any>){return api<{accepted:number;acceptedClientEventIds:string[]}>('/v1/reels/watch-events',{method:'POST',body:JSON.stringify({sessionId,events})});}
export async function endReelWatchSession(sessionId:string){return api(`/v1/reels/watch-sessions/${encodeURIComponent(sessionId)}`,{method:'DELETE'});}
export async function getReelPreferences(){return api<{preferences:any}>('/v1/reels/preferences');}
export async function updateReelPreferences(input:Record<string,unknown>){return api('/v1/reels/preferences',{method:'PUT',body:JSON.stringify(input)});}
export async function reelCreatorFeedback(creatorId:string,signal:'hide'|'mute'|'not_interested'|'report'){return api(`/v1/reels/creators/${encodeURIComponent(creatorId)}/feedback`,{method:'POST',body:JSON.stringify({signal})});}
export async function getReelAudio(q=''){return api<{audio:any[]}>(`/v1/reels/audio?q=${encodeURIComponent(q)}`);}
export async function getRelatedReels(postId:string){return api<{items:any[]}>(`/v1/reels/related?postId=${encodeURIComponent(postId)}`);}
export async function getDiscoveryResults(q:string,kind='all',sort='relevance',limit=20){return api<{query:string;people:any[];posts:any[];videos:any[];products:any[];shops:any[];topics:any[];suggestions:string[];sort:string}>(`/v1/discovery/results?q=${encodeURIComponent(q)}&kind=${encodeURIComponent(kind)}&sort=${encodeURIComponent(sort)}&limit=${limit}`);}
export type DiscoveryResult={query:string;people:any[];posts:any[];videos:any[];products:any[];shops:any[];topics:any[];suggestions:string[];sort:string};
export async function searchDiscovery(q:string,kind='all',limit=20){return api<DiscoveryResult>(`/v1/discovery/search?q=${encodeURIComponent(q)}&kind=${encodeURIComponent(kind)}&limit=${limit}`);}
export async function getDiscoveryFeed(params:{topic?:string;category?:string;limit?:number}={}){const qs=new URLSearchParams();if(params.topic)qs.set('topic',params.topic);if(params.category)qs.set('category',params.category);qs.set('limit',String(params.limit??20));return api<{topic:string;category:string;items:any[]}>(`/v1/discovery/feed?${qs.toString()}`);}
export async function getRecentSearches(){return api<{items:Array<{query:string;last_used_at:string}>}>('/v1/discovery/recent-searches');}
export async function clearRecentSearches(){return api('/v1/discovery/recent-searches',{method:'DELETE'});}
export async function getSavedSearches(){return api<{items:Array<{id:string;query:string;kind:string;created_at:string}>}>('/v1/discovery/saved-searches');}
export async function saveSearch(query:string,kind='all'){return api('/v1/discovery/saved-searches',{method:'POST',body:JSON.stringify({query,kind})});}
export async function deleteSavedSearch(id:string){return api(`/v1/discovery/saved-searches/${encodeURIComponent(id)}`,{method:'DELETE'});}
export async function getDiscoveryCategories(){return api<{categories:any[]}>('/v1/discovery/categories');}
export async function getDiscoveryPreferences(){return api<{preferences:any}>('/v1/discovery/preferences');}
export async function updateDiscoveryPreferences(input:Record<string,unknown>){return api('/v1/discovery/preferences',{method:'PUT',body:JSON.stringify(input)});}
export async function getCommerceProduct(productId:string){return api<any>(`/v1/commerce/products/${encodeURIComponent(productId)}`);}
export async function setSavedForLater(productId:string,quantity:number,saved:boolean){return api<{saved:boolean}>(`/v1/commerce/products/${encodeURIComponent(productId)}/saved-for-later`,{method:saved?'POST':'DELETE',body:JSON.stringify({quantity})});}
export async function getSavedForLater(){return api<{items:any[]}>('/v1/commerce/saved-for-later');}
export async function getAdvancedOrder(orderId:string){return api<any>(`/v1/commerce/orders/${encodeURIComponent(orderId)}`);}
export async function reportOrderIssue(orderId:string,issueType:string,details=''){return api(`/v1/commerce/orders/${encodeURIComponent(orderId)}/issues`,{method:'POST',body:JSON.stringify({issueType,details})});}
export async function requestExchange(orderId:string,productId:string,notes=''){return api(`/v1/commerce/orders/${encodeURIComponent(orderId)}/exchange`,{method:'POST',body:JSON.stringify({productId,notes})});}
export async function getCheckoutState(key:string){return api<any>(`/v1/checkout/state?key=${encodeURIComponent(key)}`);}
export async function prepareCheckout(key:string){return api<any>('/v1/checkout/prepare',{method:'POST',body:JSON.stringify({idempotencyKey:key})});}
export async function setCheckoutAddress(sessionId:string,addressId:string){return api<any>(`/v1/checkout/${encodeURIComponent(sessionId)}/address`,{method:'PUT',body:JSON.stringify({addressId})});}
export async function setCheckoutDelivery(sessionId:string,input:{code:string;feeMinor:number;minDays?:number;maxDays?:number}){return api<any>(`/v1/checkout/${encodeURIComponent(sessionId)}/delivery`,{method:'PUT',body:JSON.stringify(input)});}
export async function setCheckoutPaymentMethod(sessionId:string,method:string){return api<any>(`/v1/checkout/${encodeURIComponent(sessionId)}/payment-method`,{method:'PUT',body:JSON.stringify({method})});}
export async function finalizeCheckout(sessionId:string){return api<any>(`/v1/checkout/${encodeURIComponent(sessionId)}/finalize`,{method:'POST'});}
export async function createPaymentIntent(orderId:string,idempotencyKey:string){return api<any>('/v1/payments/intents',{method:'POST',body:JSON.stringify({orderId,idempotencyKey})});}
export async function getAdForViewer(context='feed'){return api<any>(`/v1/ads/serve?context=${encodeURIComponent(context)}`);}
export async function reportAdViewerFeedback(creativeId:string,signal:'hide'|'not_relevant'|'report'|'why_this'){return api<any>(`/v1/ads/serve/${encodeURIComponent(creativeId)}/feedback`,{method:'POST',body:JSON.stringify({signal})});}
export async function getMarketCategories(){return api<any>('/v1/market/categories');}
export async function getMarketProducts(params:any={}){const q=new URLSearchParams();Object.entries(params).forEach(([k,v])=>{if(v!==undefined&&v!==null&&v!=='')q.set(k,String(v));});return api<any>(`/v1/market/products?${q.toString()}`);}
export async function getMarketProductDetail(productId:string){return api<any>(`/v1/market/products/${encodeURIComponent(productId)}`);}
export async function getSavedProducts(limit=50,before?:string){return api<any>(`/v1/market/saved-products?limit=${limit}${before?`&before=${encodeURIComponent(before)}`:''}`);}
export async function setProductWishlist(productId:string,saved:boolean){return api<any>(`/v1/market/products/${encodeURIComponent(productId)}/wishlist`,{method:saved?'POST':'DELETE'});}
export async function createProductReview(productId:string,input:any){return api<any>(`/v1/market/products/${encodeURIComponent(productId)}/reviews`,{method:'POST',body:JSON.stringify(input)});}
export async function askProductQuestion(productId:string,question:string){return api<any>(`/v1/market/products/${encodeURIComponent(productId)}/questions`,{method:'POST',body:JSON.stringify({question})});}
export async function answerProductQuestion(questionId:string,answer:string){return api<any>(`/v1/market/questions/${encodeURIComponent(questionId)}/answers`,{method:'POST',body:JSON.stringify({answer})});}
export async function getRelatedProducts(productId:string,limit=12){return api<any>(`/v1/market/products/${encodeURIComponent(productId)}/related?limit=${limit}`);}
export async function getAddresses(){return api<any>('/v1/market/addresses');}
export async function saveAddress(input:any){return api<any>('/v1/market/addresses',{method:'POST',body:JSON.stringify(input)});}
export async function deleteAddress(id:string){return api<any>(`/v1/market/addresses/${encodeURIComponent(id)}`,{method:'DELETE'});}
export async function getDeliveryEstimate(productId:string,addressId?:string){return api<any>(`/v1/market/products/${encodeURIComponent(productId)}/delivery${addressId?`?addressId=${encodeURIComponent(addressId)}`:''}`);}
export async function requestReturn(orderId:string,reason:string,notes=''){return api<any>(`/v1/market/orders/${encodeURIComponent(orderId)}/returns`,{method:'POST',body:JSON.stringify({reason,notes})});}
export async function getReturns(orderId?:string){return api<any>(`/v1/market/returns${orderId?`?orderId=${encodeURIComponent(orderId)}`:''}`);}
export async function openOrderSupport(orderId:string,subject:string){return api<any>(`/v1/market/orders/${encodeURIComponent(orderId)}/support`,{method:'POST',body:JSON.stringify({subject})});}
export async function getSellerCommerceSettings(shopId:string){return api<any>(`/v1/seller/shops/${encodeURIComponent(shopId)}/commerce-settings`);}
export async function updateSellerCommerceSettings(shopId:string,input:any){return api<any>(`/v1/seller/shops/${encodeURIComponent(shopId)}/commerce-settings`,{method:'PUT',body:JSON.stringify(input)});}
export async function getProfessionalProfile(){return api<any>('/v1/account/professional');}
export async function updateProfessionalProfile(input:any){return api<any>('/v1/account/professional',{method:'PUT',body:JSON.stringify(input)});}
export async function getBusinessVerification(){return api<any>('/v1/business/verification');}
export async function requestBusinessVerification(input:any){return api<any>('/v1/business/verification',{method:'POST',body:JSON.stringify(input)});}
export async function getAdDeliveryControls(){return api<any>('/v1/ads/delivery-controls');}
export async function updateAdDeliveryControls(input:any){return api<any>('/v1/ads/delivery-controls',{method:'PUT',body:JSON.stringify(input)});}
export async function getAdCampaigns(){return api<any>('/v1/ads/campaigns');}
export async function createAdCampaign(input:any){return api<any>('/v1/ads/campaigns',{method:'POST',body:JSON.stringify(input)});}
export async function createAdCreative(campaignId:string,input:any){return api<any>(`/v1/ads/campaigns/${encodeURIComponent(campaignId)}/creatives`,{method:'POST',body:JSON.stringify(input)});}
export async function reportAdFeedback(creativeId:string,signal:'hide'|'not_relevant'|'report'|'why_this'){return api<any>(`/v1/ads/creatives/${encodeURIComponent(creativeId)}/feedback`,{method:'POST',body:JSON.stringify({signal})});}
export type Notification={id:string;actor_id:string|null;type:string;object_id:string|null;grouped_key:string|null;metadata:Record<string,unknown>;category?:string;read_at:string|null;created_at:string;actor_username?:string|null;actor_display_name?:string|null;actor_avatar_url?:string|null};
export type NotificationPreferences={social:boolean;mentions_replies:boolean;follows:boolean;commerce_orders:boolean;security:boolean;system:boolean;digest_enabled:boolean;digest_frequency:'daily'|'weekly';quiet_enabled:boolean;quiet_start_minute:number;quiet_end_minute:number;quiet_timezone:string;updated_at:string|null};
export async function getNotifications(limit=30,before?:string,category='all'){return api<{notifications:Notification[];nextBefore:string|null}>(`/v1/notifications?limit=${Math.min(Math.max(limit,1),100)}&category=${encodeURIComponent(category)}${before?`&before=${encodeURIComponent(before)}`:''}`);}
export async function markAllNotificationsRead(){return api<any>('/v1/notifications/read-all',{method:'POST'});}
export async function markNotificationRead(id:string){return api<any>(`/v1/notifications/${encodeURIComponent(id)}/read`,{method:'POST'});}
export async function getNotificationPreferences(){return api<{preferences:NotificationPreferences}>('/v1/notifications/preferences');}
export async function updateNotificationPreferences(input:Record<string,unknown>){return api<{preferences:NotificationPreferences}>('/v1/notifications/preferences',{method:'PUT',body:JSON.stringify(input)});}
export async function getNotificationDigest(){return api<any>('/v1/notifications/digest');}
export async function getPermissions(){return api<any>('/v1/privacy/permissions');}
export async function getPrivacyAudit(){return api<any>('/v1/privacy/audit');}
export async function getBlockedUsers(){return api<any>('/v1/privacy/blocked');}
export async function getMutedUsers(){return api<any>('/v1/privacy/muted');}
export async function setBlocked(userId:string,blocked:boolean){return api<any>('/v1/safety/block',{method:blocked?'POST':'DELETE',body:JSON.stringify({targetUserId:userId})});}
export async function setMuted(userId:string,muted:boolean){return api<any>('/v1/safety/mute',{method:muted?'POST':'DELETE',body:JSON.stringify({targetUserId:userId})});}
export async function setRestricted(userId:string,restricted:boolean){return api<any>('/v1/safety/restrict',{method:restricted?'POST':'DELETE',body:JSON.stringify({targetUserId:userId})});}
export async function getSafetyState(targetUserId?:string){return api<any>(`/v1/safety/state${targetUserId?`?targetUserId=${encodeURIComponent(targetUserId)}`:''}`);}
export async function reportTarget(target:any,reason:string,details=''){return api<any>('/v1/safety/report',{method:'POST',body:JSON.stringify({target,reason,details})});}
export async function getSafetyCases(){return api<any>('/v1/safety/cases');}
export async function addReportEvidence(caseId:string,evidence:any){return api<any>(`/v1/safety/cases/${encodeURIComponent(caseId)}/evidence`,{method:'POST',body:JSON.stringify(evidence)});}
export async function submitSafetyAppeal(caseId:string,reason:string){return api<any>(`/v1/safety/cases/${encodeURIComponent(caseId)}/appeal`,{method:'POST',body:JSON.stringify({reason})});}
export async function getModerationNotices(){return api<any>('/v1/safety/notices');}
export async function getAccountExperiencePreferences(){return api<any>('/v1/account/experience');}
export async function updateAccountExperiencePreferences(input:any){return api<any>('/v1/account/experience',{method:'PUT',body:JSON.stringify(input)});}
export async function getAccountContacts(){return api<any>('/v1/account/contacts');}
export async function updateAccountContacts(input:any){return api<any>('/v1/account/contacts',{method:'PUT',body:JSON.stringify(input)});}
export async function getSecuritySessions(){return api<any>('/v1/auth/sessions');}
export async function revokeSecuritySession(id:string){return api<any>(`/v1/auth/sessions/${encodeURIComponent(id)}/revoke`,{method:'POST'});}
export async function revokeAllSecuritySessions(){return api<any>('/v1/auth/sessions/revoke-all',{method:'POST'});}
export async function getSecurityAlerts(){return api<any>('/v1/security/alerts');}
export async function acknowledgeSecurityAlert(id:string){return api<any>(`/v1/security/alerts/${encodeURIComponent(id)}/ack`,{method:'POST'});}
export async function getSecurityEvents(){return api<any>('/v1/security/events');}
export async function secureAccount(){return api<any>('/v1/security/secure-account',{method:'POST'});}
