import { query, withTransaction } from './db.js';
const clamp=(v:number,min:number,max:number)=>Math.min(Math.max(Math.trunc(v),min),max);
const clean=(v:unknown,max:number)=>String(v??'').trim().slice(0,max);

export async function getCommerceProduct(userId:string,productId:string){
 const r=await query(`SELECT p.*,s.name shop_name,s.description shop_description,s.owner_id seller_id,u.username seller_username,COALESCE(sr.rating,0)::float seller_rating,COALESCE(sr.review_count,0)::int seller_review_count,COALESCE(sr.fulfilled_count,0)::int fulfilled_count,COALESCE(sr.response_rate,0)::float response_rate,COALESCE(pr.quality_score,0)::float product_quality_score,COALESCE(pr.fulfillment_score,0)::float product_fulfillment_score FROM products p JOIN shops s ON s.id=p.shop_id JOIN users u ON u.id=s.owner_id LEFT JOIN seller_reputation sr ON sr.seller_id=s.owner_id LEFT JOIN product_reputation pr ON pr.product_id=p.id WHERE p.id=$1 LIMIT 1`,[productId]);if(!r.rows[0])return null;
 const [media,variants,reviews,questions,wish,ship,related,priceHistory]=await Promise.all([
  query(`SELECT id,storage_key,media_type,sort_order,alt_text,duration_ms FROM product_media_metadata WHERE product_id=$1 ORDER BY sort_order ASC,created_at ASC`,[productId]),
  query(`SELECT id,name,sku,price_minor,inventory,attributes,active FROM product_variants WHERE product_id=$1 AND active=true ORDER BY created_at ASC`,[productId]),
  query(`SELECT r.id,r.rating,r.title,r.body,r.order_id IS NOT NULL verified_purchase,r.created_at,u.username FROM product_reviews r JOIN users u ON u.id=r.user_id WHERE r.product_id=$1 AND r.status='published' ORDER BY r.created_at DESC LIMIT 50`,[productId]),
  query(`SELECT q.id,q.question,q.created_at,u.username,(SELECT COALESCE(json_agg(json_build_object('id',a.id,'answer',a.answer,'createdAt',a.created_at,'username',ua.username) ORDER BY a.created_at ASC),'[]'::json) FROM product_answers a JOIN users ua ON ua.id=a.user_id WHERE a.question_id=q.id) answers FROM product_questions q JOIN users u ON u.id=q.user_id WHERE q.product_id=$1 ORDER BY q.created_at DESC LIMIT 50`,[productId]),
  query('SELECT 1 FROM product_wishlists WHERE user_id=$1 AND product_id=$2',[userId,productId]),
  query('SELECT origin_region,shipping_text,delivery_min_days,delivery_max_days,free_shipping_threshold_minor FROM product_shipping_profiles WHERE product_id=$1',[productId]),
  query(`SELECT p2.id,p2.title,p2.price_minor,p2.currency,p2.inventory,p2.category,s2.name shop_name,COALESCE(AVG(r.rating),0)::float rating FROM products p JOIN products p2 ON p2.id<>p.id AND p2.status='active' AND (p2.category=p.category OR p2.shop_id=p.shop_id) JOIN shops s2 ON s2.id=p2.shop_id LEFT JOIN product_reviews r ON r.product_id=p2.id AND r.status='published' WHERE p.id=$1 GROUP BY p2.id,s2.name ORDER BY CASE WHEN p2.category=p.category THEN 0 ELSE 1 END,p2.created_at DESC LIMIT 16`,[productId]),
  query('SELECT price_minor,currency,recorded_at FROM product_price_history WHERE product_id=$1 ORDER BY recorded_at DESC LIMIT 20',[productId])
 ]); return {product:r.rows[0],media:media.rows,variants:variants.rows,reviews:reviews.rows,questions:questions.rows,saved:Boolean(wish.rowCount),shipping:ship.rows[0]??null,related:related.rows,priceHistory:priceHistory.rows};
}

export async function setSavedForLater(userId:string,productId:string,quantity:number,saved:boolean){if(saved){if(!Number.isSafeInteger(quantity)||quantity<1)throw new Error('Invalid quantity');await query(`INSERT INTO saved_for_later(user_id,product_id,quantity) VALUES($1,$2,$3) ON CONFLICT(user_id,product_id) DO UPDATE SET quantity=EXCLUDED.quantity`,[userId,productId,quantity]);}else await query('DELETE FROM saved_for_later WHERE user_id=$1 AND product_id=$2',[userId,productId]);return{saved};}
export async function listSavedForLater(userId:string){const r=await query(`SELECT sfl.product_id,sfl.quantity,p.title,p.price_minor,p.currency,p.inventory,p.status,p.category FROM saved_for_later sfl JOIN products p ON p.id=sfl.product_id WHERE sfl.user_id=$1 ORDER BY sfl.created_at DESC`,[userId]);return{items:r.rows};}

export async function listOrderDetail(buyerId:string,orderId:string){
 const r=await query(`SELECT o.id,o.seller_id,o.total_minor,o.currency,o.status,o.created_at,o.updated_at,o.shipping_minor,o.address_id,of.shipping_address_snapshot,of.tracking_number,of.carrier,of.estimated_delivery_at,of.shipped_at,of.delivered_at,of.shipment_status,of.delivery_notes,COALESCE(json_agg(json_build_object('productId',ol.product_id,'quantity',ol.quantity,'unitPriceMinor',ol.unit_price_minor,'title',p.title)) FILTER(WHERE ol.product_id IS NOT NULL),'[]'::json) items FROM orders o LEFT JOIN order_lines ol ON ol.order_id=o.id LEFT JOIN products p ON p.id=ol.product_id LEFT JOIN order_fulfillment of ON of.order_id=o.id WHERE o.id=$1 AND o.buyer_id=$2 GROUP BY o.id,of.order_id LIMIT 1`,[orderId,buyerId]);if(!r.rows[0])return null;const [events,returns,issues,payments,reviews]=await Promise.all([query('SELECT id,from_status,to_status,note,created_at FROM order_status_events WHERE order_id=$1 ORDER BY created_at ASC',[orderId]),query('SELECT * FROM order_returns WHERE order_id=$1 AND buyer_id=$2 ORDER BY created_at DESC',[orderId,buyerId]),query('SELECT * FROM order_issue_reports WHERE order_id=$1 AND user_id=$2 ORDER BY created_at DESC',[orderId,buyerId]),query('SELECT id,provider,provider_reference,status,amount_minor,currency,failure_code,failure_message,created_at,updated_at FROM order_payments WHERE order_id=$1 ORDER BY created_at DESC',[orderId]),query(`SELECT r.id,r.product_id,r.rating,r.title,r.body,r.created_at FROM product_reviews r WHERE r.user_id=$1 AND r.order_id=$2 ORDER BY r.created_at DESC`,[buyerId,orderId])]);return{order:r.rows[0],timeline:events.rows,returns:returns.rows,issues:issues.rows,payments:payments.rows,reviews:reviews.rows};
}
export async function reportOrderIssue(userId:string,orderId:string,issueType:string,details=''){const own=await query('SELECT 1 FROM orders WHERE id=$1 AND buyer_id=$2',[orderId,userId]);if(!own.rowCount)throw new Error('Order not found');const type=clean(issueType,80);if(!type)throw new Error('Issue type required');const r=await query(`INSERT INTO order_issue_reports(order_id,user_id,issue_type,details) VALUES($1,$2,$3,$4) RETURNING *`,[orderId,userId,type,clean(details,4000)]);return r.rows[0];}
export async function requestExchange(userId:string,orderId:string,productId:string,notes=''){const own=await query(`SELECT 1 FROM orders o JOIN order_lines l ON l.order_id=o.id WHERE o.id=$1 AND o.buyer_id=$2 AND l.product_id=$3`,[orderId,userId,productId]);if(!own.rowCount)throw new Error('Product not found in order');const r=await query(`INSERT INTO order_exchanges(order_id,requested_product_id,notes) VALUES($1,$2,$3) RETURNING *`,[orderId,productId,clean(notes,2000)]);return r.rows[0];}
