export type RetrievalKind='people'|'posts'|'products';
export type DiscoveryCandidate={id:string;kind:RetrievalKind;lexical:number;exact:number;prefix:number;popularity:number;freshness:number;personal:number;final:number};
type RetrievalRow={id:string;kind:RetrievalKind;text:string;exact?:number;prefix?:number;popularity?:number;freshness?:number;personal?:number};
const clamp=(n:number)=>Math.max(0,Math.min(1,n));
const trigrams=(value:string)=>{const s=`  ${value.toLowerCase()} `;const out:string[]=[];for(let i=0;i<s.length-2;i++)out.push(s.slice(i,i+3));return out;};
const jaccard=(a:string,b:string)=>{const A=new Set(trigrams(a)),B=new Set(trigrams(b));if(!A.size&&!B.size)return 1;let hit=0;for(const x of A)if(B.has(x))hit++;return hit/Math.max(1,A.size+B.size-hit);};
export function rankDiscoveryCandidates(rows:RetrievalRow[],queryText:string){const q=queryText.trim().toLowerCase();return rows.map(row=>{const lexical=clamp(.55*jaccard(row.text,q)+.25*clamp(Number(row.prefix??0))+.20*clamp(Number(row.exact??0)));const score=clamp(.42*lexical+.15*clamp(Number(row.personal??0))+.15*clamp(Number(row.popularity??0))+.18*clamp(Number(row.freshness??0))+.10*clamp(Number(row.exact??0)));return{...row,lexical,exact:clamp(Number(row.exact??0)),prefix:clamp(Number(row.prefix??0)),popularity:clamp(Number(row.popularity??0)),freshness:clamp(Number(row.freshness??0)),personal:clamp(Number(row.personal??0)),final:score};}).sort((a,b)=>b.final-a.final||a.id.localeCompare(b.id));}
export async function retrieveDiscovery(userId:string,rawQuery:string,kind:'all'|'people'|'posts'|'products'='all',limit=20){const {query}=await import('./db.js');const q=rawQuery.trim().replace(/\s+/g,' ');if(!q)return{query:'',people:[],posts:[],products:[]};const size=Math.min(Math.max(Math.trunc(limit),1),50),like=`%${q}%`,prefix=`${q}%`;
 const people=kind==='posts'||kind==='products'?[]:(await query(`SELECT u.id,u.username,u.display_name,COALESCE(p.avatar_url,'') avatar_url,COALESCE((SELECT count(*)::int FROM follows f WHERE f.followed_id=u.id AND f.state='following'),0) followers,EXISTS(SELECT 1 FROM follows me WHERE me.follower_id=$1 AND me.followed_id=u.id AND me.state='following') following,CASE WHEN lower(u.username)=lower($2) THEN 1 ELSE 0 END exact,CASE WHEN lower(u.username) LIKE lower($3) THEN 1 ELSE 0 END prefix,LEAST(1,COALESCE((SELECT count(*) FROM follows f2 WHERE f2.followed_id=u.id AND f2.state='following'),0)/10000.0) popularity,.5 freshness,CASE WHEN EXISTS(SELECT 1 FROM follows me2 WHERE me2.follower_id=$1 AND me2.followed_id=u.id AND me2.state='following') THEN .7 ELSE .1 END personal,u.username text FROM users u LEFT JOIN profiles p ON p.user_id=u.id WHERE lower(u.username) LIKE lower($4) OR lower(COALESCE(p.display_name,'')) LIKE lower($4) ORDER BY exact DESC,prefix DESC,followers DESC LIMIT $5`,[userId,q,prefix,like,size*4])).rows as RetrievalRow[];
 const posts=kind==='people'||kind==='products'?[]:(await query(`SELECT p.id,p.author_id,p.caption,p.created_at,u.username,u.display_name,COALESCE(pf.avatar_url,'') avatar_url,COALESCE((SELECT count(*)::int FROM post_reactions r WHERE r.post_id=p.id),0) likes,CASE WHEN lower(p.caption)=lower($2) THEN 1 ELSE 0 END exact,CASE WHEN lower(p.caption) LIKE lower($3) THEN 1 ELSE 0 END prefix,LEAST(1,COALESCE((SELECT count(*) FROM post_reactions r2 WHERE r2.post_id=p.id),0)/10000.0) popularity,GREATEST(0,1-EXTRACT(EPOCH FROM(now()-p.created_at))/(30*86400.0)) freshness,.1 personal,p.caption text FROM posts p JOIN users u ON u.id=p.author_id LEFT JOIN profiles pf ON pf.user_id=u.id WHERE p.deleted_at IS NULL AND p.visibility='public' AND lower(p.caption) LIKE lower($1) LIMIT $4`,[like,q,prefix,size*4])).rows as RetrievalRow[];
 const products=kind==='people'||kind==='posts'?[]:(await query(`SELECT pr.id,pr.title,pr.description,pr.price_minor,pr.currency,pr.inventory,s.owner_id seller_id,s.name shop_name,CASE WHEN lower(pr.title)=lower($2) THEN 1 ELSE 0 END exact,CASE WHEN lower(pr.title) LIKE lower($3) THEN 1 ELSE 0 END prefix,.25 popularity,GREATEST(0,1-EXTRACT(EPOCH FROM(now()-pr.created_at))/(90*86400.0)) freshness,.1 personal,pr.title||' '||pr.description||' '||s.name text FROM products pr JOIN shops s ON s.id=pr.shop_id WHERE pr.status='active' AND s.status='active' AND pr.inventory>0 AND (lower(pr.title) LIKE lower($1) OR lower(pr.description) LIKE lower($1) OR lower(s.name) LIKE lower($1)) LIMIT $4`,[like,q,prefix,size*4])).rows as RetrievalRow[];
 return{query:q,people:rankDiscoveryCandidates(people,q).slice(0,size),posts:rankDiscoveryCandidates(posts,q).slice(0,size),products:rankDiscoveryCandidates(products,q).slice(0,size)};}
