import { createServer, type IncomingMessage, type ServerResponse } from 'node:http';
import { config } from './config.js';
import { authenticate, changePassword, createReauthGrant, listSessions, login, refresh, requestOtp, requestPasswordReset, resetPassword, revoke, revokeAll, revokeSession, signup, verifyOtp } from './auth-service.js';
import { health } from './health.js';
import { addComment, createPost, follow, getFeed, getProfile, setFollowState, toggleReaction, toggleSave, unfollow } from './social-service.js';
import { recordFeedEvents } from './feed-events-service.js';
import { getRecommendedPosts } from './recommendation-service.js';
import { assignRecommendationVariant, recordRecommendationExposure, upsertRecommendationMetric } from './recommendation-experiment-service.js';
import { evaluateRecommendationWindow } from './ranking-evaluation-service.js';
import { startReelWatchSession, endReelWatchSession, recordReelWatchEvents, getReelCandidates } from './reels-service.js';
import { addCartItem, createProduct, getCart, getProduct, listSellerProducts, placeOrder, updateCartItem } from './commerce-service.js';
import { getRecommendedProducts, recordCommerceEvent } from './commerce-recommendation-service.js';
import { listNotifications, markAllNotificationsRead, markNotificationRead, unreadNotificationCount } from './notification-service.js';
import { searchDiscovery, type DiscoveryKind } from './discovery-service.js';
import { createConversation, listConversations, listMessages, markConversationRead, sendEncryptedMessage, upsertDeviceKeyBundle, listDeviceKeyBundles } from './messaging-service.js';
import { blockUser, getSafetyState, muteUser, reportContent, unblockUser, unmuteUser } from './safety-service.js';
import { completeUpload, createUploadIntent, getMediaAsset, getPlaybackUrl } from './media-service.js';
import { getPrivacySettings, updatePrivacySettings } from './privacy-service.js';
const json=(res:ServerResponse,status:number,body:unknown)=>{res.statusCode=status;res.setHeader('Content-Type','application/json; charset=utf-8');res.setHeader('Cache-Control','no-store');res.setHeader('X-Content-Type-Options','nosniff');res.setHeader('Referrer-Policy','no-referrer');res.end(JSON.stringify(body));};
async function body(req:IncomingMessage):Promise<any>{let data='';for await(const chunk of req){data+=chunk;if(Buffer.byteLength(data)>256*1024)throw new Error('Request too large');}return data?JSON.parse(data):{};}
function bearer(req:IncomingMessage){const v=req.headers.authorization;return v?.startsWith('Bearer ')?v.slice(7):null;}function cookie(req:IncomingMessage,name:string){const x=(req.headers.cookie??'').split(';').map(v=>v.trim()).find(v=>v.startsWith(`${name}=`));return x?decodeURIComponent(x.slice(name.length+1)):null;}function sessionCookie(req:IncomingMessage){return cookie(req,config.secureCookies?'__Host-drustpoll_session':'drustpoll_session');}function setCookie(res:ServerResponse,token:string,maxAge=1800){const secure=config.secureCookies?'; Secure':'';const name=config.secureCookies?'__Host-drustpoll_session':'drustpoll_session';res.setHeader('Set-Cookie',`${name}=${encodeURIComponent(token)}; Path=/; HttpOnly; SameSite=Strict${secure}; Max-Age=${maxAge}`);}function clearCookie(res:ServerResponse){setCookie(res,'',0);}async function auth(req:IncomingMessage){return authenticate(bearer(req)??sessionCookie(req)??'');}
const server=createServer(async(req,res)=>{try{
if(req.method==='OPTIONS'){res.statusCode=204;res.end();return;}const url=new URL(req.url??'/',`http://${req.headers.host??'localhost'}`);const ip=req.headers['x-forwarded-for']?.toString().split(',')[0]?.trim()??req.socket.remoteAddress??'unknown';
if(req.method==='GET'&&url.pathname==='/health')return json(res,200,await health());
if(req.method==='POST'&&url.pathname==='/v1/auth/signup'){const r=await signup(await body(req),ip);setCookie(res,r.token);return json(res,201,r);}if(req.method==='POST'&&url.pathname==='/v1/auth/login'){const r=await login(await body(req),ip);setCookie(res,r.token);return json(res,200,r);}if(req.method==='POST'&&url.pathname==='/v1/auth/refresh'){const r=await refresh(String((await body(req)).refreshToken??''),ip);setCookie(res,r.token);return json(res,200,r);}if(req.method==='POST'&&url.pathname==='/v1/auth/password/forgot')return json(res,202,await requestPasswordReset(String((await body(req)).identifier??''),ip));if(req.method==='POST'&&url.pathname==='/v1/auth/password/reset'){const i=await body(req);return json(res,200,await resetPassword(String(i.token??''),String(i.newPassword??'')));}if(req.method==='POST'&&url.pathname==='/v1/auth/logout'){await revoke(bearer(req)??sessionCookie(req)??'');clearCookie(res);return json(res,200,{ok:true});}
const session=await auth(req);if(!session)return json(res,401,{error:'Unauthenticated'});if(req.method==='GET'&&url.pathname==='/v1/auth/me')return json(res,200,{session});if(req.method==='GET'&&url.pathname==='/v1/auth/sessions')return json(res,200,{sessions:await listSessions(session.userId,session.sessionId)});
if(req.method==='GET'&&url.pathname==='/v1/privacy')return json(res,200,{privacy:await getPrivacySettings(session.userId)});if(req.method==='PUT'&&url.pathname==='/v1/privacy')return json(res,200,{privacy:await updatePrivacySettings(session.userId,await body(req))});
if(req.method==='GET'&&url.pathname==='/v1/discovery/search'){const k=(url.searchParams.get('kind')??'all') as DiscoveryKind;if(!['all','people','posts','products'].includes(k))return json(res,400,{error:'Invalid search kind'});return json(res,200,await searchDiscovery(session.userId,url.searchParams.get('q')??'',k,Number(url.searchParams.get('limit')??20)));}
if(req.method==='POST'&&url.pathname==='/v1/media/upload-intents'){const i=await body(req);return json(res,201,await createUploadIntent(session.userId,{type:String(i.type??''),mime:String(i.mime??''),filename:i.filename?String(i.filename):undefined,byteSize:Number(i.byteSize??0)}));}const mc=url.pathname.match(/^\/v1\/media\/([^/]+)\/complete$/);if(req.method==='POST'&&mc){const i=await body(req);return json(res,200,await completeUpload(session.userId,mc[1],String(i.detectedMime??''),i.width==null?null:Number(i.width),i.height==null?null:Number(i.height),i.durationMs==null?null:Number(i.durationMs)));}const mp=url.pathname.match(/^\/v1\/media\/([^/]+)\/playback$/);if(req.method==='GET'&&mp)return json(res,200,await getPlaybackUrl(session.userId,mp[1]));
if(req.method==='POST'&&url.pathname==='/v1/reels/watch-sessions'){const i=await body(req);return json(res,201,await startReelWatchSession(session.userId,i.clientSessionId?String(i.clientSessionId):undefined));}const ws=url.pathname.match(/^\/v1\/reels\/watch-sessions\/([^/]+)$/);if(req.method==='DELETE'&&ws)return json(res,200,await endReelWatchSession(session.userId,ws[1]));if(req.method==='POST'&&url.pathname==='/v1/reels/watch-events'){const i=await body(req);return json(res,202,await recordReelWatchEvents(session.userId,String(i.sessionId??''),Array.isArray(i.events)?i.events:[]));}if(req.method==='GET'&&url.pathname==='/v1/reels/recommended')return json(res,200,{items:await getReelCandidates(session.userId,Number(url.searchParams.get('limit')??30))});
if(req.method==='GET'&&url.pathname==='/v1/feed'){const m=url.searchParams.get('mode')==='following'?'following':'for_you';return json(res,200,await getFeed(session.userId,m,Number(url.searchParams.get('limit')??30),url.searchParams.get('before')??undefined));}if(req.method==='GET'&&url.pathname==='/v1/feed/recommended')return json(res,200,{items:await getRecommendedPosts(session.userId,Number(url.searchParams.get('limit')??20))});if(req.method==='POST'&&url.pathname==='/v1/feed/events'){const i=await body(req);return json(res,202,await recordFeedEvents(session.userId,Array.isArray(i.events)?i.events:[]));}
if(req.method==='GET'&&url.pathname==='/v1/shop/recommended')return json(res,200,{items:await getRecommendedProducts(session.userId,Number(url.searchParams.get('limit')??20))});if(req.method==='POST'&&url.pathname==='/v1/shop/events'){const i=await body(req);return json(res,202,await recordCommerceEvent(session.userId,{productId:String(i.productId??''),eventType:i.eventType,dwellMs:i.dwellMs==null?undefined:Number(i.dwellMs),clientEventId:i.clientEventId?String(i.clientEventId):undefined}));}
return json(res,404,{error:'Not found'});}catch(error){const message=error instanceof Error?error.message:'Request failed';const status=/Unauthenticated/i.test(message)?401:/too many/i.test(message)?429:/already in use|invalid|incorrect|expired|required|not found|Cannot|insufficient|inactive|blocked|moderation/i.test(message)?400:500;return json(res,status,{error:message});}});server.listen(config.port,()=>console.log(`Drustpoll API listening on ${config.port}`));
