import { createServer, type IncomingMessage, type ServerResponse } from 'node:http';
import { config } from './config.js';
import { authenticate, listSessions, login, refresh, requestPasswordReset, resetPassword, revoke, revokeAll, revokeSession, signup } from './auth-service.js';
import { health } from './health.js';
import { addComment, createPost, follow, getFeed, getProfile, setFollowState, toggleReaction, toggleSave, unfollow } from './social-service.js';
import { assignRecommendationVariant, recordRecommendationExposure, upsertRecommendationMetric } from './recommendation-experiment-service.js';
import { evaluateRecommendationWindow } from './ranking-evaluation-service.js';
import { startReelWatchSession, endReelWatchSession, recordReelWatchEvents, getReelCandidates } from './reels-service.js';
import { addCartItem, createProduct, getCart, getProduct, listSellerProducts, placeOrder, updateCartItem } from './commerce-service.js';
import { getRecommendedProducts, recordCommerceEvent } from './commerce-recommendation-service.js';
import { listNotifications, markAllNotificationsRead, markNotificationRead, unreadNotificationCount, getNotificationPreferences, updateNotificationPreferences, getNotificationDigest, quietActive } from './notification-service.js';
import { searchDiscovery, type DiscoveryKind } from './discovery-service.js';
import { createConversation, listConversations, listMessages, markConversationRead, sendEncryptedMessage, upsertDeviceKeyBundle, listDeviceKeyBundles } from './messaging-service.js';
import { blockUser, getSafetyState, muteUser, reportContent, unblockUser, unmuteUser } from './safety-service.js';
import { completeUpload, createUploadIntent, getPlaybackUrl } from './media-service.js';
import { getPrivacySettings, updatePrivacySettings } from './privacy-service.js';
import { allowRequest, securityHeaders } from './security-middleware.js';
import { getBuyerOrder, listBuyerOrders, cancelPendingOrder } from './order-service.js';
import { recordUiMeasurements } from './measurement-service.js';
import { createRepost, getCommentReplies, getFeedPreferences, getPoll, getPostComments, listFeedTopics, listHiddenTopics, recordRecommendationFeedback, removeRecommendationFeedback, resetFeed, setFeedPreferences, setHiddenTopic, votePoll, type FeedbackSignal } from './social-surface-service.js';
import { getDiscoveryPreferences, listDiscoveryCategories, listRecentSearches, listSavedSearches, saveSearch, deleteSavedSearch, clearRecentSearches, recordSearch, updateDiscoveryPreferences, getDiscoveryResults, getDiscoveryFeed } from './discovery-surface-service.js';
import { getReelAudio, getReelPreferences, getRelatedReels, setReelCreatorFeedback, updateReelPreferences } from './reel-surface-service.js';
import { getProfileSurface, getMutualContext, listFollowers, listFollowing, listProfilePosts, listProfileVideos, listTaggedPosts, listSavedPosts, listCollections, getCollection, getShopSummary, getSellerSummary, updateProfileExtras } from './profile-surface-service.js';
import { listMarketCategories, listMarketProducts, getMarketProductDetail, setProductWishlist, getSavedProducts, relatedProducts, createProductReview, askProductQuestion, answerProductQuestion, listAddresses, saveAddress, deleteAddress, getDeliveryEstimate, requestReturn, listReturns, openOrderSupport, setShippingProfile, createVariant, updateVariant, deleteVariant, setStorefrontMetadata, getShopDiscovery, listShopCollections, addCollection } from './market-surface-service.js';
import { getCommerceProduct, setSavedForLater, listSavedForLater, listOrderDetail, reportOrderIssue, requestExchange } from './commerce-advanced-service.js';
import { getCheckoutState, prepareCheckout, setCheckoutAddress, setCheckoutDelivery, setCheckoutPaymentMethod } from './checkout-service.js';
import { listBlockedUsers, listMutedUsers, listHiddenTerms, setHiddenTerm, resetRecommendations, listPrivacyAudit, getDataInventory, createDataRequest, listDataRequests, listSecurityAlerts, acknowledgeSecurityAlert, listPermissions } from './settings-safety-service.js';
import { getAccountExperiencePreferences, updateAccountExperiencePreferences } from './account-experience-service.js';
const json=(res:ServerResponse,status:number,body:unknown)=>{securityHeaders(res);res.statusCode=status;res.setHeader('Content-Type','application/json; charset=utf-8');res.setHeader('Cache-Control','no-store');res.end(JSON.stringify(body));};
async function body(req:IncomingMessage):Promise<any>{let data='';for await(const chunk of req){data+=chunk;if(Buffer.byteLength(data)>256*1024)throw new Error('Request too large');}return data?JSON.parse(data):{};}
function bearer(req:IncomingMessage){const v=req.headers.authorization;return v?.startsWith('Bearer ')?v.slice(7):null;}function cookie(req:IncomingMessage,name:string){const x=(req.headers.cookie??'').split(';').map(v=>v.trim()).find(v=>v.startsWith(`${name}=`));return x?decodeURIComponent(x.slice(name.length+1)):null;}function sessionCookie(req:IncomingMessage){return cookie(req,config.secureCookies?'__Host-drustpoll_session':'drustpoll_session');}function setCookie(res:ServerResponse,token:string,maxAge=1800){const secure=config.secureCookies?'; Secure':'';const name=config.secureCookies?'__Host-drustpoll_session':'drustpoll_session';res.setHeader('Set-Cookie',`${name}=${encodeURIComponent(token)}; Path=/; HttpOnly; SameSite=Strict${secure}; Max-Age=${maxAge}`);}function clearCookie(res:ServerResponse){setCookie(res,'',0);}async function auth(req:IncomingMessage){return authenticate(bearer(req)??sessionCookie(req)??'');}
const server=createServer(async(req,res)=>{try{
if(!allowRequest(req))return json(res,429,{error:'Too many requests'});if(req.method==='OPTIONS'){securityHeaders(res);res.statusCode=204;res.end();return;}const url=new URL(req.url??'/',`http://${req.headers.host??'localhost'}`);const ip=req.headers['x-forwarded-for']?.toString().split(',')[0]?.trim()??req.socket.remoteAddress??'unknown';
if(req.method==='GET'&&url.pathname==='/health')return json(res,200,await health());
if(req.method==='POST'&&url.pathname==='/v1/auth/signup'){const r=await signup(await body(req),ip);setCookie(res,r.token);return json(res,201,r);}if(req.method==='POST'&&url.pathname==='/v1/auth/login'){const r=await login(await body(req),ip);setCookie(res,r.token);return json(res,200,r);}if(req.method==='POST'&&url.pathname==='/v1/auth/refresh'){const r=await refresh(String((await body(req)).refreshToken??''),ip);setCookie(res,r.token);return json(res,200,r);}if(req.method==='POST'&&url.pathname==='/v1/auth/password/forgot')return json(res,202,await requestPasswordReset(String((await body(req)).identifier??''),ip));if(req.method==='POST'&&url.pathname==='/v1/auth/password/reset'){const i=await body(req);return json(res,200,await resetPassword(String(i.token??''),String(i.newPassword??'')));}if(req.method==='POST'&&url.pathname==='/v1/auth/logout'){await revoke(bearer(req)??sessionCookie(req)??'');clearCookie(res);return json(res,200,{ok:true});}
const session=await auth(req);if(!session)return json(res,401,{error:'Unauthenticated'});if(req.method==='GET'&&url.pathname==='/v1/auth/me')return json(res,200,{session});if(req.method==='GET'&&url.pathname==='/v1/auth/sessions')return json(res,200,{sessions:await listSessions(session.userId,session.sessionId)});const sr=url.pathname.match(/^\/v1\/auth\/sessions\/([^/]+)\/revoke$/);if(req.method==='POST'&&sr){await revokeSession(session.userId,sr[1]);return json(res,200,{ok:true});}if(req.method==='POST'&&url.pathname==='/v1/auth/sessions/revoke-all'){await revokeAll(session.userId);return json(res,200,{ok:true});}
if(req.method==='GET'&&url.pathname==='/v1/privacy')return json(res,200,{privacy:await getPrivacySettings(session.userId)});if(req.method==='PUT'&&url.pathname==='/v1/privacy')return json(res,200,{privacy:await updatePrivacySettings(session.userId,await body(req))});if(req.method==='GET'&&url.pathname==='/v1/privacy/audit')return json(res,200,{events:await listPrivacyAudit(session.userId)});if(req.method==='GET'&&url.pathname==='/v1/privacy/inventory')return json(res,200,await getDataInventory(session.userId));if(req.method==='GET'&&url.pathname==='/v1/privacy/permissions')return json(res,200,{permissions:await listPermissions(session.userId)});if(req.method==='GET'&&url.pathname==='/v1/privacy/blocked')return json(res,200,{items:await listBlockedUsers(session.userId)});if(req.method==='GET'&&url.pathname==='/v1/privacy/muted')return json(res,200,{items:await listMutedUsers(session.userId)});if(req.method==='GET'&&url.pathname==='/v1/privacy/hidden-terms')return json(res,200,{items:await listHiddenTerms(session.userId)});if(req.method==='POST'&&url.pathname==='/v1/privacy/hidden-terms'){const i=await body(req);return json(res,200,await setHiddenTerm(session.userId,String(i.term??''),String(i.kind??'word'),true));}if(req.method==='DELETE'&&url.pathname==='/v1/privacy/hidden-terms'){const i=await body(req);return json(res,200,await setHiddenTerm(session.userId,String(i.term??''),String(i.kind??'word'),false));}if(req.method==='POST'&&url.pathname==='/v1/privacy/recommendations/reset')return json(res,200,await resetRecommendations(session.userId));if(req.method==='GET'&&url.pathname==='/v1/privacy/data-requests')return json(res,200,{requests:await listDataRequests(session.userId)});if(req.method==='POST'&&url.pathname==='/v1/privacy/data-requests'){const i=await body(req);const k=String(i.kind??'');if(k!=='export'&&k!=='delete')return json(res,400,{error:'Invalid data request'});return json(res,202,await createDataRequest(session.userId,k));}
if(req.method==='GET'&&url.pathname==='/v1/account/experience')return json(res,200,{preferences:await getAccountExperiencePreferences(session.userId)});if(req.method==='PUT'&&url.pathname==='/v1/account/experience')return json(res,200,{preferences:await updateAccountExperiencePreferences(session.userId,await body(req))});if(req.method==='GET'&&url.pathname==='/v1/privacy/audit')return json(res,200,{events:await listPrivacyAudit(session.userId)});
if(req.method==='GET'&&url.pathname==='/v1/security/alerts')return json(res,200,{alerts:await listSecurityAlerts(session.userId)});const sa=url.pathname.match(/^\/v1\/security\/alerts\/([^/]+)\/ack$/);if(req.method==='POST'&&sa)return json(res,200,await acknowledgeSecurityAlert(session.userId,sa[1]));
if(req.method==='GET'&&url.pathname==='/v1/notifications')return json(res,200,await listNotifications(session.userId,Number(url.searchParams.get('limit')??30),url.searchParams.get('before')??undefined,url.searchParams.get('category')??'all'));if(req.method==='GET'&&url.pathname==='/v1/notifications/unread-count')return json(res,200,{count:await unreadNotificationCount(session.userId)});if(req.method==='GET'&&url.pathname==='/v1/notifications/preferences')return json(res,200,{preferences:await getNotificationPreferences(session.userId)});if(req.method==='PUT'&&url.pathname==='/v1/notifications/preferences')return json(res,200,{preferences:await updateNotificationPreferences(session.userId,await body(req))});if(req.method==='GET'&&url.pathname==='/v1/notifications/digest')return json(res,200,await getNotificationDigest(session.userId));if(req.method==='GET'&&url.pathname==='/v1/notifications/quiet-state'){const p=await getNotificationPreferences(session.userId);return json(res,200,{active:quietActive(p),startMinute:p.quiet_start_minute,endMinute:p.quiet_end_minute,timezone:p.quiet_timezone});}const nr=url.pathname.match(/^\/v1\/notifications\/([^/]+)\/read$/);if(req.method==='POST'&&nr)return json(res,200,await markNotificationRead(session.userId,nr[1]));if(req.method==='POST'&&url.pathname==='/v1/notifications/read-all')return json(res,200,await markAllNotificationsRead(session.userId));
if(req.method==='GET'&&url.pathname==='/v1/discovery/search'){const k=(url.searchParams.get('kind')??'all') as DiscoveryKind;if(!['all','people','posts','products'].includes(k))return json(res,400,{error:'Invalid search kind'});const q=url.searchParams.get('q')??'';await recordSearch(session.userId,q,k);return json(res,200,await searchDiscovery(session.userId,q,k,Number(url.searchParams.get('limit')??20)));}if(req.method==='GET'&&url.pathname==='/v1/discovery/results')return json(res,200,await getDiscoveryResults(session.userId,url.searchParams));if(req.method==='GET'&&url.pathname==='/v1/discovery/feed')return json(res,200,await getDiscoveryFeed(session.userId,url.searchParams));
const sstate=url.pathname;
if(req.method==='GET'&&sstate==='/v1/feed'){const m=url.searchParams.get('mode')??'for_you';return json(res,200,await getFeed(session.userId,m==='following'?'following':'for_you',Number(url.searchParams.get('limit')??30),url.searchParams.get('before')??undefined));}if(req.method==='GET'&&sstate==='/v1/feed/topics')return json(res,200,{topics:await listFeedTopics(session.userId)});if(req.method==='GET'&&sstate==='/v1/feed/preferences')return json(res,200,await getFeedPreferences(session.userId));if(req.method==='PUT'&&sstate==='/v1/feed/preferences')return json(res,200,await setFeedPreferences(session.userId,await body(req)));if(req.method==='POST'&&sstate==='/v1/feed/reset')return json(res,200,{ok:true,...await resetFeed(session.userId)});if(req.method==='GET'&&sstate==='/v1/feed/hidden-topics')return json(res,200,{topics:await listHiddenTopics(session.userId)});if(req.method==='POST'&&sstate==='/v1/feed/hidden-topics'){const i=await body(req);return json(res,200,await setHiddenTopic(session.userId,String(i.topic??''),true));}if(req.method==='DELETE'&&sstate==='/v1/feed/hidden-topics'){const i=await body(req);return json(res,200,await setHiddenTopic(session.userId,String(i.topic??''),false));}
const sp=url.pathname.match(/^\/v1\/profiles\/([^/]+)$/);if(req.method==='GET'&&sp)return json(res,200,{profile:await getProfileSurface(session.userId,sp[1])});if(req.method==='GET'&&url.pathname==='/v1/profiles/me')return json(res,200,{profile:await getProfileSurface(session.userId,session.userId)});const mut=url.pathname.match(/^\/v1\/profiles\/([^/]+)\/mutuals$/);if(req.method==='GET'&&mut){const m=await getMutualContext(session.userId,mut[1]);return json(res,200,{count:m.count,people:m.people});}const followers=url.pathname.match(/^\/v1\/profiles\/([^/]+)\/followers$/);if(req.method==='GET'&&followers)return json(res,200,{people:await listFollowers(session.userId,followers[1],Number(url.searchParams.get('limit')??50),url.searchParams.get('before')??undefined)});const following=url.pathname.match(/^\/v1\/profiles\/([^/]+)\/following$/);if(req.method==='GET'&&following)return json(res,200,{people:await listFollowing(session.userId,following[1],Number(url.searchParams.get('limit')??50),url.searchParams.get('before')??undefined)});if(req.method==='GET'&&url.pathname==='/v1/profiles/me/saved')return json(res,200,{posts:await listSavedPosts(session.userId,Number(url.searchParams.get('limit')??30),url.searchParams.get('before')??undefined)});if(req.method==='GET'&&url.pathname==='/v1/shop/recommended')return json(res,200,{items:await getRecommendedProducts(session.userId,Number(url.searchParams.get('limit')??24))});
if(req.method==='GET'&&url.pathname==='/v1/market/categories')return json(res,200,{categories:await listMarketCategories(Number(url.searchParams.get('limit')??50))});if(req.method==='GET'&&url.pathname==='/v1/market/products')return json(res,200,{products:await listMarketProducts(session.userId,url.searchParams)});const md=url.pathname.match(/^\/v1\/market\/products\/([^/]+)$/);if(req.method==='GET'&&md)return json(res,200,await getMarketProductDetail(session.userId,md[1]));const mw=url.pathname.match(/^\/v1\/market\/products\/([^/]+)\/wishlist$/);if(mw&&(req.method==='POST'||req.method==='DELETE'))return json(res,200,await setProductWishlist(session.userId,mw[1],req.method==='POST'));if(req.method==='GET'&&url.pathname==='/v1/market/saved-products')return json(res,200,{items:await getSavedProducts(session.userId,Number(url.searchParams.get('limit')??50),url.searchParams.get('before')??undefined)});const related=url.pathname.match(/^\/v1\/market\/products\/([^/]+)\/related$/);if(req.method==='GET'&&related)return json(res,200,{items:await relatedProducts(session.userId,related[1],Number(url.searchParams.get('limit')??12))});const reviews=url.pathname.match(/^\/v1\/market\/products\/([^/]+)\/reviews$/);if(req.method==='POST'&&reviews)return json(res,201,await createProductReview(session.userId,reviews[1],await body(req)));const questions=url.pathname.match(/^\/v1\/market\/products\/([^/]+)\/questions$/);if(req.method==='POST'&&questions){const i=await body(req);return json(res,201,await askProductQuestion(session.userId,questions[1],String(i.question??'')));}const answers=url.pathname.match(/^\/v1\/market\/questions\/([^/]+)\/answers$/);if(req.method==='POST'&&answers){const i=await body(req);return json(res,201,await answerProductQuestion(session.userId,answers[1],String(i.answer??'')));}if(req.method==='GET'&&url.pathname==='/v1/market/addresses')return json(res,200,{addresses:await listAddresses(session.userId)});if(req.method==='POST'&&url.pathname==='/v1/market/addresses')return json(res,201,await saveAddress(session.userId,await body(req)));const addr=url.pathname.match(/^\/v1\/market\/addresses\/([^/]+)$/);if(req.method==='DELETE'&&addr)return json(res,200,await deleteAddress(session.userId,addr[1]));
if(req.method==='GET'&&url.pathname==='/v1/market/shops')return json(res,200,{shops:await getShopDiscovery(Number(url.searchParams.get('limit')??30))});const col=url.pathname.match(/^\/v1\/market\/shops\/([^/]+)\/collections$/);if(req.method==='GET'&&col)return json(res,200,{collections:await listShopCollections(col[1],Number(url.searchParams.get('limit')??30))});
if(req.method==='GET'&&url.pathname==='/v1/cart')return json(res,200,await getCart(session.userId));if(req.method==='POST'&&url.pathname==='/v1/cart/items'){const i=await body(req);return json(res,200,await addCartItem(session.userId,String(i.productId??''),Number(i.quantity??0)));}if(req.method==='PATCH'&&url.pathname==='/v1/cart/items'){const i=await body(req);return json(res,200,await updateCartItem(session.userId,String(i.productId??''),Number(i.quantity??0)));}if(req.method==='POST'&&url.pathname==='/v1/orders')return json(res,201,await placeOrder(session.userId,String((await body(req)).idempotencyKey??'')));if(req.method==='GET'&&url.pathname==='/v1/orders')return json(res,200,await listBuyerOrders(session.userId,Number(url.searchParams.get('limit')??30),url.searchParams.get('before')??undefined));const or=url.pathname.match(/^\/v1\/orders\/([^/]+)$/);if(req.method==='GET'&&or)return json(res,200,{order:await getBuyerOrder(session.userId,or[1])});const oc=url.pathname.match(/^\/v1\/orders\/([^/]+)\/cancel$/);if(req.method==='POST'&&oc)return json(res,200,await cancelPendingOrder(session.userId,oc[1]));
if(req.method==='GET'&&url.pathname==='/v1/security/alerts')return json(res,200,{alerts:await listSecurityAlerts(session.userId)});const sec=url.pathname.match(/^\/v1\/security\/alerts\/([^/]+)\/ack$/);if(req.method==='POST'&&sec)return json(res,200,await acknowledgeSecurityAlert(session.userId,sec[1]));
return json(res,404,{error:'Not found'});
}catch(error){return json(res,400,{error:error instanceof Error?error.message:'Request failed'});}});server.listen(config.port,config.host,()=>console.log(`Drustpoll API listening on ${config.host}:${config.port}`));
