import { query, withTransaction } from './db.js';

const clamp=(v:number,min:number,max:number)=>Math.min(Math.max(Math.trunc(v),min),max);
const clean=(v:unknown,max:number)=>String(v??'').trim().slice(0,max);

export async function listMarketCategories(limit=50){
 const r=await query(`SELECT COALESCE(category,'Uncategorized') category,COUNT(*)::int count FROM products WHERE status='active' GROUP BY 1 ORDER BY count DESC,category ASC LIMIT $1`,[clamp(limit,1,100)]);return r.rows;
}
export async function listMarketProducts(userId:string,params:URLSearchParams){
 const q=clean(params.get('q'),120),category=clean(params.get('category'),120),sort=['relevance','newest','price_asc','price_desc','rating'].includes(params.get('sort')??'')?String(params.get('sort')):'relevance',limit=clamp(Number(params.get('limit')??24),1,50),offset=Math.max(0,Math.trunc(Number(params.get('offset')??0)));
 const order=sort==='newest'?'p.created_at DESC':sort==='price_asc'?'p.price_minor ASC':sort==='price_desc'?'p.price_minor DESC':sort==='rating'?'rating DESC,p.created_at DESC':'score DESC,p.created_at DESC';
 const r=await query(`WITH stats AS(SELECT product_id,COUNT(*) FILTER(WHERE status='published')::int review_count,COALESCE(AVG(rating) FILTER(WHERE status='published'),0)::float rating FROM product_reviews GROUP BY product_id),wish AS(SELECT product_id FROM product_wishlists WHERE user_id=$1), scored AS(
 SELECT p.id,p.shop_id,s.owner_id seller_id,s.name shop_name,p.title,p.description,p.price_minor,p.currency,p.inventory,p.category,p.created_at,
 COALESCE(st.review_count,0) review_count,COALESCE(st.rating,0) rating,EXISTS(SELECT 1 FROM wish w WHERE w.product_id=p.id) saved,
 CASE WHEN lower(p.title) LIKE lower('%'||$2||'%') THEN 1 ELSE 0 END relevance,
 CASE WHEN lower(p.category)=lower($3) THEN 1 ELSE 0 END category_match
 FROM products p JOIN shops s ON s.id=p.shop_id LEFT JOIN stats st ON st.product_id=p.id
 WHERE p.status='active' AND ($2='' OR lower(p.title) LIKE lower('%'||$2||'%') OR lower(p.description) LIKE lower('%'||$2||'%') OR lower(COALESCE(p.category,'')) LIKE lower('%'||$2||'%')) AND ($3='' OR lower(COALESCE(p.category,''))=lower($3)) )
 SELECT *, (relevance*2.0+category_match+LEAST(1,rating/5.0)+CASE WHEN inventory>0 THEN .25 ELSE 0 END) score FROM scored ORDER BY ${order} LIMIT $4 OFFSET $5`,[userId,q,category,limit,offset]);
 return{items:r.rows,nextOffset:r.rows.length===limit?offset+limit:null};
}
export async function getMarketProductDetail(userId:string,productId:string){
 const [p,v,r,q,shipping]=await Promise.all([
  query(`SELECT p.*,s.name shop_name,s.description shop_description,s.owner_id seller_id FROM products p JOIN shops s ON s.id=p.shop_id WHERE p.id=$1 LIMIT 1`,[productId]),
  query(`SELECT id,name,sku,price_minor,inventory,attributes,active FROM product_variants WHERE product_id=$1 AND active=true ORDER BY created_at ASC`,[productId]),
  query(`SELECT r.id,r.rating,r.title,r.body,r.created_at,u.username FROM product_reviews r JOIN users u ON u.id=r.user_id WHERE r.product_id=$1 AND r.status='published' ORDER BY r.created_at DESC LIMIT 50`,[productId]),
  query(`SELECT q.id,q.question,q.created_at,u.username,(SELECT json_agg(json_build_object('id',a.id,'answer',a.answer,'createdAt',a.created_at,'username',ua.username) ORDER BY a.created_at ASC) FROM product_answers a JOIN users ua ON ua.id=a.user_id WHERE a.question_id=q.id) answers FROM product_questions q JOIN users u ON u.id=q.user_id WHERE q.product_id=$1 ORDER BY q.created_at DESC LIMIT 50`,[productId]),
  query(`SELECT origin_region,shipping_text,delivery_min_days,delivery_max_days,free_shipping_threshold_minor FROM product_shipping_profiles WHERE product_id=$1`,[productId])
 ]);
 if(!p.rows[0])return null;const wishlist=await query('SELECT 1 FROM product_wishlists WHERE user_id=$1 AND product_id=$2',[userId,productId]);return{product:p.rows[0],variants:v.rows,reviews:r.rows,questions:q.rows,shipping:shipping.rows[0]??null,saved:Boolean(wishlist.rowCount)};
}
export async function setProductWishlist(userId:string,productId:string,saved:boolean){if(saved)await query('INSERT INTO product_wishlists(user_id,product_id) VALUES($1,$2) ON CONFLICT DO NOTHING',[userId,productId]);else await query('DELETE FROM product_wishlists WHERE user_id=$1 AND product_id=$2',[userId,productId]);return{saved};}
export async function getSavedProducts(userId:string,limit=50,before?:string){const r=await query(`SELECT p.id,p.title,p.description,p.price_minor,p.currency,p.category,p.created_at,w.created_at saved_at FROM product_wishlists w JOIN products p ON p.id=w.product_id WHERE w.user_id=$1 AND ($2::timestamptz IS NULL OR w.created_at<$2::timestamptz) ORDER BY w.created_at DESC LIMIT $3`,[userId,before??null,clamp(limit,1,100)]);return{items:r.rows,nextBefore:r.rows.length===clamp(limit,1,100)?r.rows[r.rows.length-1].saved_at.toISOString():null};}
export async function relatedProducts(userId:string,productId:string,limit=12){const r=await query(`SELECT p.id,p.title,p.price_minor,p.currency,p.category,s.name shop_name FROM products p JOIN shops s ON s.id=p.shop_id WHERE p.status='active' AND p.id<>$2 AND (p.category=(SELECT category FROM products WHERE id=$2) OR s.id=(SELECT shop_id FROM products WHERE id=$2)) AND NOT EXISTS(SELECT 1 FROM user_blocks b WHERE (b.blocker_id=$1 AND b.blocked_id=s.owner_id) OR (b.blocker_id=s.owner_id AND b.blocked_id=$1)) ORDER BY p.created_at DESC LIMIT $3`,[userId,productId,clamp(limit,1,24)]);return r.rows;}
export async function createProductReview(userId:string,productId:string,input:any){const orderId=input.orderId?String(input.orderId):null;const rating=Math.trunc(Number(input.rating));if(rating<1||rating>5)throw new Error('Rating must be 1-5');if(orderId){const owned=await query('SELECT 1 FROM orders o JOIN order_lines l ON l.order_id=o.id WHERE o.id=$1 AND o.buyer_id=$2 AND l.product_id=$3 AND o.status IN(\'paid\',\'processing\',\'shipped\',\'delivered\')',[orderId,userId,productId]);if(!owned.rowCount)throw new Error('Verified purchase required');}const r=await query(`INSERT INTO product_reviews(product_id,user_id,order_id,rating,title,body) VALUES($1,$2,$3,$4,$5,$6) RETURNING id,created_at`,[productId,userId,orderId,rating,clean(input.title,160),clean(input.body,5000)]);return{id:r.rows[0].id,createdAt:r.rows[0].created_at.toISOString()};}
export async function askProductQuestion(userId:string,productId:string,question:string){const cleanQ=clean(question,1200);if(!cleanQ)throw new Error('Question required');const r=await query(`INSERT INTO product_questions(product_id,user_id,question) VALUES($1,$2,$3) RETURNING id,created_at`,[productId,userId,cleanQ]);return{id:r.rows[0].id,createdAt:r.rows[0].created_at.toISOString()};}
export async function answerProductQuestion(userId:string,questionId:string,answer:string){const a=clean(answer,3000);if(!a)throw new Error('Answer required');const owned=await query(`SELECT 1 FROM product_questions q JOIN products p ON p.id=q.product_id JOIN shops s ON s.id=p.shop_id WHERE q.id=$1 AND s.owner_id=$2`,[questionId,userId]);if(!owned.rowCount)throw new Error('Only the seller can answer this question');const r=await query(`INSERT INTO product_answers(question_id,user_id,answer) VALUES($1,$2,$3) RETURNING id,created_at`,[questionId,userId,a]);return{id:r.rows[0].id,createdAt:r.rows[0].created_at.toISOString()};}
export async function listAddresses(userId:string){const r=await query('SELECT * FROM buyer_addresses WHERE user_id=$1 ORDER BY is_default DESC,updated_at DESC',[userId]);return r.rows;}
export async function saveAddress(userId:string,input:any){const required=['label','recipientName','phone','line1','city','region','postalCode','countryCode'];for(const key of required)if(!clean(input[key],200))throw new Error('Address fields are required');const isDefault=Boolean(input.isDefault);return withTransaction(async client=>{if(isDefault)await client.query('UPDATE buyer_addresses SET is_default=false,updated_at=now() WHERE user_id=$1',[userId]);const r=await client.query(`INSERT INTO buyer_addresses(user_id,label,recipient_name,phone,line1,line2,city,region,postal_code,country_code,is_default) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11) RETURNING *`,[userId,clean(input.label,80),clean(input.recipientName,160),clean(input.phone,40),clean(input.line1,240),clean(input.line2,240),clean(input.city,120),clean(input.region,120),clean(input.postalCode,32),clean(input.countryCode,2).toUpperCase(),isDefault]);return r.rows[0];});}
export async function deleteAddress(userId:string,id:string){await query('DELETE FROM buyer_addresses WHERE id=$1 AND user_id=$2',[id,userId]);return{ok:true};}
export async function getDeliveryEstimate(productId:string,userId:string,addressId?:string){const shipping=await query(`SELECT s.origin_region,sp.shipping_text,sp.delivery_min_days,sp.delivery_max_days FROM products p JOIN shops s ON s.id=p.shop_id LEFT JOIN product_shipping_profiles sp ON sp.product_id=p.id WHERE p.id=$1`,[productId]);if(!shipping.rows[0])return null;let address=null;if(addressId){const a=await query('SELECT city,region,postal_code,country_code FROM buyer_addresses WHERE id=$1 AND user_id=$2',[addressId,userId]);address=a.rows[0]??null;}return{...shipping.rows[0],address};}
export async function requestReturn(userId:string,orderId:string,reason:string,notes=''){const own=await query('SELECT 1 FROM orders WHERE id=$1 AND buyer_id=$2 AND status IN(\'paid\',\'processing\',\'shipped\',\'delivered\')',[orderId,userId]);if(!own.rowCount)throw new Error('Order is not eligible for return');const r=await query(`INSERT INTO order_returns(order_id,buyer_id,reason,notes) VALUES($1,$2,$3,$4) RETURNING id,status,created_at`,[orderId,userId,clean(reason,200),clean(notes,2000)]);return r.rows[0];}
export async function listReturns(userId:string,orderId?:string){const r=await query('SELECT * FROM order_returns WHERE buyer_id=$1 AND ($2::uuid IS NULL OR order_id=$2) ORDER BY created_at DESC',[userId,orderId??null]);return r.rows;}
export async function openOrderSupport(userId:string,orderId:string,subject:string){const own=await query('SELECT 1 FROM orders WHERE id=$1 AND buyer_id=$2',[orderId,userId]);if(!own.rowCount)throw new Error('Order not found');const r=await query(`INSERT INTO order_support_threads(order_id,user_id,subject) VALUES($1,$2,$3) RETURNING *`,[orderId,userId,clean(subject,200)]);return r.rows[0];}
export async function setShippingProfile(userId:string,productId:string,input:any){const own=await query(`SELECT 1 FROM products p JOIN shops s ON s.id=p.shop_id WHERE p.id=$1 AND s.owner_id=$2`,[productId,userId]);if(!own.rowCount)throw new Error('Product not found');await query(`INSERT INTO product_shipping_profiles(product_id,origin_region,shipping_text,delivery_min_days,delivery_max_days,free_shipping_threshold_minor,updated_at) VALUES($1,$2,$3,$4,$5,$6,now()) ON CONFLICT(product_id) DO UPDATE SET origin_region=$2,shipping_text=$3,delivery_min_days=$4,delivery_max_days=$5,free_shipping_threshold_minor=$6,updated_at=now()`,[productId,clean(input.originRegion,120),clean(input.shippingText,1000),input.deliveryMinDays==null?null:clamp(Number(input.deliveryMinDays),0,365),input.deliveryMaxDays==null?null:clamp(Number(input.deliveryMaxDays),0,365),input.freeShippingThresholdMinor==null?null:Number(input.freeShippingThresholdMinor)]);return getMarketProductDetail(userId,productId);}
