import { query, withTransaction } from './db.js';
import { createPlaybackUrl, headObject } from './storage-service.js';
import { config } from './config.js';

type Job={id:string;asset_id:string;job_type:'probe'|'scan'|'thumbnail'|'moderation'|'transcode';attempt_count:number};
const MAX_ATTEMPTS=5,LEASE_MS=10*60*1000;
async function processRemote(input:unknown){if(!config.mediaProcessing.endpoint)throw new Error('MEDIA_PROCESSOR_NOT_CONFIGURED');const controller=new AbortController();const timer=setTimeout(()=>controller.abort(),config.mediaProcessing.timeoutMs);try{const r=await fetch(config.mediaProcessing.endpoint,{method:'POST',headers:{'Content-Type':'application/json',...(config.mediaProcessing.apiKey?{Authorization:`Bearer ${config.mediaProcessing.apiKey}`}:{})},body:JSON.stringify(input),signal:controller.signal});if(!r.ok)throw new Error(`MEDIA_PROCESSOR_HTTP_${r.status}`);const data=await r.json() as Record<string,unknown>;return data;}finally{clearTimeout(timer);}}
export async function leaseMediaJob(workerId:string):Promise<Job|null>{return withTransaction(async client=>{const r=await client.query<Job>(`SELECT id,asset_id,job_type,attempt_count FROM media_jobs WHERE (status='queued' AND created_at<=now()) OR (status='running' AND started_at<now()-interval '10 minutes') ORDER BY created_at,id FOR UPDATE SKIP LOCKED LIMIT 1`);if(!r.rowCount)return null;const job=r.rows[0];await client.query(`UPDATE media_jobs SET status='running',attempt_count=attempt_count+1,started_at=now(),error_code=NULL WHERE id=$1`,[job.id]);return job;});}
export async function runMediaJob(job:Job){try{const asset=await query<{storage_key:string;media_type:string;declared_mime:string;byte_size:number}>(`SELECT storage_key,media_type,declared_mime,byte_size FROM media_assets WHERE id=$1`,[job.asset_id]);if(!asset.rowCount)throw new Error('MEDIA_ASSET_NOT_FOUND');const sourceUrl=await createPlaybackUrl(asset.rows[0].storage_key);const result=await processRemote({jobType:job.job_type,assetId:job.asset_id,sourceUrl,mediaType:asset.rows[0].media_type,mime:asset.rows[0].declared_mime,byteSize:Number(asset.rows[0].byte_size)});await withTransaction(async client=>{if(job.job_type==='moderation'){const status=String(result.status??'');if(!['approved','rejected','review'].includes(status))throw new Error('INVALID_MODERATION_RESULT');await client.query(`UPDATE media_assets SET moderation_status=$2,updated_at=now() WHERE id=$1`,[job.asset_id,status]);}
 if(job.job_type==='probe'){const detectedMime=String(result.detectedMime??'');const byteSize=Number(result.byteSize??0);if(!detectedMime||!Number.isSafeInteger(byteSize)||byteSize<=0)throw new Error('INVALID_PROBE_RESULT');await client.query(`UPDATE media_assets SET detected_mime=$2,byte_size=$3,width=$4,height=$5,duration_ms=$6,updated_at=now() WHERE id=$1`,[job.asset_id,detectedMime,byteSize,result.width==null?null:Number(result.width),result.height==null?null:Number(result.height),result.durationMs==null?null:Number(result.durationMs)]);}
 if(job.job_type==='thumbnail'||job.job_type==='transcode'){const renditions=Array.isArray(result.renditions)?result.renditions:[];for(const rendition of renditions as Array<Record<string,unknown>>){const key=String(rendition.storageKey??'');const type=String(rendition.renditionType??'');if(!key||!['thumbnail','preview','hls','dash','image','original'].includes(type))throw new Error('INVALID_RENDITION');const object=await headObject(key);if(object.contentLength<=0)throw new Error('RENDITION_MISSING');await client.query(`INSERT INTO media_renditions(asset_id,rendition_type,storage_key,mime_type,width,height,bitrate,duration_ms,byte_size) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9) ON CONFLICT(asset_id,rendition_type,width,height,bitrate) DO NOTHING`,[job.asset_id,type,key,rendition.mimeType?String(rendition.mimeType):null,rendition.width==null?null:Number(rendition.width),rendition.height==null?null:Number(rendition.height),rendition.bitrate==null?null:Number(rendition.bitrate),rendition.durationMs==null?null:Number(rendition.durationMs),object.contentLength]);}}
 await client.query(`UPDATE media_jobs SET status='succeeded',finished_at=now(),error_code=NULL WHERE id=$1`,[job.id]);
 });}catch(error){const code=error instanceof Error?error.message:'MEDIA_JOB_FAILED';await query(`UPDATE media_jobs SET status=CASE WHEN attempt_count >= $2 THEN 'failed' ELSE 'queued' END,error_code=$3,finished_at=CASE WHEN attempt_count >= $2 THEN now() ELSE NULL END,started_at=NULL WHERE id=$1`,[job.id,MAX_ATTEMPTS,code.slice(0,120)]);throw error;}}
