import { query, withTransaction } from './db.js';
async function member(userId:string,conversationId:string){const r=await query('SELECT 1 FROM conversation_members WHERE conversation_id=$1 AND user_id=$2 AND left_at IS NULL',[conversationId,userId]);if(!r.rowCount)throw new Error('Conversation not found');}
export async function getMessagePreferences(userId:string){const r=await query('SELECT typing_indicators,read_receipts,disappearing_default_seconds,updated_at FROM message_preferences WHERE user_id=$1',[userId]);return r.rows[0]??{typing_indicators:true,read_receipts:true,disappearing_default_seconds:null,updated_at:null};}
export async function updateMessagePreferences(userId:string,input:any){const typing=input.typingIndicators!==false,read=input.readReceipts!==false;const d=input.disappearingDefaultSeconds==null?null:Number(input.disappearingDefaultSeconds);if(d!==null&&(!Number.isInteger(d)||d<5||d>2592000))throw new Error('Invalid disappearing duration');const r=await query('INSERT INTO message_preferences(user_id,typing_indicators,read_receipts,disappearing_default_seconds) VALUES($1,$2,$3,$4) ON CONFLICT(user_id) DO UPDATE SET typing_indicators=EXCLUDED.typing_indicators,read_receipts=EXCLUDED.read_receipts,disappearing_default_seconds=EXCLUDED.disappearing_default_seconds,updated_at=now() RETURNING *',[userId,typing,read,d]);return r.rows[0];}
export async function setTyping(userId:string,conversationId:string,active:boolean){await member(userId,conversationId);if(active)await query('INSERT INTO message_typing(conversation_id,user_id,expires_at) VALUES($1,$2,now()+interval \'6 seconds\') ON CONFLICT(conversation_id,user_id) DO UPDATE SET expires_at=now()+interval \'6 seconds\',updated_at=now()',[conversationId,userId]);else await query('DELETE FROM message_typing WHERE conversation_id=$1 AND user_id=$2',[conversationId,userId]);return{ok:true};}
export async function listTyping(userId:string,conversationId:string){await member(userId,conversationId);await query('DELETE FROM message_typing WHERE expires_at<now()');const r=await query('SELECT user_id,expires_at FROM message_typing WHERE conversation_id=$1 AND user_id<>$2 AND expires_at>now()',[conversationId,userId]);return{users:r.rows};}
export async function reactToMessage(userId:string,messageId:string,reaction:string){const r=await query<{conversation_id:string}>('SELECT conversation_id FROM messages WHERE id=$1 AND deleted_at IS NULL',[messageId]);if(!r.rowCount)throw new Error('Message not found');await member(userId,r.rows[0].conversation_id);const value=reaction.trim().slice(0,32);if(!value)throw new Error('Reaction required');await query('INSERT INTO message_reactions(message_id,user_id,reaction) VALUES($1,$2,$3) ON CONFLICT(message_id,user_id) DO UPDATE SET reaction=EXCLUDED.reaction',[messageId,userId,value]);return{ok:true};}
export async function removeMessageReaction(userId:string,messageId:string){const r=await query<{conversation_id:string}>('SELECT conversation_id FROM messages WHERE id=$1 AND deleted_at IS NULL',[messageId]);if(!r.rowCount)throw new Error('Message not found');await member(userId,r.rows[0].conversation_id);await query('DELETE FROM message_reactions WHERE message_id=$1 AND user_id=$2',[messageId,userId]);return{ok:true};}
export async function pinMessage(userId:string,messageId:string,pinned:boolean){const r=await query<{conversation_id:string}>('SELECT conversation_id FROM messages WHERE id=$1 AND deleted_at IS NULL',[messageId]);if(!r.rowCount)throw new Error('Message not found');const cid=r.rows[0].conversation_id;await member(userId,cid);if(pinned)await query('INSERT INTO message_pins(conversation_id,message_id,pinned_by) VALUES($1,$2,$3) ON CONFLICT DO NOTHING',[cid,messageId,userId]);else await query('DELETE FROM message_pins WHERE conversation_id=$1 AND message_id=$2',[cid,messageId]);return{ok:true,pinned};}
export async function listPinned(userId:string,conversationId:string){await member(userId,conversationId);const r=await query('SELECT p.message_id,p.pinned_by,p.created_at FROM message_pins p WHERE p.conversation_id=$1 ORDER BY p.created_at DESC LIMIT 100',[conversationId]);return{pins:r.rows};}
export async function replyToMessage(userId:string,parentMessageId:string,ciphertext:string,keyVersion:number,deviceId?:string){const parent=await query<{conversation_id:string}>('SELECT conversation_id FROM messages WHERE id=$1 AND deleted_at IS NULL',[parentMessageId]);if(!parent.rowCount)throw new Error('Parent message not found');await member(userId,parent.rows[0].conversation_id);return withTransaction(async client=>{const m=await client.query<{id:string;created_at:Date}>(`INSERT INTO messages(conversation_id,sender_id,ciphertext,key_version) VALUES($1,$2,$3,$4) RETURNING id,created_at`,[parent.rows[0].conversation_id,userId,ciphertext,keyVersion]);await client.query('INSERT INTO message_replies(message_id,parent_message_id) VALUES($1,$2)',[m.rows[0].id,parentMessageId]);return{id:m.rows[0].id,createdAt:m.rows[0].created_at.toISOString(),parentMessageId};});}
export async function searchEncryptedMessages(userId:string,conversationId:string,q:string){await member(userId,conversationId);const term=q.trim();if(!term||term.length>200)throw new Error('Search query required');const r=await query('SELECT id,sender_id,created_at FROM messages WHERE conversation_id=$1 AND deleted_at IS NULL AND ciphertext=$2 ORDER BY created_at DESC LIMIT 50',[conversationId,term]);return{messages:r.rows,mode:'encrypted-exact-envelope'};}
