import { query } from './db.js';

export type NotificationType='follow'|'follow_request'|'reaction'|'comment'|'mention'|'message'|'order_update'|'security'|'system';
export type NotificationCategory='social'|'mentions_replies'|'follows'|'commerce_orders'|'security'|'system';
export type DigestFrequency='daily'|'weekly';
type NotificationInput={recipientId:string;actorId?:string;type:NotificationType;objectId?:string;groupedKey?:string;metadata?:Record<string,unknown>};
const categoryFor=(type:NotificationType):NotificationCategory=>type==='mention'||type==='comment'?'mentions_replies':type==='follow'||type==='follow_request'?'follows':type==='order_update'?'commerce_orders':type==='security'?'security':type==='system'?'system':'social';
export async function getNotificationPreferences(userId:string){const r=await query(`SELECT social,mentions_replies,follows,commerce_orders,security,system,digest_enabled,digest_frequency,quiet_enabled,quiet_start_minute,quiet_end_minute,quiet_timezone,updated_at FROM notification_preferences WHERE user_id=$1`,[userId]);return r.rows[0]??{social:true,mentions_replies:true,follows:true,commerce_orders:true,security:true,system:true,digest_enabled:false,digest_frequency:'daily',quiet_enabled:false,quiet_start_minute:1320,quiet_end_minute:420,quiet_timezone:'UTC',updated_at:null};}
export async function updateNotificationPreferences(userId:string,input:Record<string,unknown>){const c=await getNotificationPreferences(userId);const bool=(key:string,fallback:boolean)=>typeof input[key]==='boolean'?Boolean(input[key]):fallback;const minute=(key:string,fallback:number)=>{const raw=input[key];if(raw==null)return fallback;const n=Math.trunc(Number(raw));return Number.isFinite(n)?Math.min(1439,Math.max(0,n)):fallback;};const frequency:DigestFrequency=input.digestFrequency==='weekly'?'weekly':input.digestFrequency==='daily'?'daily':(c.digest_frequency==='weekly'?'weekly':'daily');const timezone=String(input.quietTimezone??c.quiet_timezone??'UTC').trim().slice(0,80)||'UTC';await query(`INSERT INTO notification_preferences(user_id,social,mentions_replies,follows,commerce_orders,security,system,digest_enabled,digest_frequency,quiet_enabled,quiet_start_minute,quiet_end_minute,quiet_timezone,updated_at) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,now()) ON CONFLICT(user_id) DO UPDATE SET social=$2,mentions_replies=$3,follows=$4,commerce_orders=$5,security=$6,system=$7,digest_enabled=$8,digest_frequency=$9,quiet_enabled=$10,quiet_start_minute=$11,quiet_end_minute=$12,quiet_timezone=$13,updated_at=now()`,[userId,bool('social',c.social!==false),bool('mentionsReplies',c.mentions_replies!==false),bool('follows',c.follows!==false),bool('commerceOrders',c.commerce_orders!==false),bool('security',c.security!==false),bool('system',c.system!==false),bool('digestEnabled',c.digest_enabled===true),frequency,bool('quietEnabled',c.quiet_enabled===true),minute('quietStartMinute',Number(c.quiet_start_minute??1320)),minute('quietEndMinute',Number(c.quiet_end_minute??420)),timezone]);return getNotificationPreferences(userId);}
export async function createNotification(input:NotificationInput){if(input.actorId&&input.actorId===input.recipientId)return null;const category=categoryFor(input.type);const prefs=await getNotificationPreferences(input.recipientId) as any;if(prefs[category]===false)return null;const r=await query<{id:string;created_at:Date}>(`INSERT INTO notifications(recipient_id,actor_id,type,object_id,grouped_key,metadata,category) VALUES($1,$2,$3,$4,$5,$6,$7) RETURNING id,created_at`,[input.recipientId,input.actorId??null,input.type,input.objectId??null,input.groupedKey??null,JSON.stringify(input.metadata??{}),category]);return r.rows[0]?{id:r.rows[0].id,createdAt:r.rows[0].created_at.toISOString()}:null;}
export async function listNotifications(userId:string,limit=30,before?:string,category='all'){const safe=Math.min(Math.max(Math.trunc(limit),1),100);const wanted=['all','social','mentions_replies','follows','commerce_orders','security','system'].includes(category)?category:'all';const r=await query(`SELECT n.id,n.actor_id,n.type,n.object_id,n.grouped_key,n.metadata,n.category,n.read_at,n.created_at,p.username actor_username,pr.display_name actor_display_name,pr.avatar_url actor_avatar_url FROM notifications n LEFT JOIN users p ON p.id=n.actor_id LEFT JOIN profiles pr ON pr.user_id=n.actor_id WHERE n.recipient_id=$1 AND ($2::timestamptz IS NULL OR n.created_at<$2::timestamptz) AND ($3='all' OR n.category=$3) ORDER BY n.created_at DESC LIMIT $4`,[userId,before??null,wanted,safe]);return{notifications:r.rows,nextBefore:r.rows.length===safe?r.rows[r.rows.length-1].created_at.toISOString():null};}
export async function unreadNotificationCount(userId:string){const r=await query<{count:string}>('SELECT count(*)::text count FROM notifications WHERE recipient_id=$1 AND read_at IS NULL',[userId]);return Number(r.rows[0]?.count??0);}
export async function markNotificationRead(userId:string,id:string){const r=await query('UPDATE notifications SET read_at=COALESCE(read_at,now()) WHERE id=$1 AND recipient_id=$2 RETURNING id',[id,userId]);return{ok:r.rowCount===1};}
export async function markAllNotificationsRead(userId:string){const r=await query('UPDATE notifications SET read_at=now() WHERE recipient_id=$1 AND read_at IS NULL',[userId]);return{updated:r.rowCount??0};}
export async function getNotificationDigest(userId:string){const p=await getNotificationPreferences(userId);if(!p.digest_enabled)return{enabled:false,items:[]};const interval=p.digest_frequency==='weekly'?'7 days':'1 day';const r=await query(`SELECT category,type,COUNT(*)::int count,MAX(created_at) latest FROM notifications WHERE recipient_id=$1 AND digest_eligible=true AND created_at>now()-($2::interval) GROUP BY category,type ORDER BY latest DESC`,[userId,interval]);return{enabled:true,frequency:p.digest_frequency,items:r.rows};}
export function quietActive(preferences:any,at=new Date()){if(!preferences?.quiet_enabled)return false;const minute=at.getHours()*60+at.getMinutes();const start=Number(preferences.quiet_start_minute??1320),end=Number(preferences.quiet_end_minute??420);return start<=end?minute>=start&&minute<end:minute>=start||minute<end;}
