import type { IncomingMessage } from 'node:http';
import { listConversations, listMessageRequests, resolveMessageRequest, createConversation, listMessages, sendEncryptedMessage, markConversationRead, listDeviceKeyBundles, upsertDeviceKeyBundle } from './messaging-service.js';
import { getFeed, createPost, toggleReaction, toggleSave, addComment, type FeedMode } from './social-service.js';
import { recordRecommendationFeedback, removeRecommendationFeedback, createRepost, getPostComments, getCommentReplies, votePoll, getPoll, listFeedTopics, getFeedPreferences, setFeedPreferences, resetFeed, setHiddenTopic, listHiddenTopics } from './social-surface-service.js';
import { searchDiscovery } from './discovery-service.js';
import { getReelCandidates, startReelWatchSession, endReelWatchSession, recordReelWatchEvents } from './reels-service.js';
import { blockUser, unblockUser, muteUser, unmuteUser, restrictUser, reportContent, getSafetyState, addReportEvidence, addCaseEvidence, listSafetyCases, submitAppeal, listModerationNotices } from './safety-service.js';
import { requestOtp, verifyOtp } from './auth-service.js';
import { hydrateAvatarRows, mediaUri } from './storage-service.js';
const json=(res:any,status:number,body:any)=>{res.statusCode=status;res.setHeader('Content-Type','application/json; charset=utf-8');res.setHeader('Cache-Control','no-store');res.end(JSON.stringify(body));};
const body=async(req:IncomingMessage)=>{let raw='';for await(const c of req){raw+=c;if(Buffer.byteLength(raw)>300000)throw new Error('Request too large');}return raw?JSON.parse(raw):{};};
export async function handlePlatformRoute(req:IncomingMessage,res:any,userId:string,path:string,url:URL){
 if(req.method==='POST'&&path==='/v1/auth/otp/request'){const i=await body(req);const purpose=String(i.purpose??'verify_email') as any;const destination=String(i.destination??'');if(!['verify_email','verify_phone','password_reset','login_step_up'].includes(purpose))return json(res,400,{error:'Invalid OTP purpose'});return json(res,202,await requestOtp(userId,destination,purpose,'authenticated'));}
 if(req.method==='POST'&&path==='/v1/auth/otp/verify'){const i=await body(req);const purpose=String(i.purpose??'verify_email') as any;const destination=String(i.destination??'');const code=String(i.code??'');if(!['verify_email','verify_phone','password_reset','login_step_up'].includes(purpose))return json(res,400,{error:'Invalid OTP purpose'});await verifyOtp(userId,destination,purpose,code);return json(res,200,{verified:true,purpose});}
 if(req.method==='GET'&&path==='/v1/feed'){
  const mode=url.searchParams.get('mode')??'for_you';
  if(!['for_you','following','latest'].includes(mode))return json(res,400,{error:'Invalid feed mode'});
  const feed=await getFeed(userId,mode as FeedMode,Number(url.searchParams.get('limit')??30),url.searchParams.get('before')??undefined);
  const origin=`${url.protocol==='https:'?'https':'http'}://${url.host??req.headers.host??'localhost'}`;
  await hydrateAvatarRows(feed.items as any,origin);
  for(const item of feed.items as any[]){if(Array.isArray(item.media))for(const media of item.media){if(media.storageKey&&!media.uri){const uri=await mediaUri(media.storageKey,origin);if(uri)media.uri=uri;}}}
  return json(res,200,feed);
 }
 if(req.method==='POST'&&path==='/v1/posts')return json(res,201,await createPost(userId,await body(req)));
 let m=path.match(/^\/v1\/posts\/([^/]+)\/reaction$/);if(m&&req.method==='POST')return json(res,200,await toggleReaction(userId,m[1]));m=path.match(/^\/v1\/posts\/([^/]+)\/save$/);if(m&&req.method==='POST')return json(res,200,await toggleSave(userId,m[1]));m=path.match(/^\/v1\/posts\/([^/]+)\/comments$/);if(m&&req.method==='GET'){const page:any=await getPostComments(userId,m[1],Number(url.searchParams.get('limit')??50),url.searchParams.get('before')??undefined);const origin=`${url.protocol==='https:'?'https':'http'}://${url.host??req.headers.host??'localhost'}`;await hydrateAvatarRows(page.comments??[],origin);return json(res,200,{...page,items:page.comments??[]});}if(m&&req.method==='POST'){const i=await body(req);return json(res,201,await addComment(userId,m[1],String(i.body??''),i.parentId?String(i.parentId):undefined));}m=path.match(/^\/v1\/comments\/([^/]+)\/replies$/);if(m&&req.method==='GET'){const page:any=await getCommentReplies(userId,m[1],Number(url.searchParams.get('limit')??50),url.searchParams.get('before')??undefined);const origin=`${url.protocol==='https:'?'https':'http'}://${url.host??req.headers.host??'localhost'}`;const rows=page.replies??page.comments??page.items??[];await hydrateAvatarRows(rows,origin);return json(res,200,{...page,items:rows});}m=path.match(/^\/v1\/posts\/([^/]+)\/poll$/);if(m&&req.method==='GET')return json(res,200,await getPoll(userId,m[1]));if(m&&req.method==='POST'){const i=await body(req);return json(res,200,await votePoll(userId,m[1],String(i.optionId??'')));}m=path.match(/^\/v1\/posts\/([^/]+)\/repost$/);if(m&&req.method==='POST'){const i=await body(req);return json(res,200,await createRepost(userId,m[1],String(i.quote??'')));}
 if(path==='/v1/recommendation/feedback'){const i=await body(req);return json(res,200,req.method==='DELETE'?await removeRecommendationFeedback(userId,i.objectType,i.objectId,i.signal,i.context):await recordRecommendationFeedback(userId,i.objectType,i.objectId,i.signal,i.context));}
 if(req.method==='GET'&&path==='/v1/feed/topics')return json(res,200,{topics:await listFeedTopics(userId)});if(req.method==='GET'&&path==='/v1/feed/preferences')return json(res,200,await getFeedPreferences(userId));if(req.method==='PUT'&&path==='/v1/feed/preferences')return json(res,200,await setFeedPreferences(userId,await body(req)));if(req.method==='POST'&&path==='/v1/feed/reset')return json(res,200,await resetFeed(userId));if(req.method==='GET'&&path==='/v1/feed/hidden-topics'){const hidden=await listHiddenTopics(userId);return json(res,200,{...hidden,items:hidden.topics});}if(path==='/v1/feed/hidden-topics'&&(req.method==='POST'||req.method==='DELETE')){const i=await body(req);return json(res,200,await setHiddenTopic(userId,String(i.topic??''),req.method==='POST'));}
 if(path==='/v1/reels/recommended'&&req.method==='GET'){const items=await getReelCandidates(userId,Number(url.searchParams.get('limit')??30));const origin=`${url.protocol==='https:'?'https':'http'}://${url.host??req.headers.host??'localhost'}`;for(const item of items as Array<Record<string,unknown>>){const v=typeof item.videoUrl==='string'?item.videoUrl:null;if(v&&v.startsWith('/'))item.videoUrl=origin+v;}return json(res,200,{items});}if(path==='/v1/reels/watch-sessions'&&req.method==='POST'){const i=await body(req);return json(res,201,await startReelWatchSession(userId,String(i.clientSessionId??'')));}m=path.match(/^\/v1\/reels\/watch-sessions\/([^/]+)$/);if(m&&req.method==='DELETE')return json(res,200,await endReelWatchSession(userId,m[1]));if(path==='/v1/reels/watch-events'&&req.method==='POST'){const i=await body(req);return json(res,200,await recordReelWatchEvents(userId,String(i.sessionId??''),i.events??[]));}
 if(path==='/v1/discovery/search'&&req.method==='GET'){const r:any=await searchDiscovery(userId,url.searchParams.get('q')??'',(url.searchParams.get('kind')??'all') as any,Number(url.searchParams.get('limit')??20));const origin=`${url.protocol==='https:'?'https':'http'}://${url.host??req.headers.host??'localhost'}`;for(const key of ['people','posts','videos','products','shops'])if(Array.isArray(r[key]))await hydrateAvatarRows(r[key],origin,['avatar_url','logo_url']);return json(res,200,{...r,videos:r.videos??[],shops:r.shops??[],topics:r.topics??[],suggestions:r.suggestions??[]});}
 if(path==='/v1/messages/requests'&&req.method==='GET'){
  const page=await listMessageRequests(userId,Number(url.searchParams.get('limit')??50));
  const origin=`${url.protocol==='https:'?'https':'http'}://${url.host??req.headers.host??'localhost'}`;
  await hydrateAvatarRows(page.requests as any,origin);
  return json(res,200,page);
 }
 m=path.match(/^\/v1\/messages\/requests\/([^/]+)$/);if(m&&req.method==='POST'){
  const i=await body(req);const decision=String(i.decision??'');
  if(decision!=='accept'&&decision!=='decline')return json(res,400,{error:'Invalid message request decision'});
  return json(res,200,await resolveMessageRequest(userId,m[1],decision));
 }
 if(path==='/v1/messages/conversations'&&req.method==='GET'){
  const folder=url.searchParams.get('folder')==='unread'?'unread':'all';
  return json(res,200,await listConversations(userId,Number(url.searchParams.get('limit')??30),folder));
 }
 if(path==='/v1/messages/conversations'&&req.method==='POST'){
  const i=await body(req);return json(res,201,await createConversation(userId,(i.participantIds??[]).map(String)));
 }
 m=path.match(/^\/v1\/messages\/conversations\/([^/]+)\/messages$/);if(m&&req.method==='GET')return json(res,200,await listMessages(userId,m[1],Number(url.searchParams.get('limit')??50),url.searchParams.get('before')??undefined));if(m&&req.method==='POST'){const i=await body(req);return json(res,201,await sendEncryptedMessage(userId,m[1],String(i.ciphertext??''),Number(i.keyVersion??1),i.deviceId?String(i.deviceId):undefined));}
 m=path.match(/^\/v1\/messages\/conversations\/([^/]+)\/read$/);if(m&&req.method==='POST')return json(res,200,await markConversationRead(userId,m[1]));m=path.match(/^\/v1\/messages\/device-keys\/([^/]+)$/);if(m&&req.method==='GET')return json(res,200,await listDeviceKeyBundles(userId,m[1]));if(path==='/v1/messages/device-keys'&&req.method==='POST')return json(res,201,await upsertDeviceKeyBundle(userId,await body(req)));
 m=path.match(/^\/v1\/safety\/state$/);if(m&&req.method==='GET')return json(res,200,await getSafetyState(userId,String(url.searchParams.get('targetUserId')??'')));if(path==='/v1/safety/notices'&&req.method==='GET')return json(res,200,{notices:await listModerationNotices(userId)});if(path==='/v1/safety/cases'&&req.method==='GET')return json(res,200,{cases:await listSafetyCases(userId)});if(path==='/v1/safety/report'&&req.method==='POST'){const i=await body(req);const target=i.target?.type==='user'?{userId:String(i.target.id)}:i.target?.type==='post'?{postId:String(i.target.id)}:i.target?.type==='comment'?{commentId:String(i.target.id)}:{messageId:String(i.target?.id??'')};return json(res,201,await reportContent(userId,target,String(i.reason??''),String(i.details??'')));}if(path==='/v1/safety/block'&&(req.method==='POST'||req.method==='DELETE')){const i=await body(req);return json(res,200,req.method==='POST'?await blockUser(userId,String(i.targetUserId??'')):await unblockUser(userId,String(i.targetUserId??'')));}if(path==='/v1/safety/mute'&&(req.method==='POST'||req.method==='DELETE')){const i=await body(req);return json(res,200,req.method==='POST'?await muteUser(userId,String(i.targetUserId??'')):await unmuteUser(userId,String(i.targetUserId??'')));}if(path==='/v1/safety/restrict'&&(req.method==='POST'||req.method==='DELETE')){const i=await body(req);return json(res,200,await restrictUser(userId,String(i.targetUserId??''),req.method==='POST'));}m=path.match(/^\/v1\/safety\/reports\/([^/]+)\/evidence$/);if(m&&req.method==='POST'){const i=await body(req);return json(res,201,await addReportEvidence(userId,m[1],i.mediaId?String(i.mediaId):undefined,String(i.note??'')));}m=path.match(/^\/v1\/safety\/cases\/([^/]+)\/evidence$/);if(m&&req.method==='POST'){const i=await body(req);return json(res,201,await addCaseEvidence(userId,m[1],i.mediaId?String(i.mediaId):undefined,String(i.note??i.details??'')));}m=path.match(/^\/v1\/safety\/cases\/([^/]+)\/appeal$/);if(m&&req.method==='POST'){const i=await body(req);return json(res,200,await submitAppeal(userId,m[1],String(i.text??'')));}
 return false;
}
