import { query, withTransaction } from './db.js';
import { createPlaybackUrl } from './storage-service.js';
import { buildSequenceProfile, scoreSequenceCandidate } from './reels-sequence-model.js';
import { diversifySlate, recordSlateExposure, type ReelRankItem } from './reels-ranking.js';

export type ReelWatchEventType='impression'|'start'|'progress'|'complete'|'skip'|'replay'|'like'|'save'|'share'|'comment'|'not_interested';
const EVENT_TYPES=new Set<ReelWatchEventType>(['impression','start','progress','complete','skip','replay','like','save','share','comment','not_interested']);
function nonNegative(value:unknown):number|null{if(value===undefined||value===null||value==='')return null;const n=Number(value);return Number.isSafeInteger(n)&&n>=0?n:null;}
export async function startReelWatchSession(userId:string,clientSessionId?:string){const r=await query<{id:string;started_at:Date}>(`INSERT INTO reel_watch_sessions(user_id,client_session_id) VALUES($1,$2) RETURNING id,started_at`,[userId,clientSessionId?.slice(0,128)??null]);return{sessionId:r.rows[0].id,startedAt:r.rows[0].started_at.toISOString()};}
export async function endReelWatchSession(userId:string,sessionId:string){const r=await query<{id:string;ended_at:Date}>(`UPDATE reel_watch_sessions SET ended_at=COALESCE(ended_at,now()) WHERE id=$1 AND user_id=$2 RETURNING id,ended_at`,[sessionId,userId]);if(!r.rowCount)throw new Error('Watch session not found');return{sessionId:r.rows[0].id,endedAt:r.rows[0].ended_at.toISOString()};}
export async function recordReelWatchEvents(userId:string,sessionId:string,events:Array<{postId:string;eventType:ReelWatchEventType;position?:number;watchedMs?:number;videoDurationMs?:number;clientEventId?:string}>){if(events.length>100)throw new Error('Too many watch events');return withTransaction(async client=>{const session=await client.query<{ended_at:Date|null}>('SELECT ended_at FROM reel_watch_sessions WHERE id=$1 AND user_id=$2 FOR SHARE',[sessionId,userId]);if(!session.rowCount)throw new Error('Watch session not found');if(session.rows[0].ended_at)throw new Error('Watch session has ended');let accepted=0;for(const event of events){if(!event.postId||!EVENT_TYPES.has(event.eventType)||!event.clientEventId)continue;const watched=nonNegative(event.watchedMs),duration=nonNegative(event.videoDurationMs),position=nonNegative(event.position);if(watched!==null&&duration!==null&&watched>duration)continue;const post=await client.query(`SELECT 1 FROM posts p WHERE p.id=$1 AND p.deleted_at IS NULL AND EXISTS(SELECT 1 FROM post_media m WHERE m.post_id=p.id AND m.media_type='video') AND NOT EXISTS(SELECT 1 FROM user_blocks b WHERE (b.blocker_id=$2 AND b.blocked_id=p.author_id) OR (b.blocker_id=p.author_id AND b.blocked_id=$2))`,[event.postId,userId]);if(!post.rowCount)continue;const r=await client.query(`INSERT INTO reel_watch_events(session_id,user_id,post_id,event_type,position,watched_ms,video_duration_ms,client_event_id) VALUES($1,$2,$3,$4,$5,$6,$7,$8) ON CONFLICT(user_id,client_event_id) DO NOTHING`,[sessionId,userId,event.postId,event.eventType,position,watched,duration,event.clientEventId]);if(r.rowCount)accepted++;}return{accepted};});}

export async function getReelCandidates(userId:string,limit=30){
 const size=Math.min(Math.max(Math.trunc(limit),1),50);const candidateLimit=Math.min(size*8,400);
 const [history,candidates]=await Promise.all([
  query(`SELECT e.post_id,e.created_at,e.watched_ms,e.video_duration_ms,e.replay>0 AS replay,e.event_type='skip' AS skipped,e.event_type='like' AS liked,e.event_type='save' AS saved,e.event_type='share' AS shared,e.event_type='comment' AS commented,p.author_id,COALESCE(cf.fused_features->>'topic','') topic,COALESCE(cf.fused_features->>'format','') format FROM reel_watch_events e JOIN posts p ON p.id=e.post_id LEFT JOIN content_features cf ON cf.post_id=p.id WHERE e.user_id=$1 ORDER BY e.created_at DESC LIMIT 200`,[userId]),
  query(`WITH watched AS(SELECT post_id,MAX(COALESCE(watched_ms,0)) watched_ms,MAX(COALESCE(video_duration_ms,0)) duration_ms FROM reel_watch_events WHERE user_id=$1 GROUP BY post_id),excluded AS(SELECT DISTINCT post_id FROM reel_watch_events WHERE user_id=$1 AND event_type IN('not_interested','skip') AND created_at>now()-interval '7 days'),blocked AS(SELECT blocked_id user_id FROM user_blocks WHERE blocker_id=$1 UNION SELECT blocker_id FROM user_blocks WHERE blocked_id=$1),creators AS(SELECT creator_id,COUNT(*) exposures FROM recommendation_exposure WHERE user_id=$1 AND surface='reels' AND shown_at>now()-interval '7 days' GROUP BY creator_id) SELECT p.id,p.author_id,p.created_at,u.username,u.display_name,m.storage_key,COALESCE(w.watched_ms,0)::int prior_watched_ms,COALESCE(w.duration_ms,0)::int prior_duration_ms,COALESCE(c.exposures,0)::int creator_exposures,COALESCE((SELECT COUNT(*) FROM post_reactions r WHERE r.post_id=p.id),0)::int likes,COALESCE((SELECT COUNT(*) FROM comments cm WHERE cm.post_id=p.id AND cm.deleted_at IS NULL),0)::int comments,COALESCE(cf.fused_features->>'topic','') topic,COALESCE(cf.fused_features->>'format','') format,COALESCE(cf.fused_features->>'semanticSimilarity','0')::double precision semantic_similarity FROM posts p JOIN users u ON u.id=p.author_id JOIN post_media m ON m.post_id=p.id AND m.media_type='video' AND m.sort_order=0 LEFT JOIN watched w ON w.post_id=p.id LEFT JOIN creators c ON c.creator_id=p.author_id LEFT JOIN content_features cf ON cf.post_id=p.id AND cf.status='ready' WHERE p.deleted_at IS NULL AND p.visibility='public' AND NOT EXISTS(SELECT 1 FROM excluded x WHERE x.post_id=p.id) AND NOT EXISTS(SELECT 1 FROM blocked b WHERE b.user_id=p.author_id) ORDER BY p.created_at DESC LIMIT $2`,[userId,candidateLimit])
 ]);
 const profile=buildSequenceProfile(history.rows.map((e:any)=>({postId:e.post_id,creatorId:e.author_id,topic:e.topic||undefined,format:e.format||undefined,watchedMs:Number(e.watched_ms??0),durationMs:Number(e.video_duration_ms??0),replay:e.replay?1:0,skipped:Boolean(e.skipped),liked:Boolean(e.liked),saved:Boolean(e.saved),shared:Boolean(e.shared),commented:Boolean(e.commented),createdAt:new Date(e.created_at).getTime()})));
 const ranked=await Promise.all(candidates.rows.map(async(row:any)=>{const score=scoreSequenceCandidate({postId:row.id,creatorId:row.author_id,topic:row.topic||undefined,format:row.format||undefined,semanticSimilarity:Number(row.semantic_similarity??0),freshness:row.created_at?Math.max(0,Math.min(1,1-(Date.now()-new Date(row.created_at).getTime())/(7*86400000))):0,quality:Math.min(1,(Number(row.likes)+Number(row.comments)*2)/100),longTail:Number(row.creator_exposures)===0?1:Number(row.creator_exposures)<3?.7:.3,creatorExposure:Math.min(1,Number(row.creator_exposures)/6)},profile);const item={postId:row.id,creatorId:row.author_id,topic:row.topic||undefined,score,reason:score>.7?'watch_pattern':row.creator_exposures===0?'fresh_creator':'diverse_discovery'} satisfies ReelRankItem;return {...row,score,item,videoUrl:await createPlaybackUrl(row.storage_key)};}));
 const slate=diversifySlate(ranked.map(x=>x.item),size);const byId=new Map(ranked.map(x=>[x.id,x]));await recordSlateExposure(userId,'reels',slate.map(x=>({postId:x.postId,creatorId:x.creatorId})));return slate.map((item,position)=>{const row=byId.get(item.postId)!;return{id:row.id,author_id:row.author_id,created_at:row.created_at,username:row.username,display_name:row.display_name,videoUrl:row.videoUrl,prior_watched_ms:row.prior_watched_ms,prior_duration_ms:row.prior_duration_ms,creator_exposures:row.creator_exposures,likes:row.likes,comments:row.comments,position,reason:item.reason,score:Number(item.score.toFixed(6))};});
}
