import { query } from './db.js';

const clamp=(v:number,min:number,max:number)=>Math.min(Math.max(Math.trunc(v),min),max);
const clean=(v:string)=>v.trim().replace(/\s+/g,' ').slice(0,120);
export async function getReelPreferences(userId:string){const r=await query(`SELECT mode,topic,quality,preload,autoplay,data_saver,updated_at FROM reel_preferences WHERE user_id=$1`,[userId]);return r.rows[0]??{mode:'for_you',topic:null,quality:'auto',preload:'wifi',autoplay:true,data_saver:false,updated_at:null};}
export async function updateReelPreferences(userId:string,input:Record<string,unknown>){const current=await getReelPreferences(userId);const mode=['for_you','following','topic'].includes(String(input.mode??''))?String(input.mode):String(current.mode);const quality=['auto','low','medium','high'].includes(String(input.quality??''))?String(input.quality):String(current.quality);const preload=['never','wifi','always'].includes(String(input.preload??''))?String(input.preload):String(current.preload);const topic=input.topic==null?current.topic:clean(String(input.topic));const autoplay=typeof input.autoplay==='boolean'?input.autoplay:Boolean(current.autoplay);const dataSaver=typeof input.dataSaver==='boolean'?input.dataSaver:Boolean(current.data_saver);await query(`INSERT INTO reel_preferences(user_id,mode,topic,quality,preload,autoplay,data_saver,updated_at) VALUES($1,$2,$3,$4,$5,$6,$7,now()) ON CONFLICT(user_id) DO UPDATE SET mode=$2,topic=$3,quality=$4,preload=$5,autoplay=$6,data_saver=$7,updated_at=now()`,[userId,mode,topic,quality,preload,autoplay,dataSaver]);return getReelPreferences(userId);}
export async function setReelCreatorFeedback(userId:string,creatorId:string,signal:string){if(!['hide','mute','not_interested','report'].includes(signal))throw new Error('Invalid creator feedback');if(signal==='hide'||signal==='mute'||signal==='not_interested'||signal==='report')await query(`INSERT INTO reel_creator_feedback(user_id,creator_id,signal) VALUES($1,$2,$3) ON CONFLICT(user_id,creator_id,signal) DO UPDATE SET created_at=now()`,[userId,creatorId,signal]);return{ok:true};}
export async function getReelAudio(q:string,limit=20){const term=clean(q);const r=await query(`SELECT id,title,artist,source_url,duration_ms FROM reel_audio_catalog WHERE ($1='' OR title ILIKE '%'||$1||'%' OR artist ILIKE '%'||$1||'%') ORDER BY title LIMIT $2`,[term,clamp(limit,1,50)]);return r.rows;}
export async function getRelatedReels(userId:string,postId:string,limit=12){const r=await query(`SELECT p.id,p.author_id,p.created_at,u.username,u.display_name,p.caption,COALESCE((SELECT count(*)::int FROM post_reactions x WHERE x.post_id=p.id),0) likes,COALESCE((SELECT pm.storage_key FROM post_media pm WHERE pm.post_id=p.id AND pm.media_type='video' ORDER BY pm.sort_order LIMIT 1),'') storage_key FROM posts p JOIN users u ON u.id=p.author_id LEFT JOIN reel_topics rt ON rt.post_id=p.id WHERE p.id<>$2 AND p.deleted_at IS NULL AND p.visibility='public' AND EXISTS(SELECT 1 FROM post_media vm WHERE vm.post_id=p.id AND vm.media_type='video') AND NOT EXISTS(SELECT 1 FROM user_blocks b WHERE (b.blocker_id=$1 AND b.blocked_id=p.author_id) OR (b.blocker_id=p.author_id AND b.blocked_id=$1)) AND (rt.topic IN(SELECT topic FROM reel_topics WHERE post_id=$2) OR p.author_id IN(SELECT author_id FROM posts WHERE id=$2)) ORDER BY p.created_at DESC LIMIT $3`,[userId,postId,clamp(limit,1,24)]);return r.rows;}
