import { query, withTransaction } from './db.js';

const reasons = new Set(['spam','harassment','hate','sexual','violence','scam','privacy','other']);

export async function blockUser(actorId:string,targetId:string){if(actorId===targetId)throw new Error('Cannot block yourself');await withTransaction(async c=>{await c.query('INSERT INTO user_blocks(blocker_id,blocked_id) VALUES($1,$2) ON CONFLICT DO NOTHING',[actorId,targetId]);await c.query('DELETE FROM user_mutes WHERE muter_id=$1 AND muted_id=$2',[actorId,targetId]);});return {ok:true,state:'blocked'};}
export async function unblockUser(actorId:string,targetId:string){await query('DELETE FROM user_blocks WHERE blocker_id=$1 AND blocked_id=$2',[actorId,targetId]);return {ok:true,state:'none'};}
export async function muteUser(actorId:string,targetId:string){if(actorId===targetId)throw new Error('Cannot mute yourself');await query('INSERT INTO user_mutes(muter_id,muted_id) VALUES($1,$2) ON CONFLICT DO NOTHING',[actorId,targetId]);return {ok:true,state:'muted'};}
export async function unmuteUser(actorId:string,targetId:string){await query('DELETE FROM user_mutes WHERE muter_id=$1 AND muted_id=$2',[actorId,targetId]);return {ok:true,state:'none'};}
export async function reportContent(actorId:string,target:{userId?:string;postId?:string;commentId?:string;messageId?:string},reason:string,details=''){if(!reasons.has(reason))throw new Error('Invalid report reason');const keys=Object.entries(target).filter(([,v])=>v);if(keys.length!==1)throw new Error('Exactly one report target is required');const map:{[k:string]:string}={userId:'target_user_id',postId:'target_post_id',commentId:'target_comment_id',messageId:'target_message_id'};const column=map[keys[0][0]];const value=keys[0][1];const r=await query(`INSERT INTO content_reports(reporter_id,${column},reason,details) VALUES($1,$2,$3,$4) RETURNING id,created_at,status`,[actorId,value,reason,details.slice(0,2000)]);return r.rows[0];}
export async function getSafetyState(actorId:string,targetId:string){const r=await query(`SELECT EXISTS(SELECT 1 FROM user_blocks WHERE blocker_id=$1 AND blocked_id=$2) blocked, EXISTS(SELECT 1 FROM user_mutes WHERE muter_id=$1 AND muted_id=$2) muted`,[actorId,targetId]);return r.rows[0];}
