import { query, withTransaction } from './db.js';

const reasons = new Set(['spam','harassment','hate','sexual','violence','scam','privacy','impersonation','self_harm','illegal','other']);

export async function blockUser(actorId:string,targetId:string){if(actorId===targetId)throw new Error('Cannot block yourself');await withTransaction(async c=>{await c.query('INSERT INTO user_blocks(blocker_id,blocked_id) VALUES($1,$2) ON CONFLICT DO NOTHING',[actorId,targetId]);await c.query('DELETE FROM user_mutes WHERE muter_id=$1 AND muted_id=$2',[actorId,targetId]);await c.query('DELETE FROM user_restrictions WHERE user_id=$1 AND target_user_id=$2',[actorId,targetId]).catch(()=>undefined);});return {ok:true,state:'blocked'};}
export async function unblockUser(actorId:string,targetId:string){await query('DELETE FROM user_blocks WHERE blocker_id=$1 AND blocked_id=$2',[actorId,targetId]);return {ok:true,state:'none'};}
export async function muteUser(actorId:string,targetId:string){if(actorId===targetId)throw new Error('Cannot mute yourself');await query('INSERT INTO user_mutes(muter_id,muted_id) VALUES($1,$2) ON CONFLICT DO NOTHING',[actorId,targetId]);return {ok:true,state:'muted'};}
export async function unmuteUser(actorId:string,targetId:string){await query('DELETE FROM user_mutes WHERE muter_id=$1 AND muted_id=$2',[actorId,targetId]);return {ok:true,state:'none'};}
export async function restrictUser(actorId:string,targetId:string,restricted:boolean,reason='safety'){if(actorId===targetId)throw new Error('Cannot restrict yourself');if(restricted)await query(`INSERT INTO user_restrictions(user_id,target_user_id,reason) VALUES($1,$2,$3) ON CONFLICT(user_id,target_user_id) DO UPDATE SET reason=EXCLUDED.reason`,[actorId,targetId,reason.slice(0,200)]);else await query('DELETE FROM user_restrictions WHERE user_id=$1 AND target_user_id=$2',[actorId,targetId]);return {ok:true,state:restricted?'restricted':'none'};}
export async function reportContent(actorId:string,target:{userId?:string;postId?:string;commentId?:string;messageId?:string},reason:string,details=''){if(!reasons.has(reason))throw new Error('Invalid report reason');const keys=Object.entries(target).filter(([,v])=>v);if(keys.length!==1)throw new Error('Exactly one report target is required');const map:{[k:string]:string}={userId:'target_user_id',postId:'target_post_id',commentId:'target_comment_id',messageId:'target_message_id'};const column=map[keys[0][0]];const value=String(keys[0][1]);const safeDetails=details.slice(0,2000);const r=await query(`INSERT INTO content_reports(reporter_id,${column},reason,details) VALUES($1,$2,$3,$4) RETURNING id,created_at,status`,[actorId,value,reason,safeDetails]);await query(`INSERT INTO safety_cases(reporter_id,report_id) VALUES($1,$2) ON CONFLICT DO NOTHING`,[actorId,r.rows[0].id]);return r.rows[0];}
export async function getSafetyState(actorId:string,targetId:string){const r=await query(`SELECT EXISTS(SELECT 1 FROM user_blocks WHERE blocker_id=$1 AND blocked_id=$2) blocked, EXISTS(SELECT 1 FROM user_mutes WHERE muter_id=$1 AND muted_id=$2) muted, EXISTS(SELECT 1 FROM user_restrictions WHERE user_id=$1 AND target_user_id=$2) restricted`,[actorId,targetId]);return r.rows[0];}
export async function addReportEvidence(actorId:string,reportId:string,mediaId?:string,note=''){const own=await query('SELECT 1 FROM content_reports WHERE id=$1 AND reporter_id=$2',[reportId,actorId]);if(!own.rowCount)throw new Error('Report not found');if(!mediaId&&!note.trim())throw new Error('Evidence note or media is required');const r=await query(`INSERT INTO content_report_evidence(report_id,media_id,note) VALUES($1,$2,$3) RETURNING id,created_at`,[reportId,mediaId||null,note.slice(0,1000)]);return r.rows[0];}
export async function listSafetyCases(actorId:string){const r=await query(`SELECT s.id,s.state,s.appeal_text,s.appeal_status,s.created_at,s.updated_at,s.report_id,cr.reason,cr.status report_status FROM safety_cases s LEFT JOIN content_reports cr ON cr.id=s.report_id WHERE s.reporter_id=$1 ORDER BY s.updated_at DESC LIMIT 100`,[actorId]);return r.rows;}
export async function submitAppeal(actorId:string,caseId:string,text:string){const body=text.trim().slice(0,4000);if(body.length<10)throw new Error('Appeal needs more detail');const r=await query(`UPDATE safety_cases SET appeal_text=$1,appeal_status='submitted',state='appealed',updated_at=now() WHERE id=$2 AND reporter_id=$3 AND state<>'closed' RETURNING id,appeal_status,state,updated_at`,[body,caseId,actorId]);if(!r.rows[0])throw new Error('Safety case not found or closed');return r.rows[0];}
export async function listModerationNotices(actorId:string){const r=await query(`SELECT id,object_type,object_id,title,body,action,appeal_available,created_at FROM moderation_notices WHERE user_id=$1 ORDER BY created_at DESC LIMIT 100`,[actorId]);return r.rows;}
export async function listSecurityEvents(actorId:string){const r=await query(`SELECT id,event_type,resource_type,resource_id,metadata,created_at FROM security_events WHERE user_id=$1 ORDER BY created_at DESC LIMIT 200`,[actorId]);return r.rows;}
export async function acknowledgeSecurityAlert(actorId:string,id:string){const r=await query(`UPDATE security_alerts SET acknowledged_at=COALESCE(acknowledged_at,now()) WHERE id=$1 AND user_id=$2 RETURNING id,acknowledged_at`,[id,actorId]);if(!r.rows[0])throw new Error('Security alert not found');return r.rows[0];}
export async function secureAccount(actorId:string){await query('UPDATE sessions SET revoked_at=now() WHERE user_id=$1 AND revoked_at IS NULL',[actorId]);await query(`UPDATE security_alerts SET acknowledged_at=COALESCE(acknowledged_at,now()) WHERE user_id=$1 AND acknowledged_at IS NULL`,[actorId]);return {ok:true,action:'sessions_revoked_and_alerts_acknowledged'};}
